### ISSUE TITLE
NullReferenceException in IMatcher.Matches

### ISSUE THREAD

**Issue by eduherminio** [moq/moq4#1005]
I may have found a bug/issue while using `Verify(Expression<Action<T>>, Times, string)`.

A suspicious `NullReferenceException` is triggered in `Moq.Match.Moq.IMatcher.Matches(Object, Type)`.

I created [a sample repo](https://github.com/eduherminio/MoqIssue) to easily reproduce this issue.

**Comment by stakx** [comment]
Seems to me this is your mistake, not a bug inside Moq.

In [this line of code](https://github.com/eduherminio/MoqIssue/blob/392f7f501fd8551f3d110c62c505129a731f3e4c/VerifyLogExtensions.cs#L16):

```csharp
It.Is<TException>(e => e.GetHashCode() == ex.GetHashCode()),
```

you haven't considered the possibility that `e` might be `null`, therefore `e.GetHashCode()` will throw a `NullReferenceException`.

This case appears to be triggered [in your failing test](https://github.com/eduherminio/MoqIssue/blob/392f7f501fd8551f3d110c62c505129a731f3e4c/VerifyLogExtensionsTest.cs#L41-L42):

```csharp
_service.LogMessage(_level, _level.ToString());   // Logging a simple message
_logger.VerifyLog(_exception, _exception.Message, Times.Once());  // => NullReferenceException
```

You're logging a *message*, not an exception.

**Comment by eduherminio** [comment]
That's it, nice catch!
The test was designed like that to trigger the mysterious exception.
`It.Is<TException>(e => (e != null ? e.GetHashCode() : -1) == ex.GetHashCode())` does the trick
