### ISSUE TITLE
Moq Setup with Generic methods - Ordering of derived types

### ISSUE THREAD

**Issue by eden188** [moq/moq4#1015]
Hi,

I have recently upgraded Moq from 4.12.0 to 4.14.1 and have come across a number of issues relating to the use of generic methods. To begin with, I want to confirm if one of the problem that I have encountered, whether it is an issue or have I missed out some release documentation and have made a mistake.

The code below will hopefully describes the problem that I have encountered.

**Create a base class:**
```
    public class BaseType
    {
        public string Name { get; set; }
    }
```

**Create a derive class:**
```
    public class DerivedType : BaseType
    {
        public string Identifier { get; set; }
    }

```
**Create an Interface for mock:**
```
    public interface ITestInterface
    {
        List<T> GetTest<T>() where T: BaseType;
    }
```
**Create the unit test:**
```
    using System.Collections.Generic;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Moq;
    using Unity;
    using Unity.Lifetime;

    [TestClass]
    public class MoqUnitTests
    {
        [TestMethod]
        public void MoqTest()
        {
            var container = new UnityContainer();
            container.RegisterInstance<ITestInterface>(Mock.Of<ITestInterface>(), new ContainerControlledLifetimeManager());

            var derivedTypes = new List<DerivedType>
            {
                new DerivedType {Identifier = "123", Name = "ABC"}
            };

            var baseTypes = new List<BaseType>
            {
                new BaseType {Name = "ABC"}
            };

            Mock.Get(container.Resolve<ITestInterface>()).Setup(m => m.GetTest<DerivedType>()).Returns(derivedTypes);
            Mock.Get(container.Resolve<ITestInterface>()).Setup(m => m.GetTest<BaseType>()).Returns(baseTypes);

            var mockInterface = container.Resolve<ITestInterface>();

            mockInterface.GetTest<DerivedType>();
            mockInterface.GetTest<BaseType>();
        }
    }
```

**!Note on the order of the _Setups()_.**
```
            Mock.Get(container.Resolve<ITestInterface>()).Setup(m => m.GetTest<DerivedType>()).Returns(derivedTypes);
            Mock.Get(container.Resolve<ITestInterface>()).Setup(m => m.GetTest<BaseType>()).Returns(baseTypes);
```

If you run the test, you would get the following error:
![image](https://user-images.githubusercontent.com/51329234/80670391-9eafab00-8a9e-11ea-99c5-13685ad95384.png)

However, if the order is swapped, so that the **BaseType** is set up before the **DerivedType**, the test would pass.
```
            Mock.Get(container.Resolve<ITestInterface>()).Setup(m => m.GetTest<BaseType>()).Returns(baseTypes);
            Mock.Get(container.Resolve<ITestInterface>()).Setup(m => m.GetTest<DerivedType>()).Returns(derivedTypes);
```
![image](https://user-images.githubusercontent.com/51329234/80671432-b2104580-8aa1-11ea-9a43-7ec385521a41.png)

I would be grateful if you could confirm if this is an issue or something that I have missed out. This issue is causing quite a headache with our existing code base, so I would appreciate any guidance please. Thanks in advance.

**Comment by stakx** [comment]
Yes, there was a change regarding this (this is most likely caused by #904), and this is intended behavior: in Moq, always set up more specific setups after less specific ones to prevent the latter from "shadowing"/overriding the former. That rule has always applied to setups when it comes to arguments & argument matchers; it now applies to generic type arguments, too.

**Comment by stakx** [comment]
I was going to answer that you should always order your setups from less specific to more specific (or, in this case, set up the `BaseType` variant before the `DerivedType` one) to prevent setups from being "shadowed"/overridden, but it appears that something else may be going on here. I'll take a look later.

**Comment by eden188** [comment]
Hi, thank you for the prompt reply and explanation. I have made the necessary changes in our code base to make it work. I'll pass this information onto our team to avoid future mistakes like this.

I'll leave this thread open in case you do find anything.

Many thanks.

**Comment by stakx** [comment]
Yes, there was a change (most likely #904 mentioned in the changelog), but it was an intended one:

The rule for ordering setups from less specific to more specific has always held for arguments and argument matchers: say, if you set up something with `It.Is<int>(x => x < 10)` and then `It.is<int>(x => x < 1000)`, the latter setup will also cover `x < 10` and the former setup will never get matched; it is being "shadowed" by the latter.

Now the same rule applies also to generic type arguments (as it perhaps always should have): a setup for `BaseType` will also match `DerivedType`, and `baseTypes` obviously isn't a valid return value in that case.
