### ISSUE TITLE
Extension methods for verify

### ISSUE THREAD

**Issue by binaryevents** [moq/moq4#1021]
Hi,
I'm using ths CQRS pattern for my apps. So almost everything is ether an 
```cs
public interface ICommandHandler<TCommand>
{
    Task Handle(TCommand command);
}
```
or an 
```cs
public interface IQueryHandler<TQuery, TResult>
{
    Task<TResult> Handle(TQuery query);
}
```

To get rid of some noise in my tests, I added some extension methods like `SetupHandle(TCommand command)`.

Now, on the verify side I ran into a problem with the extension
```cs
        public static void VerifyHandle<TCommand>(this Mock<ICommandHandler<TCommand>> mock, TCommand command)
            where TCommand : class,ICommand
            => mock.Verify(x=>x.Handle(command), Times.Once);
```

```cs
// ok:
commandHandlerMock.Verify(x=>x.Handle(It.IsAny<TestCommand>()), Times.Once); 
// fails
// Expected invocation on the mock once, but was 0 times: x => x.Handle(null)
commandHanderMock.VerifyHandle(It.IsAny<TestCommand>()); // Fails. 
```

Is there any possibility to pass the `It.IsAny<TCommand>()` to the method in a way it's recognised by the mock? 

Thanks for your help!

**Comment by stakx** [comment]
The problem here is that when passing `It.IsAny<TestCommand>` to your extension method, you are actually *executing* that method. The return value of that method is absolutely meaningless; it's the presence of that method in a LINQ expression tree that matters. So your extension method needs to accept a parameter of type `Expression<Func<TCommand, bool>>`, then you need to extract that `LambdaExpression`'s `.Body` and embed it in the expression tree that you're passing to `mock.Verify`. (You'll likely need to construct the final LINQ expression trees manually using the static `Expression.*` factory methods.

**Comment by stakx** [comment]
@binaryevents, does the above answer your question?

**Comment by binaryevents** [comment]
Sadly I could not work out a working solution in the short time I got for this problem. I think I'm not skilled enough with Expressions. I'll try again next weekend.

**Comment by stakx** [comment]
If you always verify using `It.IsAny<SomeCommand>` you could, of course, completely circumvent the LINQ expression tree manipulation by making your `VerifyHandle` extension method generic: have it accept a parameter `TCommand`, then move the `It.IsAny<TCommand>` into `VerifyHandle`. Then the C# compiler will do the expression tree building for you, at the price of losing the flexibility to use a different matcher.

**Comment by binaryevents** [comment]
Yay. I finaly got it working. I'll post my solution here for anyone with similar issues.
```cs
public static void VerifyHandle<TCommand>(this Mock<ICommandHandler<TCommand>> setup,
        Expression<Func<TCommand, bool>> command,
        Times? times= null
) 
where TCommand : class, ICommand 
{
    Expression<Action<ICommandHandler<TCommand>>> expression = x => x.Handle(null);
     setup.Verify(HandlerParameterReplacer.Replace(expression, ItExpr.Is(command)), times ?? Times.Once());
}

private static class HandlerParameterReplacer
{
    public static Expression<T> Replace<T>(Expression<T> expression,  Expression target)
        => new ParameterReplacerVisitor<T>(target).VisitAndConvert(expression);	
         
    private class ParameterReplacerVisitor<TOutput> : ExpressionVisitor
    {
        private readonly Expression _target;
        public ParameterReplacerVisitor(Expression target) => _target = target;
    
        internal Expression<TOutput> VisitAndConvert<T>(Expression<T> root) 
                => (Expression<TOutput>)Visit(root);
         
        protected override Expression VisitConstant(ConstantExpression node) => _target;
    }
}
```

This way it's possible to mimimize 
```cs
mock.Verify(x => x.Handle(It.Is<TestCommand>(command => command.ID == 5)));
```
to
```cs
mock.VerifyHandle(command => command.ID == 5);
```

Thank you @stakx for your hints.
