### ISSUE TITLE
API Documentation page broken.

### ISSUE THREAD

**Issue by Camios** [moq/moq4#1023]
The wiki Home page has a link to API docs here http://www.nudoq.org/#!/Projects/Moq
But that link redirects due to error to the nudoq home page

**Comment by stakx** [comment]
NuDoq has been abandoned long ago, I'd say. The Moq API docs there are hopelessly out of date (#354).

I've started some work to get up-to-date documentation online (#799) but haven't found the time to finish that. I'll update the wiki once I'm making further progress.

Regarding the redirect error that you reported, that must have been an intermittent malfunction, it appears to work fine again now so I'll close this issue.

**Comment by sbrl** [comment]
Nudoq seems to be a spam wordpress site for me:

![image](https://user-images.githubusercontent.com/9929737/100649548-8193d100-333a-11eb-92ff-7c6991726a69.png)

Some actual docs (even if autogenerated) would be very nice indeed, as the quickstart is singularly unhelpful and confusing.

**Comment by stakx** [comment]
It's perhaps time to bury that NuDoq link. I've removed it. See my above post and #799 for the replacement plan.
