### ISSUE TITLE
VerifySet breaks with System.NullReferenceException for WriteOnly-Indexed-Properties

### ISSUE THREAD

**Issue by Epicycle23** [moq/moq4#1036]
Version: 4.14.4
Language: Visual Basic
Environment: Visual Studio 2019 16.6.2

Steps to reproduce

``` vb
<TestClass()>
Public Class UnitTest1


    Public Interface ITest
        WriteOnly Property Value(key As String)
    End Interface

    <TestMethod()>
    Public Sub TestMethod1()

        Dim mock As New Mock(Of ITest)
        mock.Object.Value("key") = "value"
        mock.VerifySet(Sub(x) x.Value("key") = It.IsAny(Of String), Times.Once)

    End Sub

End Class
```

Was working fine with version 4.8.3.
I ran into this issue when trying to update to 4.14.4

**Comment by stakx** [comment]
Hi @Epicycle23 , thanks for reporting. I'll take a look a little later.

**Comment by stakx** [comment]
OK, this broke between versions 4.10.1 and 4.11.0, and the problem lies in this line of code: 

https://github.com/moq/moq4/blob/be325ce3971d7d4efa432f8ebcbe10763f027e91/src/Moq/ExpressionExtensions.cs#L262

This is supposed to extract the method from the expression tree, and obviously always choosing the getter won't do any good for write-only indexers.

**Comment by stakx** [comment]
OK, this should be fixed. The expression tree logic I had to change is somewhat difficult to understand, so I might do some refactoring before releasing a bugfix version on NuGet. It should happen sometime during the next few days.

Thanks again for reporting this regression!

**Comment by Epicycle23** [comment]
Thanks for the fast response/fix, can't wait to update.

**Comment by stakx** [comment]
> can't wait to update

If you're in a hurry and you cannot wait, you can use the CI NuGet feed at https://ci.appveyor.com/nuget/moq4, or download the NuGet packages generated on the CI server from https://ci.appveyor.com/project/MobileEssentials/moq4/build/artifacts.

But I'll likely do a release today or tomorrow.
