### ISSUE TITLE
Add .NET Standard 2.1

### ISSUE THREAD

**Issue by twsl** [moq/moq4#1041]
Since .NET Core 3.1 is an LTS version, support for .NET Standard 2.1 should definitly be added.

**Comment by stakx** [comment]
Yes @twsl, you're right.

Please note that as of now, our main dependency [DynamicProxy](https://github.com/castleproject/Core) still only has .NET Standard 1.x targets, so adding .NET Standard 2.x targets here at Moq won't actually have much benefit... you'll still get an awful lot of .NET Standard 1.x dependencies installed.

I'm actively working on a DynamicProxy release that also has .NET Standard 2.x targets, but there's quite a bit of other work left to do before an updated version can be released.

**Comment by twsl** [comment]
Nice to hear, let me know if you need any help with that.

**Comment by twsl** [comment]
Actually, DynamicProxy already has multi targets, [2.0 and 2.1](https://github.com/castleproject/Core/blob/master/src/Castle.Core/Castle.Core.csproj#L6) to be precise. Which is why a created a pull request to target 2.1 as well

**Comment by stakx** [comment]
Yes, leaving the PR open is fine. I won't merge it right away as some bug fixes have to go in first that will end up with a patch-version release. I'll look at your PR for the next minor version release. (We can add the `netstandard2.1` target before Castle.Core does, it won't do much good, but it also won't do any harm.)
