### ISSUE TITLE
Setup virtual new method returns null

### ISSUE THREAD

**Issue by rgarrison12345** [moq/moq4#1044]
Hello, I have code that looks like the below. I have to do a new implementation of ExecuteReaderAsync because the DbDataReader function is not override-able.  What do I need to do to get the mocked function to return a value.  I have to do a new implementation of the function and make it virtual.

_command.Setup(x => x.ExecuteReaderAsync(CommandBehavior.SingleRow, source.Token)).ReturnsAsync(new CustomDbReader()).Verifiable();

**Comment by stakx** [comment]
Non-overridable methods cannot be set up. Re-implementing an interface method is not the same thing as overriding, you'll end up with two distinct methods: you get one when you cast your variable to the base class' type (e.g. `(DbCommand)command`); you'll end up with the other when casting to the interface (e.g. `(IDbCommand)command`). If some component expects a `DbCommand` argument, and that component calls the method, they will therefore in all probability *not* end up with your reimplemented version but with the non-overridable one from the base class.

That being said, in Moq you'd re-implement an interface method by using `.As<TInterface>()`:

```csharp
classMock.As<TInterface>().Setup(m => m.Method(...))...
var interfaceMockObj = (TInterface)classMock.Object;
interfaceMockObj.Method(...);
```
