### ISSUE TITLE
Mock<T>.Reset() clears event handlers

### ISSUE THREAD

**Issue by kkerchmar** [moq/moq4#1046]
If I create a `Mock<T>` and use that `mock.Object` as a constructor parameter for a class I want to test, and that constructor adds a handler to an event provided by `T`, there does not seem to be a way to clear the `Setup` and Invocations without nuking the event handler- calling `Reset` clears `Setup`, among other things, but it clears the event handlers too. What's the intended use case for clearing event handlers, and why is there no way to prevent this? I ask because offhand from the perspective of what I *want* this to do right now, this particular fact seems to make `Reset` basically useless with no alternative. I want to clear all the Setups and invocations, but I need to keep the same instance of the class I'm testing, and it only adds event handlers in the constructor.

**Comment by stakx** [comment]
`mock.Reset()` may be useless for you, but I dare say that doesn't make it useless for everyone else. As for why it works the way it does: there's perhaps no ultimate reason, that's how it's been contributed to this open-source community project.

There's currently no API for what you need to do. There is `mock.Invocations.Clear()`, but there isn't `mock.Setups.Clear()`, though that latter one may be added in the future if some tricky questions about its interaction with verification state can be figured out.

I suggest in the meantime, you simply recreate a fresh mock.

**Comment by kkerchmar** [comment]
Thank you for your reply.

>  I dare say that doesn't make it useless for everyone else

I am also quite sure that's true :)

> but there isn't mock.Setups.Clear()1

A full reset of everything on a mock other than just the event handlers would be useful to me. I wouldn't specifically need to only clear the Setups while not clearing Invocations.

> simply recreate a fresh mock

The obvious way I'm thinking of right now to use a new mock would be to provide access to what is currently a private field to replace the mock (by making it an internal property or something goofy like that). This hypothetical property would have to subscribe the event handlers on the new instance of the dependency that is being replaced. That's not really ideal, and this is probably something that would have to be done for quite a few dependencies in quite a few classes if this is the approach I settle on. It's completely contrary to the whole notion of constructor dependency injection.

Another option I guess might be to use Castle DynamicProxy2 to create a shim between my class and the Mock instance, where the Mock can be swapped out freely without the class I'm testing realizing anything happened. Honestly, that might be the workaround I'll look in to.

Another workaround could be to Setup more wide setups and to rely more heavily on verification than Setup. My gripe with this is that if something unexpected occurs, verification is raised long after the problem actually occurred, and the error shows up in the unit test, rather than the call site that did the unexpected thing. By Setup-ing only exactly what I really want to allow, the failure occurs at the point that the class I'm testing does something unexpected.

**Comment by stakx** [comment]
> A full reset of everything on a mock other than just the event handlers would be useful to me. I wouldn't specifically need to only clear the Setups while not clearing Invocations.

From the library API's point of view, it makes more sense to implement a few fine-grained reset methods that people can combine however they need, vs. a larger number of more specific methods for coarser-grained combination resets that will be hard to name & distinguish.

I don't think it makes sense to add a method for *precisely* what you need. It simply seems too specific.

**Comment by kkerchmar** [comment]
Works for me, honestly, as long as I can reset what I need one way or another. 

For now, though, I implemented a workaround that I mentioned previously. I have a `MockShim<T>` that places a Castle DynamicProxy over the `Mock<T>.Object` with an interceptor that tracks all event add and remove calls. The event handlers are cached and then if I need to reset the mock, I do a full reset and then reapply the event handlers I've cached.

It's a little hacky, but it works and that's good enough for me for now. However, I would look forward to not needing this workaround if more granular resets ever make it to a future release. 

Thank you for your replies and time!

**Comment by siprbaum** [comment]
@kkerchmar Any chance you can post the code? Looks like a valuable example, even if someone else is stumbling over the same issue you have

**Comment by kkerchmar** [comment]
Sure, I can do that. It's a good chunk of code. This is not thoroughly tested, YMMV.

First, the `Castle.DynamicProxy` interceptor:

```csharp
using System;
using System.Collections.Generic;
using System.Reflection;
using System.Linq;
using Castle.DynamicProxy;

/// <summary>
/// Captures event handler add and remove calls so that the event handlers
/// can be restored later.
/// </summary>
internal class EventInterceptor : IInterceptor
{
    private const string EventAddPrefix = "add_";
    private const string EventRemovePrefix = "remove_";

    // Using a HashSet instead of a List here would remove the need to do
    // a linear search when we remove a delegate. However, it also loses
    // the guarantee of stable ordering. A tree-based data structure that
    // maintains order and provides superior lookup time-complexity could
    // be used, but I don't know if .NET has one off the top of my head. My
    // use case is not concerned with performance, so I'm not going to
    // bother. Feel free to improve this!
    private readonly Dictionary<string, Tuple<MethodInfo, List<Delegate>>> _handlers =
        new Dictionary<string, Tuple<MethodInfo, List<Delegate>>>();

    public void Intercept(IInvocation invocation)
    {
        // This interception caches event handlers that are subscribed by
        // filtering everything other than event handler add and remove
        // method calls and storing them along with the event handlers that
        // were being registered.

        if (invocation.Method.Name.StartsWith(EventAddPrefix) &&
            invocation.Arguments.Length == 1 &&
            invocation.Arguments[0] is Delegate handlerToAdd)
        {
            if (!this._handlers.TryGetValue(
                invocation.Method.Name,
                out Tuple<MethodInfo, List<Delegate>> eventInfo))
            {
                eventInfo = Tuple.Create(invocation.Method, new List<Delegate>());
                this._handlers.Add(invocation.Method.Name, eventInfo);
            }

            eventInfo.Item2.Add(handlerToAdd);
        }
        else if (invocation.Method.Name.StartsWith(EventRemovePrefix) &&
            invocation.Arguments.Length == 1 &&
            invocation.Arguments[0] is Delegate handlerToRemove &&
            this._handlers.TryGetValue(
                invocation.Method.Name,
                out Tuple<MethodInfo, List<Delegate>> eventInfo))
        {
            List<Delegate> cachedHandlersForEvent = eventInfo.Item2;

            // Yeah, I know, a linear search. See the comment on the
            // declaration of the data structure.
            for (int i = 0; i < eventInfo.Item2.Count; ++i)
            {
                if (cachedHandlersForEvent[i].Equals(handlerToRemove))
                {
                    cachedHandlersForEvent.RemoveAt(i);
                    break;
                }
            }
        }

        // We aren't modifying any behavior, just observing.
        invocation.Proceed();
    }

    /// <summary>
    /// Reregisters all cached event handlers with the specified target.
    /// </summary>
    /// <param name="target">
    /// The instance that the cached event handlers should be restored to.
    /// The <see cref="Type"/> of this parameter must be the same as the
    /// <see cref="Type"/> of what was intercepted. According to the
    /// intended use case, it really ought to be the same actual instance.
    /// </param>
    public void RestoreEventHandlers(object target)
    {
        Type targetType = target.GetType();

        var registrations =
            from pair in this._handlers
            let eventInfo = pair.Value
            let methodInfo = eventInfo.Item1
            let delegates = eventInfo.Item2
            from handler in delegates
            select new { MethodInfo = methodInfo, Handler = handler };

        foreach (var registration in registrations)
        {
            if (registration.MethodInfo.ReflectedType != targetType)
            {
                throw new Exception(
                    $"The specified target of type '{targetType}' does " +
                    "not match the intercepted type " +
                    $"'{registration.MethodInfo.ReflectedType}'.");
            }

            registration.MethodInfo.Invoke(
                target,
                new object[] { registration.Handler });
        }
    }
}
```

And then the shim class that wraps the `Mock<T>`:

```csharp
using Castle.DynamicProxy;
using Moq;

/// <summary>
/// This class provides a workaround for the fact that calling
/// <see cref="MockExtensions.Reset(Mock)"/> wipes out the registered event
/// handlers from the specified <see cref="Mock{T}"/>.
/// </summary>
internal class MockShim<T> where T : class
{
    private readonly ProxyGenerator _proxyGenerator = new ProxyGenerator();
    private readonly EventInterceptor _eventInterceptor = new EventInterceptor();

    public MockShim(Mock<T> mock)
    {
        this.Mock = mock;

        // This following proxy generation code isn't thoroughly tested,
        // but it worked for my use case. I didn't see an obvious way to
        // just handle everything with one single proxy creation call.

        if (typeof(T).IsInterface)
        {
            this.Object = this._proxyGenerator.CreateInterfaceProxyWithTarget(
                mock.Object,
                this._eventInterceptor);
        }
        else
        {
            this.Object = this._proxyGenerator.CreateClassProxyWithTarget(
                mock.Object,
                this._eventInterceptor);
        }
    }

    /// <summary>
    /// Provides the underlying <see cref="Mock{T}"/> so that you can do
    /// normal setup and verification work. This class has no interest in
    /// duplicating the surface area of the <see cref="Mock{T}"/> class for
    /// the sole benefit of encapsulating the <see cref="Mock{T}.Object"/>
    /// property, as nice as that would be.
    /// </summary>
    public Mock<T> Mock { get; }

    /// <summary>
    /// Provides a replacement instance of the type that is being mocked.
    /// This should be used instead of the <see cref="Mock.Object"/>
    /// property in all cases where you will need to restore lost event
    /// handler registrations.
    /// </summary>
    public T Object { get; }

    /// <summary>
    /// Resets the underlying <see cref="Mock{T}"/>, but also restores any
    /// event handlers that were previously registered to events on the
    /// <see cref="Mock{T}.Object"/>.
    /// </summary>
    public void ResetMock()
    {
        // The reset call is bundled with the restoration because this
        // makes it impossible to restore events if they have not been
        // discarded, which would possibly result in duplicate
        // registrations? Is that even possible? Not sure. Better safe than
        // sorry.
        this.Mock.Reset();

        // The interceptor has tracked event handler add and remove calls,
        // so we can now use it to replace the event handlers that have
        // just been discarded.
        this._eventInterceptor.RestoreEventHandlers(this.Mock.Object);
    }
}
```

**Comment by siprbaum** [comment]
Thx for sharing! It is really appreciated.
