### ISSUE TITLE
Access invocation arguments when using Throws/ThrowsAsync during Setup

### ISSUE THREAD

**Issue by mcdevmc** [moq/moq4#1048]
When defining the setup of a method call, I am able to access the invocation arguments when defining the return value, as shown in the sample from the QuickStart guide:
```c#
// access invocation arguments when returning a value
mock.Setup(x => x.DoSomethingStringy(It.IsAny<string>()))
		.Returns((string s) => s.ToLower());
```
However, I don't seem to be able to do the same when setting up a method with Throws or ThrowsAsync, for example something like:
```c#
// unable to access invocation arguments when throwing a value (this is will not build)
mock.Setup(x => x.DoSomethingStringy(It.IsAny<string>()))
		.Throws((string s) => new Exception($"Tried to DoSomethingStringy with {s.ToLower()}"));

// or, a case that seems particularly useful is setting properties on custom exception
mock.Setup(x => x.FindByIdAsync(It.IsAny<int>()))
		.ThrowsAsync((int id) => new IdNotFoundException(id, "Can't find the given id"));
```
I can work around this by using Callback to throw an exception instead: 
```c#
mock.Setup(x => x.DoSomethingStringy(It.IsAny<string>()))
		.Callback((string s) => throw new Exception($"Tried to DoSomethingStringy with {s.ToLower()}"));
```
but it would be much clearer and more consistent if I could use the Throws/ThrowsAsync syntax instead

**Comment by stakx** [comment]
Support for argument access has been added to `Throws` in #1191 (thanks again, @adam-knights!).

Regarding `ThrowsAsync`, let's wait with adding support there for now. That method might very well be marked obsolete (see https://github.com/moq/moq/issues/53#issuecomment-755221874), so there is no point in adding dozens of method overloads as long as we're not sure whether they'll stay around long-term.
