### ISSUE TITLE
Mock methods that take or return a Span<T>

### ISSUE THREAD

**Issue by trampster** [moq/moq4#1049]
Expression Trees cannot contain a Span<T>.  Moq seems to be built around expression trees.

How can Span support be added to the mock library

**Comment by stakx** [comment]
Perhaps check out the upcoming Moq version 5 over at https://github.com/moq/moq. For the current version 4 at this repo here, (last time I checked) I don't think there's any way to add full support for `Span<T>` et al. due to limitations in the LINQ expression tree API and reflection.

**Comment by stakx** [comment]
I'll close this issue since in all likelihood there's nothing we can do about `Span` (unfortunately). If this question pops up again in the future, I'll probably reopen & pin it.
