### ISSUE TITLE
No way of checking if a Mock has any "Setups" configured

### ISSUE THREAD

**Issue by wizofaus** [moq/moq4#1053]
I have a bunch of a tests in a test class, some of which use a mock of a particular object, calling Setup as needed to configure it, an others of which use the "real" un-mocked behaviour.  I was hoping this could be achieved by having a function that either returned a real object or a mock depending on whether the mock had been configured using Setup(). But as far as I can see there's no way to determine this other than by reflection (checking the "internal" Setups property). Is this by design?

**Comment by stakx** [comment]
Have you checked the latest version of Moq? `Setups` has been made public. Just query `mock.Setups.Any()`.
