### ISSUE TITLE
Is it possible to mock a method and return a value that's set by its callback?

### ISSUE THREAD

**Issue by InteXX** [moq/moq4#1069]
Here's the problem detail:

https://stackoverflow.com/q/64235559

The issue is that `oResult` may contain any number of validation errors, to be determined at runtime. I can't just pass in an expected value, because I need to test for any/all of those errors.

I tried [this construct](https://github.com/Moq/moq4/wiki/Quickstart#callbacks) from the Wiki:

```
var mock = new Mock<IFoo>();
var calls = 0;
mock.Setup(foo => foo.GetCount())
	.Callback(() => calls++)
	.Returns(() => calls);
```

Here's the adaptation for my code:

```
Dim oCallback as Action(Of TUser, String, TCity)
Dim oResult As IdentityResult

oCallback = Sub(User, Password, City)
              If City.IsNothing Then
                oResult = IdentityResult.Failed($"{NameOf(City)} is required.")
              Else
                oResult = IdentityResult.Success
              End If

              If oResult Is IdentityResult.Success Then
                oResult = oManager.UserValidator.ValidateAsync(User).Result

                If oResult Is IdentityResult.Success Then
                  oResult = oManager.PasswordValidator.ValidateAsync(Password).Result

                  If oResult Is IdentityResult.Success Then
                    User.PasswordHash = oManager.PasswordHasher.HashPassword(Password)
                    Users.Add(User)

                    User.CityId = City.Id
                    User.City = City

                    City.Users.Add(User)
                  End If
                End If
              End If
            End Sub

oManagerMock.Setup(oCreateSetup).Callback(oCallback).Returns(Function() oResult)
```

But I'm getting an 'Object not initialized' precompiler warning for `oResult`:

![image](https://user-images.githubusercontent.com/10966749/95689744-5e149b80-0bbf-11eb-804f-c95564ab6e95.png)

Can this be accomplished with Moq?

**Comment by stakx** [comment]
> Can this be accomplished with Moq?

This has more to do with basic VB.NET than with Moq.

> But I'm getting an 'Object not initialized' precompiler warning for oResult:
>
> ```vb.net
> .Returns(Function() oResult)
> ```

Have you tried this change:

```diff
-Dim oResult As IdentityResult
+Dim oResult As IdentityResult = Nothing  ' or some other ignored initial value
```

That being said, using `Function() oResult` rather than just `oResult` is the way to go.

**Comment by InteXX** [comment]
That works the first time through, but on subsequent runs `tcs.SetResult(...)` produces an error:

> An attempt was made to transition a task to a final state when it had already completed.

I tried reinstantiating `tcs` within the callback, but as you may expect that results in a deadlock.

All of this can be avoided by instantiating a new `UserManager` for each request, which isn't the worst requirement there ever was.

Thanks! I think this'll do it.

**Comment by stakx** [comment]
I think I was wrong on (3), instead of `.Returns(tcs.Task)` you need to do `.Returns(() => tcs.Task)` to always return the latest task; otherwise the first one gets cached inside the setup and returned on all invocations.

**Comment by InteXX** [comment]
That works, thanks.

I still get the error, but I can reinstantiate `tcs` inside the callback without getting the deadlock.

**Comment by InteXX** [comment]
I think we can close this issue; the problem is solved quite nicely.

Thanks for your help.

**Comment by stakx** [comment]
Glad to hear!

**Comment by InteXX** [comment]
I posted it as an [answer](https://stackoverflow.com/a/64324780).

**Comment by stakx** [comment]
> I posted it as an answer.

I believe your code there still has a bug:

```vb.net
                      oSource = New TaskCompletionSource(Of IdentityResult)
                      oSource.SetResult(oResult)
```

I suspect that you need to swap the order of these two statements; otherwise the task that got returned the first time will be thrown away and thus never complete.

**Comment by InteXX** [comment]
Hm, but wouldn't that eviscerate the result?

**Comment by InteXX** [comment]
I tried it, but it brings back the deadlock.

**Comment by stakx** [comment]
> eviscerate

Thanks for teaching me a new word... I had to look it up. 😆

> wouldn't that eviscerate the result?

Ah... I see. The code happens to work because the `Callback` lambda always runs to completion before the `Returns`,so it doesn't really matter that you're essentially dropping the very first task completion source.

But something about your code strikes me as suboptimal, e.g. you're synchronously blocking on an async method in your `Callback` lambda. And now I'm really wondering whether things have been overcomplicated. You're setting up an async method, which needs to return some kind of `Task` or `Task<>`, so why not merge `Callback` into `Returns`?

Forgive me for using a C# example, I haven't done any VB.NET work for the past 3 years. Here's the general idea:

```csharp
oManagerMock.Setup(manager => manager.CreateAsync(...))
            .Returns(async (Db.User user, string password, Db.City city) =>
                     {
                         ...
                         oResult = await oManager.UserValidator.ValidateAsync(User)
                         //        ^^^^^ async instead of blocking with:           .Result;
                         ...
                         return oResult;
                     });
```

You might possibly have to help out the compiler with the type of that async lambda, but it should work, and it would be a much cleaner solution. I obviously haven't tried it out myself, but perhaps give it a try.

**Comment by InteXX** [comment]
Beauteous Maximus :-)

OK, I'll update my answer.

**Comment by InteXX** [comment]
Beauteous Maximus :-)

OK, I'll update the answer.

**Comment by InteXX** [comment]
@stakx 

Everything is working well now.

I was blocked for nearly a week on these two (this and [#1067](https://github.com/moq/moq4/issues/1067)). I'm exceedingly grateful for your assistance—I couldn't have done it without you.

Next time I see you I'll buy you a milkshake :-)

**Comment by stakx** [comment]
> Next time I see you I'll buy you a milkshake :-)

Thanks a ton, a milkshake 🥛 (lactose free, preferably) would be greatly appreciated! 😁
