### ISSUE TITLE
`IInvocation` should expose `Exception` along with `ReturnValue`

### ISSUE THREAD

**Issue by stakx** [moq/moq4#1070]
#921 which just got merged added a `ReturnValue` property to `IInvocation`, which allows user code to find out what got returned from a mocked invocation. The author of that PR (@MaStr11) suggested that an `Exception` property also be added for similar reasons; if an invocation throws, user code might want to find out what it threw.

I think we ought to add `Exception Exception { get; }` to `IInvocation` for completeness. Incidentally, we'd then reach [parity with Moq 5](https://github.com/moq/moq/blob/a76c3cea64a4d9be4934d048c19d9c041ef487d5/src/Stunts/Stunts/IMethodReturn.cs#L16-L20) in this particular regard.

#### Some implementation notes

* I [mentioned in that PR](https://github.com/moq/moq4/pull/921#issuecomment-706759795) that the addition of an `Exception` property wouldn't make `Invocation` heavier (by adding a corresponding field). The existing field `Invocation.returnValue` could serve double duty (holding either a return value, or an exception). We'd need to ensure that methods returning an exception as a regular return value should not report that via the new `Exception` property.

* Also [mentioned in the PR] is the likely Moq [code location](https://github.com/moq/moq4/blob/947c6a0aa1bbf265b5555ad0a84beb5bfc53b4e2/src/Moq/ProxyFactories/CastleProxyFactory.cs#L99-L107) where `Exception` would be set.

**Comment by MaStr11** [comment]
> P.S. @MaStr11: In case you were wondering where we stand regarding thrown exceptions, I didn't forget about it, but thought it would be cleaner to do that in a separate PR, to keep this one as straightforward as it was.

> If you would like to submit a PR that adds an Exception Exception { get; } property to IInvocation (as you described in (1) above), please feel free to do so, and I'll merge that, too.

> It shouldn't be too hard to do, setting the Invocation.Exception property would likely happen in a catch block being added there. (Ideally, we would make this addition without adding a new field to Invocation—to keep it as lightweight as possible–but that's not essential, it'd be more of an optimization. The existing returnValue field could serve double duty since an invocation cannot both return a value and throw. We'd only have to make sure that returned Exception objects won't leak out through the Exception property; this could be done by wrapping thrown exceptions in an internal type that only we can check for.)

From https://github.com/moq/moq4/pull/921#issuecomment-706759795

@stakx  I will give it a try.
