### ISSUE TITLE
Setters on deep mocks no longer work after updating to 4.14.6 from old version 

### ISSUE THREAD

**Issue by vruss** [moq/moq4#1071]
I've noticed after upgrade from an older version of Moq to the latest that setters on deep mocks no longer work. It's a bit of an annoyance to fix 100s of test cases with this issue.

#### Interfaces
```C#
public interface IFoo
{
	int Property { get; set; }
}

public interface IBar
{
	IFoo Foo { get; set; }
}
```

#### Dosen't work
```C#
var bar = Mock.Of<IBar>(x => x.Foo.Property == 123);
Assert.AreEqual(123, bar.Foo.Property);

bar.Foo.Property = 321;
Assert.AreEqual(321, bar.Foo.Property); // Expected:<321>. Actual:<123>.
```

#### Works
```C#
var bar = Mock.Of<IBar>(x => x.Foo == Mock.Of<IFoo>(y => y.Property == 123));
Assert.AreEqual(123, bar.Foo.Property);

bar.Foo.Property = 321;
Assert.AreEqual(321, bar.Foo.Property);
```

**Comment by vruss** [comment]
Is this related to #1039?

**Comment by stakx** [comment]
This stopped working with version 4.14.0; more precisely, with cb6b71a60df08a9c62b44ad6a33b608e4c0e11a1. I'll look into it.

**Comment by vruss** [comment]
Thank you for fixing it so quickly! 
@stakx any chance of this fix being included in an earlier 4.14.7 release?

**Comment by stakx** [comment]
> any chance of this fix being included in an earlier 4.14.7 release

I suppose I could do that, yes.

**Comment by vruss** [comment]
> I suppose I could do that, yes.

That would be so great!

**Comment by stakx** [comment]
@vruss, I've pushed a hotfix release version 4.14.7 to NuGet. It should become available shortly.
