### ISSUE TITLE
Mock.Of of Excel interop classes fails to initialize

### ISSUE THREAD

**Issue by killergege** [moq/moq4#1072]
I have a project that has a lot of tests on Excel interop classes.  
Those were working fine with my current test project (net452, Moq 4.8, Microsoft.Office.Interop.Excel v12.0.4518.1014, NUnit v3.12...)

But after upgrading to Moq 4.14 & Microsoft.Office.Interop.Excel v15.0.4795.1000, all the Mock.Of on interop classes fail to initialize.
I had other setup issues following interop upgrade (because they stated to use `dynamic` in some places, instead of `object`) but it seems that this is a different problem.

```
[Test]
public void Test_Works()
{
                var worksheet = new Mock<Worksheet>();
                var parent = new Mock<Workbook>();
                parent.Setup(x => x.FullName).Returns(string.Empty);
                worksheet.Setup(x => x.Parent).Returns(parent.Object);
}

[Test]
public void Test_Fails()
{
                var worksheet = new Mock<Worksheet>();
                var v = Mock.Of<Workbook>(x => x.FullName == string.Empty);
                worksheet.Setup(x => x.Parent).Returns(v);
}
```

The error is different based on the Moq version, but they all fail : 

Moq v4.13.1

```
  Message:
    System.ArgumentException : Method 'Moq.Language.Flow.IReturnsResult`1[Microsoft.Office.Interop.Excel.Workbook] Returns(System.String)' declared on type 'Moq.Language.IReturns`2[Microsoft.Office.Interop.Excel.Workbook,System.String]' cannot be called with instance of type 'Moq.Mock`1[System.String]'
  Stack Trace:
    Expression.ValidateCallInstanceType(Type instanceType, MethodInfo method)
    Expression.ValidateStaticOrInstanceMethod(Expression instance, MethodInfo method)
    Expression.Call(Expression instance, MethodInfo method, IEnumerable`1 arguments)
    MockSetupsBuilder.ConvertToSetup(Expression targetObject, Expression left, Expression right)
    MockSetupsBuilder.ConvertToSetupProperty(Expression targetObject, Expression left, Expression right)
    MockSetupsBuilder.ConvertToSetup(Expression left, Expression right)
    MockSetupsBuilder.VisitBinary(BinaryExpression node)
    BinaryExpression.Accept(ExpressionVisitor visitor)
    ExpressionVisitor.Visit(Expression node)
    ExpressionVisitor.VisitLambda[T](Expression`1 node)
    Expression`1.Accept(ExpressionVisitor visitor)
    ExpressionVisitor.Visit(Expression node)
    ExpressionVisitor.VisitUnary(UnaryExpression node)
    MockSetupsBuilder.VisitUnary(UnaryExpression node)
    UnaryExpression.Accept(ExpressionVisitor visitor)
    ExpressionVisitor.Visit(Expression node)
    ExpressionVisitor.VisitArguments(IArgumentProvider nodes)
    ExpressionVisitor.VisitMethodCall(MethodCallExpression node)
    MockSetupsBuilder.VisitMethodCall(MethodCallExpression node)
    MethodCallExpression.Accept(ExpressionVisitor visitor)
    ExpressionVisitor.Visit(Expression node)
    MockQueryable`1.Execute[TResult](Expression expression)
    Queryable.First[TSource](IQueryable`1 source, Expression`1 predicate)
    Mock.Of[T](Expression`1 predicate, MockBehavior behavior)
    Mock.Of[T](Expression`1 predicate)
    UnitTest1.Test_Fails() line 22
```

Moq v4.14.6

```
  Message:
    System.ArgumentException : Object instance was not created by Moq.
    Parameter name: mocked
  Stack Trace:
    Mock.Get[T](T mocked)
    lambda_method(Closure , Workbook )
    Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
    lambda_method(Closure )
    EnumerableExecutor`1.Execute()
    IQueryProvider.Execute[S](Expression expression)
    Queryable.First[TSource](IQueryable`1 source, Expression`1 predicate)
    lambda_method(Closure )
    MockQueryable`1.Execute[TResult](Expression expression)
    Queryable.First[TSource](IQueryable`1 source, Expression`1 predicate)
    Mock.Of[T](Expression`1 predicate, MockBehavior behavior)
    Mock.Of[T](Expression`1 predicate)
    UnitTest1.Test_Fails() line 22
```

Is it expected?
Do you have a workaround ?
Replacing all the `Mock.Of<>()` by `new Mock<>() + setup` is a lot of work and adds a lot of "useless" rows...

**Comment by stakx** [comment]
> But after upgrading to Moq 4.14 & Microsoft.Office.Interop.Excel v15.0.4795.1000

@killergege, can you tell which of the two updates causes the issue?

**Comment by killergege** [comment]
We are using the nuget package to get the interop objects : https://www.nuget.org/packages/microsoft.office.interop.excel/
Our build server don't have Excel so I guess this is enough. If not I'll try to get you what you asked but in my corporate network this is not easy to send files outside :).

**Comment by stakx** [comment]
Ah, excellent! I wasn't aware of that NuGet package. Thank you for pointing me towards it... that should indeed be sufficient.

**Comment by stakx** [comment]
@killergege, I've compared the Excel COM interop libraries. They appear to differ in (among other things) the presence or absence of `[CompilerGenerated]` custom attributes on the `Workbook` and related types, and it appears to be the presence of that attribute that causes stuff inside Moq to go wrong. Moq queries for this attribute in some places to recognize captured variables and anonymous types (those can show up in LINQ queries that use query comprehension syntax). In the current version, Moq erroneously enters into [this "then" clause](https://github.com/moq/moq4/blob/5b8fbc477a67fc36415e3114cb4a4a4492a91e4c/src/Moq/Linq/MockSetupsBuilder.cs#L155) when it shouldn't... and that's what makes your code fail.

Not yet sure how to fix this properly, but at least a fix is possible. A very crude fix would consist of adding an `&& !pe.Type.IsImport` check in the line of code referenced above... but that would be hardly pretty. I'll try to come up with something better.

**Comment by stakx** [comment]
@killergege, since previous versions of Moq failed with different error messages, I can't completely rule out other causes for failure in a real-world use case. If problems with mocking `Workbook` still occur after upgrading Moq to the upcoming version, please post again here, and we'll reopen this issue.
