### ISSUE TITLE
Verify() fails on items not explicitely marked a Verifiable()

### ISSUE THREAD

**Issue by killergege** [moq/moq4#1073]
I think the issue is similar to #1018 

When using nested properties, it seems that Verify() is behaving as if Verifiable() was applied on the auto-generated properties.
The issue appeared in 4.14.

To reproduce:
Solution : https://github.com/killergege/moq_issue1073
```
public class Tests
    {
        [Test]
        public void Test1()
        {
            var mock = new Mock<IClassA>();
            mock.Setup(x => x.Items.Count).Returns(1);
            mock.Setup(x => x.Method()).Verifiable();

            mock.Object.Method();

            //Expected to pass
            //Passes in 4.13, but fails in 4.14 with "IClassA x => x.Items: This setup was not matched."
            mock.Verify();
        }
    }

    public interface IClassA
    {
        public IList<string> Items { get; set; }
        public void Method();
    }
```

**Comment by stakx** [comment]
Thanks for reporting, @killergege. Yes, it's definitely related to #1018, or more precisely, to the automatic recursion algorithm that Moq uses for verification, which leads to quite a few unintuitive situations like this one.

I'm still investigating ways to give up recursive verification as safely as possible. It's quite a puzzle, so I'm afraid this is going to take some time.
