### ISSUE TITLE
Setup on method with parameters (Interface) cannot invoke callback with parameters (Implementation).

### ISSUE THREAD

**Issue by TDroogh** [moq/moq4#1078]
I'm retrieving the (runtime) error message `Invalid callback. Setup on method with parameters (Interface) cannot invoke callback with parameters (Implementation).`

What i'm doing is 
```csharp
mock
  .Setup(x => x.DoSomething(It.IsAny<Implementation>()))
  .Callback((Implementation impl) =>
  {
     //Do something
  });
```
Method 'DoSomething' accepts parameter of interface Interface, while class Implementation implements the interface

Now i do get the error message, it expects a callback with type Interface as parameter. However, this would require me to cast the interface to the implementation to use implementation specific members, like this:
```csharp
mock
  .Setup(x => x.DoSomething(It.IsAny<Implementation>()))
  .Callback((Interface if) =>
  {
     var impl = if as Implementation;
     //Do something
  });
```

The reason i'm submitting this issue is that the same construction works for the Returns method. The following code does work.
```csharp
mock
  .Setup(x => x.DoSomething(It.IsAny<Implementation>()))
  .Returns((Implementation impl) =>
  {
      //Do something
      return returnValue;
  });
```

I think i'd be a nice addition to add as it would be simplified.

I'm using Moq 4.14.7 btw.

**Comment by stakx** [comment]
You'll either need to...

* upcast the `Interface`-typed argument to `Implementation` in your callbsck, or

* make `DoSomething` generic (`where TArg : Interface`). With this option, the use of `It.IsAny<Implementation>()` will determine `TArg := Implementation` and you'll then be able to use that type directly in your callback signature.

And yes, the callback validation logic for `Returns` is less strict / different that the one for `Callback`. That has been intentionally left that way to maintain backwards compatibility.

**Comment by TDroogh** [comment]
Changing the signature of the method is no option as it is an interface from a third party library.

What i don't get is why making `Callback` more 'forgiving' is breaking backward compatibility. It is making the call less restrictive, but the current validation logic should still be working, right?

**Comment by stakx** [comment]
> What i don't get is why making Callback more 'forgiving' is breaking backward compatibility.

It isn't. Making `Returns` more strict would be.

Making `Callback` more forgiving would be the wrong direction, while making `Returns` more strict likely would be.

**Comment by TDroogh** [comment]
I don't get the 'wrong direction' argument. I'm setting up a method with an argument of a specific implementation of the parameter, how is it wrong to expect the callback to accept the same argument?

**Comment by stakx** [comment]
> I don't get the 'wrong direction' argument. I'm setting up a method with an argument of a specific implementation of the parameter, how is it wrong to expect the callback to accept the same argument?

I'll let the C# compiler answer this one. Try this:

```csharp
interface Interface { }

class Implementation : Interface { }

Action<Interface> callback = (Implementation arg) => {
    // ...
};
```

> error CS1661: Cannot convert lambda expression to type `Action<Interface>` because the parameter types do not match the delegate parameter types
> error CS1678: Parameter 1 is declared as type `Implementation` but should be `Interface`
