### ISSUE TITLE
ArgumentException 'Unsupported expression' during Setup

### ISSUE THREAD

**Issue by InteXX** [moq/moq4#1080]
Here's the setup:

```c#
using Moq;
using System;
using System.Data.Entity;
using System.Linq.Expressions;

namespace MoqRepro2
{
  class Program
  {
    static void Main(string[] args)
    {
      Mock<Context> contextMock;
      Expression<Func<Context, DbSet<Role>>> rolesSetup;

      contextMock = new Mock<Context>();
      rolesSetup = Context => (DbSet<Role>)Context.Roles;

      contextMock.Setup(rolesSetup);
    }
  }
}
```

Here's the context:

```c#
using Microsoft.AspNet.Identity.EntityFramework;
using System;
using System.Data.Entity;

namespace MoqRepro2
{
  class Context : IdentityDbContext<User, Role, String, IdentityUserLogin, IdentityUserRole, IdentityUserClaim>
  {
    public virtual DbSet<City> Cities { get; set; }
  }
}
```

And here's the model:

```c#
using Microsoft.AspNet.Identity.EntityFramework;

namespace MoqRepro2
{
  class Role : IdentityRole
  {
    public int? CityId { get; set; }
    public City City { get; set; }
  }
}
```

The error at `contextMock.Setup(rolesSetup)` on line 18 is:

> Unsupported expression: (DbSet<Role>)Context.Roles

I've uploaded a small repro project here:

https://1drv.ms/u/s!AodXF_j3BiWkheURAp5KHaoreMCdgg

What is meant by 'unsupported expression' in this context, and how must I modify the setup in order to avoid creating one?

**Comment by stakx** [comment]
> What is meant by 'unsupported expression' in this context, and how must I modify the setup in order to avoid creating one?

In this particular case, Moq does not know how to deal with a type cast in the setup expression. Once you drop it, the setup should work:

```diff
 Mock<Context> contextMock;
-Expression<Func<Context,  DbSet<Role>>> rolesSetup;
+Expression<Func<Context, IDbSet<Role>>> rolesSetup;

 contextMock = new Mock<Context>();
-rolesSetup = Context => (IDbSet<Role>)Context.Roles;
+rolesSetup = Context =>              Context.Roles;

 contextMock.Setup(rolesSetup);
```

**Comment by InteXX** [comment]
@stakx 

Impressive.

But this works for only the two Identity-derived models (`Role` and `User`). It doesn't work for `Base`-derived models (`City`, etc.). Oddly, `City` wants a `DbSet<T>` and `Role`/`User` want an `IDbSet<T>`. I have no idea why this is the case.

Background: I'm trying to roll all of these into a single extension method (see [here](https://stackoverflow.com/a/64479533)). Without a common way of setting these up, it'll quickly get out of control as my database schema grows.

Overloaded methods seem to accommodate this:

```vb
<Extension>
Public Sub Setup(Of TEntity As Class)(
    Instance As Mock(Of Db.Context),
    Entities As List(Of TEntity),
    DbSetSetup As Expression(Of Func(Of Db.Context, DbSet(Of TEntity)))
  )
End Sub

<Extension>
Public Sub Setup(Of TEntity As Class)(
    Instance As Mock(Of Db.Context),
    Entities As List(Of TEntity),
    DbSetSetup As Expression(Of Func(Of Db.Context, IDbSet(Of TEntity)))
  )
End Sub
```

This results in a bit of duplicated code, but if that's the worst of it I can live with it.

Thanks!

**Comment by InteXX** [comment]
> What does a type cast in a setup expresion mean? Does it mean that you want the setup to only trigger when you also type-cast later on, when you exercise the mock?

Yes.

**Comment by stakx** [comment]
@InteXX: Type casts aren't something that can be intercepted at runtime. Impossible to do. Therefore the error message.

**Comment by InteXX** [comment]
But then it shouldn't be working for `DbSet<City>`, right?

**Comment by InteXX** [comment]
Is it worth considering updating that error message a bit, to clarify a bit what the actual problem is?

**Comment by stakx** [comment]
I don't think so. The total number of [types of expressions](https://docs.microsoft.com/en-us/dotnet/api/system.linq.expressions.expressiontype) (approx. 60) is far greater than the number of expressions that Moq understands (approx. 6), so if we started adding specific error messages, we'd ideally do it for all unsupported expressions... meaning we'd end up with way too much error handling code. Not worth it IMHO, especially given that this repository doesn't see that kind of peoblem report very often.

A Roslyn analyzer might be better suited for that kind of thing.

**Comment by InteXX** [comment]
Oh, OK.

I was under the impression that the message could be built up at runtime using the faulty expression, maybe something along the lines of;

> `TypeA` could not be cast to `TypeB`

Perhaps I've simplified things too much.
