### ISSUE TITLE
nudoq.org domain has expired

### ISSUE THREAD

**Issue by samjetski** [moq/moq4#1086]
Hi @kzu, just noticed that nudoq.org has expired again on GoDaddy.
Given Moq DocFX (#799) isn't up yet, is this worth renewing this for the time being? Per #701
Cheers!

**Comment by kzu** [comment]
Site is abandoned, no point in renewing the domain. I'd rather sponsor someone to work on a docfx-based site instead ;)

**Comment by stakx** [comment]
I think it's time I got DocFX up and running.

I stopped working on that PR a while ago because I had planned to integrate the DocFX build with CI, but realised that DocFX builds are non-deterministic.

So I am probably going to make DocFX site deployment a manual step. I'll keep you posted.
