### ISSUE TITLE
[Bug?] MockException: invocation failed with mock behavior Strict. All invocations on the mock must have a corresponding setup.

### ISSUE THREAD

**Issue by voroninp** [moq/moq4#1088]
### Steps to Reproduce

For this code and Strict mode I get :

> MockException: SendAsync(null, CancellationToken) invocation failed with mock behavior Strict.
All invocations on the mock must have a corresponding setup.

For Loose mode result is `null`, and not an instance of `HttpResponseMessage`.

But should it be like that if I defined behaviour for `public abstract` method?!

```CSharp
void Main()
{
    var method = typeof(TestHandler).GetMethods(BindingFlags.NonPublic | BindingFlags.Instance).Single(m => m.Name == "SendAsync");
	
    var mock = new Mock<TestHandler>(MockBehavior.Strict);
    mock.Setup(x => x.MockableSendAsync(It.IsAny<HttpRequestMessage>(), It.IsAny<CancellationToken>())).ReturnsAsync(new HttpResponseMessage());

    var result = method.Invoke(mock.Object, new object[] { null, CancellationToken.None}) as Task<HttpResponseMessage>;
    result.Wait();
}

public abstract class TestHandler : HttpMessageHandler
{
    public abstract Task<HttpResponseMessage> MockableSendAsync(HttpRequestMessage request, CancellationToken cancellationToken);
    protected override Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
    {
        return this.MockableSendAsync(request, cancellationToken);
    }
}
```

### Expected Behavior
I expect that protected overridden method works as it is.

**Comment by kzu** [comment]
Still not decided on how protected setups would work on v5. You can follow https://github.com/moq/moq/issues/51.

Thanks

**Comment by stakx** [comment]
I am going to close this issue since it is now in this repo, and an answer for Moq v4 has already been given above.
