### ISSUE TITLE
Setup with the `in` parameter fails for MockBefavior.Strict

### ISSUE THREAD

**Issue by MihailsKuzminsDG** [moq/moq4#1094]
Sorry, if such an issue has already been created, but I haven't found it in the search.
Moq version: 4.14.7

When an interface method as a parameter with the `in` keyword, `MockBehavior.Strict` cannot verify a setup.

Interface example:
```c#
public interface IInterface
{
    void SetDate(in DateTime dateTime);
}
```
Setup example:
```c#
var mockRepository = new MockRepository(MockBehavior.Strict);
var mock = mockRepository.Create<IInterface>();

mock
    .Setup(x => x.SetDate(It.IsAny<DateTime>()));
```
So, running a test where the method `SetDate` is accessed throws an exception that the method failed with the mock behaviour Strict. Removing the `in` keyword from the method (i.e. `void SetDate(DateTime dateTime);`) resolves the issue.

These has been an issue with the `ref` keyword, but it looks like there is no functionality for the `in` keyword.

Is there any workaround for the issue?
I would be glad for any possible directions :)

**Comment by stakx** [comment]
`in` parameters are by-ref parameters, so I guess you should use `It.Ref<DateTime>.IsAny`.

**Comment by MihailsKuzminsDG** [comment]
> `in` parameters are by-ref parameters, so I guess you should use `It.Ref<DateTime>.IsAny`.

@stakx Thank you for the fast and correct answer. It works for the `in` parameters as well
