### ISSUE TITLE
Could not build in Linux using xbuild of mono

### ISSUE THREAD

**Issue by rupertsoftdev** [moq/moq4#1095]
Could not build successfully in Linux (Ubuntu) using xbuild of mono with the following error:

CSC: error CS0009: Metadata file `.../packages/Moq.4.14.7/lib/net45/Moq.dll' does not contain valid metata

some information:
XBuild Engine Version 14.0
Mono, Version 6.8.0.105

Please advise what to do.  It would be greatly appreciated.

Thanks,
Ruperts

**Comment by stakx** [comment]
From the [Mono 5.0.0 release notes](https://www.mono-project.com/docs/about-mono/releases/5.0.0/#xbuild):

> Mono’s historical implementation of MSBuild called `xbuild` is now deprecated. We encourage everyone to switch to the `msbuild` command which is now available on Mono as well.

You're using Mono 6, so you should probably switch to MSBuild.

**Comment by rupertsoftdev** [comment]
@stakx ,  I have the version of mono 6.8.0.105 in my ubuntu docker and msbuild is missing with the installation
![image](https://user-images.githubusercontent.com/6970889/98521998-22005380-22af-11eb-860f-82661dad7073.png)


I followed instructions from this link: https://medium.com/@hudsonmendes/build-net-4-5-on-linux-in-5-minutes-and-see-what-it-is-like-848ea45fc667

please advise. 

Thannks,
Ruperts

**Comment by stakx** [comment]
This is not the right place to ask for help with installing or using Mono, I am sure you'll find instructions on their homepage.

**Comment by rupertsoftdev** [comment]
Thank you very much @stakx .
I was just hoping that this was already raised and there is just something needs to be done.
Thanks very much for the help

Thanks,
Ruperts
