### ISSUE TITLE
Recursive property setup overrides previous setups

### ISSUE THREAD

**Issue by jamesfoster** [moq/moq4#110]
Apologies for the cryptic subject. It's difficult to explain this without an example.

Here's a failing test:

``` c#
var baz = Mock.Of<Baz>(x => x.Value == "beforeBaz");
var qux = Mock.Of<Qux>(x => x.Value == "beforeQux");

var bar = Mock.Of<Bar>(x =>
    x.Baz == baz &&
    x.Qux == qux);

var obj = Mock.Of<Foo>(x => x.Bar == bar);

var mock = Mock.Get(obj);

obj.Bar.Baz.Value.ShouldBe("beforeBaz"); // Pass
obj.Bar.Qux.Value.ShouldBe("beforeQux"); // Pass

mock.SetupGet(x => x.Bar.Baz.Value).Returns("test");

obj.Bar.Baz.Value.ShouldBe("test"); // Pass
obj.Bar.Qux.Value.ShouldBe("beforeQux"); // Fail
```

Effectively I've set up the return value of `Foo.Bar`, `Bar.Qux` and `Qux.Value` separately and then used the call the `SetupGet` to override the value of `Foo.Bar.Baz.Value`. This replaces the previously setup `Foo.Bar` with a new mock without the registration of `Bar.Qux`.

Not sure whether this is an edge case you want to support but I'm not sure of the best way to work around it. Any help would be greatly appreciated

**Comment by stakx** [comment]
After the recent merges, this might finally be fairly easy to fix.
