### ISSUE TITLE
Provide a quickstart that actually compiles

### ISSUE THREAD

**Issue by Meai1** [moq/moq4#112]
An IFoo is used but I have to implement everything myself. Resharper does a good job, but still, for example I dont understand how to fulfill the lazy evaluated return param.

Why not give the IFoo in the example?

**Comment by stakx** [comment]
Fixed the code in most sections of the quickstart (all except the "Event" and "Linq to Mocks" secions), so I'll close this for now. In my opinion, the quickstart guide would profit much more from examples that were slightly more "real-world" examples; the `IFoo` type currently given is just a big blob of random methods and properties that don't make much sense. Contrast this e.g. with NInject's ninja and weapon examples; that kind of example code (while not exactly representative of real-world code :-) is still much more illustrative than what we currently have for Moq.
