### ISSUE TITLE
Upgrade to Castle.Core 3.2.1 because of Mono

### ISSUE THREAD

**Issue by ztone** [moq/moq4#113]
There is a fix in Castle.Core castleproject/Core@9f0577fc6e5750b7d0eac6a550a58b28192bdbde that fixes http://stackoverflow.com/questions/18034341/system-collections-generic-keynotfoundexception-with-mono-but-not-microsofts

<code>git tag --contains 9f0577fc</code> in Castle.Core show that this fix was released first in 3.2.1 but Moq is using 3.2.0.  A diff shows that there wasn't to much code change so I'm hoping that an upgrade will not be to painful.

Main reason for asking for this is that we are trying to get ScriptCs test to run on mono and because we are using Moq, this is a huge blocker.

**Comment by kzu** [comment]
plz reopen if this still fails. we've bumped to Castle.Core 4.0 now
