### ISSUE TITLE
Issue on Dispose when using a Mock on WebClient and Strict behavior

### ISSUE THREAD

**Issue by MarienMonnier** [moq/moq4#129]
**What steps will reproduce the problem?**

Using this code :

```
Mock<WebClient> mockWebClient = new Mock<WebClient>(MockBehavior.Strict);
mockWebClient.Protected().Setup("Dispose", ItExpr.IsAny<bool>());
using (WebClient client = mockWebClient.Object))
{
}
```

**What is the expected output? What do you see instead?**
It should work without error. But starting with the version 4.2.1408.619, I have an exception:

```
Test method XXX threw exception: 
Moq.MockException: IDisposable.Dispose() invocation failed with mock behavior Strict.
All invocations on the mock must have a corresponding setup.
Result StackTrace:  
at Moq.ExtractProxyCall.HandleIntercept(ICallContext invocation, InterceptorContext ctx, CurrentInterceptContext localctx)
   at Moq.Interceptor.Intercept(ICallContext invocation)
   at Moq.Proxy.CastleProxyFactory.Interceptor.Intercept(IInvocation invocation)
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at Castle.Proxies.WebClientProxy.Dispose()
   at ...
```

The problem being that I can't mock the Dispose() method, it's not virtual. The Dispose method calls the protected virtual Dispose(bool) method, so my way should be the correct one.

**What version of the product are you using? On what operating system?**
Works correctly with versions (from nuget): 4.2.1312.1622, 4.2.1402.2112
Doesn't work with versions: 4.2.1408.619, 4.2.1408.717 (latest ATM)
My operating system is Windows 7, I tested with Frameworks 4, 4.5 and 4.5.1

**Please provide any additional information below.**
/

Thank you

**Comment by aleks091** [comment]
Thanks ! @drieseng
