### ISSUE TITLE
Mock name should be a part of method verification error message

### ISSUE THREAD

**Issue by bl-nero** [moq/moq4#140]
This would simplify debugging in case of multiple mocks of the same class verified through MockRepository.

**Comment by stakx** [comment]
I am not sure everyone would agree that this will make for better exception messages. So I'd like to ask, does the mock's name have to be in the exception `.Message` itself, or might it also suffice to augment the `MockVerificationException` type with an additional property such as `.MockName`? That way, people interested in knowing which mock caused the exception can check that extra property.

**Comment by bl-nero** [comment]
Wow, I'm sorry, but I no longer have the context. I had to look at the project to even remind myself what's this. :) It's been years.

**Comment by stakx** [comment]
I know, I know. :) But I would feel bad about closing an old issue without any comment or at least attempting to follow up on it. If this is no longer important to you, we can also close this.

**Comment by bl-nero** [comment]
Yup, no longer important. Thanks! :)
