### ISSUE TITLE
Update wiki from MockFactory to MockRepository

### ISSUE THREAD

**Issue by bartlannoeye** [moq/moq4#153]
As pull requests are not possible on the wiki (afaik), I'm only able to log the issue.

Since MockFactory is obsolete and will be removed in Moq 5, the [Quickstart wiki page](https://github.com/Moq/moq4/wiki/Quickstart) should reflect this and show an example using the MockRepository instead of the MockFactory.

**Comment by stakx** [comment]
Done. Thank you!
