### ISSUE TITLE
Quickstart should include SetupSequence

### ISSUE THREAD

**Issue by jjmartin** [moq/moq4#165]
it would be nice if the Quickstart had a reference/example for the SetupSequence extension.

**Comment by warrendodsworth** [comment]
I Second that.
The Quick start shows everything but a simple Context Mock and CRUD operations testing.

Finding setup quite unobvious.

**Comment by stakx** [comment]
Added under [Miscellaneous](https://github.com/moq/moq4/wiki/Quickstart#miscellaneous).
