### ISSUE TITLE
ProxyGenerationException using 3+ observer

### ISSUE THREAD

**Issue by herecydev** [moq/moq4#167]
I've made a [gist](https://gist.github.com/herecydev/081a7703866f19005b95) to demonstrate the ProxyGenerationException I get when trying to mock an interface with multiple observers.

The issue seems to only occur when running at least 3 observers (2 is fine strangely).

![image](https://cloud.githubusercontent.com/assets/11328618/7315290/09ddffac-ea64-11e4-8908-5a9e67e418c4.png)

The issue lies in [this block of code](https://github.com/castleproject/Core/blob/master/src/Castle.Core/DynamicProxy/Generators/TypeElementCollection.cs) @kkozmic 

[Raised](https://github.com/castleproject/Core/issues/88) on CastleProject repo

Currently using **Moq 4.2.1502.0911**

**Comment by stakx** [comment]
This is currently being dealt with over at Castle.Core, there is nothing further to do in Moq except to upgrade Castle.Core once a future version is published. I'll track this in #402.
