### ISSUE TITLE
Can we package the PDB in the NuGet Drop?

### ISSUE THREAD

**Issue by aolszowka** [moq/moq4#170]
It is helpful to have the PDB files produced by the build for debugging issues that may be related to the Moq Framework itself. SymbolSource.org appears to be down, but assuming it was up are you deploying packages as per https://docs.nuget.org/create/creating-and-publishing-a-symbol-package ?

Looking at build.proj it appears you are creating a Symbols package but I don't see the script to Push to NuGet.

**Comment by kzu** [comment]
I'd love a PR that enables this and also does SourceLink: http://ctaggart.github.io/SourceLink/

:)

**Comment by aolszowka** [comment]
Hey @kzu I'd need to know a little bit about your build procedures; where is this being built to be dropped out to NuGet? That is where we'd have to change the process to package the PDB.

**Comment by stakx** [comment]
PR #417 should take care of this once it's finished. The only thing I'm not 100 % sure about is whether the PDB should go into a separate Moq.symbols package or get included in the main Moq package.

**Comment by stakx** [comment]
The next release of Moq (version >4.7.63) will include portable PDBs that are SourceLink-ed to this GitHub repository.
