### ISSUE TITLE
Passing a mock into another mock does not work for me

### ISSUE THREAD

**Issue by Meai1** [moq/moq4#174]
I setup the call, it works fine. 
I pass the mock to another mock and inside that parent mock call the method: doesn't work

**Comment by tparikka** [comment]
@Meai1 Can you provide the code you're using? It's hard to say without being able to see what is actually being done.

**Comment by Meai1** [comment]
no, not anymore

**Comment by kzu** [comment]
Until a repro can be provided, closing
