### ISSUE TITLE
Mocking extension methods

### ISSUE THREAD

**Issue by Hosch250** [Moq/moq4#189]
I am working on an addin for the VBE - [Rubberduck](https://github.com/rubberduck-vba/Rubberduck).  We are working on getting everything under unit tests, but Moq doesn't support extension methods.  Rather than implementing an interface between the VBE and RD just to stick our extension methods in, I figured I would write a patch for Moq that would allow interface methods.  Looking through the project, this is the relevant code:

    private static void ThrowIfNotMember(Expression setup, MethodInfo method)
    {
        if (method.IsStatic)
        {
            throw new NotSupportedException(string.Format(
            CultureInfo.CurrentCulture,
            Resources.SetupOnNonMemberMethod,
            setup.ToStringFixed()));
        }
    }

It is called just twice - in `internal static MethodCallReturn<T, TResult>()` and `internal static MethodCall<T> Setup<T>()`.

I didn't dare touch this code because I don't know what bugs this is preventing.  Could someone who knows explain what I would need to do to fix this?

## Edit:

After a bit of research, I found [the commit it was introduced in](https://github.com/Moq/moq4/commit/21ea597962d90fde0221573ed2ce7860a9cf4d72#diff-8a548f9aae49b8ccb54a1a5cbfb69108).

**Comment by kzu** [comment]
You can't mock extension methods because they are static, and you can't
override a static method call by inheriting its declaring class.
