### ISSUE TITLE
Can I attach an attribute to mocked properties?

### ISSUE THREAD

**Issue by gsscoder** [moq/moq4#190]
Hi there,
thanks for sharing this great project! :+1: 

Given that example:

``` csharp
public interface IEmptyInterface { }
public interface IScalarString { 
  string StringValue { get; set; }
}

mock = new Mock<IEmptyInterface>();
intf = mock.As<IScalarString>();
intf.SetupAllProperties();
var o = mock.Object;
```

I lock to attach an attribute to mocked `IScalarString::StringValue`. Is this possible?

This will be very interesting also when mocking anonymous objects.

P.S.: I'm using Moq from NuGet, version **4.2.1507.0118**.

**Comment by kzu** [comment]
That's a very interesting scenario and potential new feature. Unfortunately this isn't possible right now :(

**Comment by gsscoder** [comment]
@kzu, thank you for saying that!

Since I want to refactor a test project with _non-programmatic_ fake, I'm writing a [small helper](https://github.com/gsscoder/tagger) class.
It's nothing exceptional, something I've done 2-3 hours, but I hope it could inspire a **Moq** enhancement.
(For now it's designed to create mock of classes with property getters/setters and attach attributes to such properties).

For completeness, I want to refactor all this [fake types](https://github.com/gsscoder/commandline/tree/master/src/CommandLine.Tests/Fakes): I'd like to be able to define types using a _fluent dot-syntax_.

**Comment by stakx** [comment]
I love reflection, metaprogramming, and runtime type generation stuff, so your proposition sounds interesting to me. That being said though, I am not sure Moq is quite the right place for this kind of functionality. After all, its main focus is on creating ad-hoc implementations of types having a specified behaviour. Adding or modifying custom attributes doesn't quite match up with that.
