### ISSUE TITLE
SetupAllProperties overrides previous setups of read-only properties

### ISSUE THREAD

**Issue by dcastro** [moq/moq4#196]
**Repro**

``` csharp
public interface Interface
{
    string Property { get; }
}

var a = new Mock<Interface>();

a.Setup(x => x.Property).Returns("test");
a.SetupAllProperties();

Assert.NotNull(a.Object.Property);
```

Passes with Moq 4.2.1409.1722 or lower
Fails with Moq 4.2.1502.911 or greater

**Problem**

It appears that, before Moq 4.2.1502.911, the visible side-effects of `SetupAllProperties` were:
- Stub get-set properties
- Initialize get-set properties with a default value - thus, overriding any previous setups.

Since 4.2.1502.911, SetupAllProperties now does this:
- Stub get-set properties
- Initialize **all** properties with a default value - thus, overriding any previous setups.

**Comment by ploeh** [comment]
Nice repro :+1: 

It seems... unexpected... that `SetupAllProperties()` should affect read-only properties.

**Comment by MichaelLogutov** [comment]
Please, fix this.

**Comment by kzu** [comment]
We'll gladly accept a PR ;)

**Comment by david-banister** [comment]
Is this related to #275?

**Comment by stakx** [comment]
@david-banister: Yes, this is related to #275, in the sense that it has the same underlying cause (as mentioned in #162).

**Comment by stakx** [comment]
I am closing this issue for the time being, for three reasons:

1. The described functional change of Moq happened almost 3 years ago, changing it back only now might break more tests than it fixes. People have probably got used to the new behavior by now.
2. The new behavior does make good sense and fits well with Moq's "the last setup overrides previous setups" rule of thumb.
3. Relatively long thread inactivity.

If someone would like to bring forward other arguments why this should be fixed nevertheless, please do so... we can always reopen this issue.
