### ISSUE TITLE
how to use Moq for ViewModel unit testing

### ISSUE THREAD

**Issue by Meenakshichawla** [Moq/moq4#197]
I am a newBee in Moq. I want to know 
1. How should I unit test ViewModel using Moq?
2. How can I raise an event on setting up property on Mocked object ?

I would be very greatful if you can help me entering in to the world on Moq :).

Thanks & Regards
Meenakshi

**Comment by informatorius** [comment]
see https://github.com/Moq/moq4/wiki/Quickstart

**Comment by kzu** [comment]
Precisely ;)
