### ISSUE TITLE
All Clarius Consulting links broken in README.md

### ISSUE THREAD

**Issue by nrichards** [Moq/moq4#210]
The "Why?" section, and others, of README.md (https://github.com/Moq/moq4/blob/029d510041c95714876bd1e43110af07c24f9aaa/README.md) point to blog articles at Clarius Consulting. None of the links resolve - all generate HTTP 503.

Also, the Internet Archive has nothing from those blogs, due to a robots.txt restriction.

The README set me up to want to read deeper into the issues motivating Moq.

Unless kzu will resurrect the blog / embed the posts in the repository how about the README not linking out to those pages?

**Comment by kzu** [comment]
Fixed

**Comment by nrichards** [comment]
Thank you @kzu ! I can read again. :)

**Comment by kzu** [comment]
thanks for reporting :)
