### ISSUE TITLE
Why is building moq so difficult?

### ISSUE THREAD

**Issue by divmgl** [Moq/moq4#221]
Currently working on a project where team members don't want to rely on NuGet to grab the package. I'm trying to use the `build.cmd` batch file in the master branch, but I've run into two issues (one of which I solved). But frankly, this is frustrating.

Are you guys willing to move away from your build tool so that I may open a pull request and fix this? It's very inconvenient to download the master branch, to then discover we have to grab your `Common` folder from your other repo, and then discover that the master branch is not the correct commit for `Common`, and then still not be able to build because of `-RequiresConsent` flag.

If there is room for this improvement, I can work on this for you and open a pull request. There really needs to be a simpler way to be able to build Moq.

**Comment by kzu** [comment]
You just need to make sure you `git submodule update --init`. Having submodules that you need to init is pretty straightforward and common. 

If you're using TortoiseGit, it's just a checkbox in the checkout.
