### ISSUE TITLE
Events not working with CallBase = true depending on order interfaces are inherited.  C : IA, IB behaves different than C : IB, IA

### ISSUE THREAD

**Issue by seanhalliday** [moq/moq4#228]
public interface IFoo
{
        event EventHandler Foo;
}

public interface IBar
{
        event EventHandler Bar;
}

// reverse the order of IFoo and IBar will change the results of the test
public class FooBar : IFoo, IBar
{
        public event EventHandler Foo;
        public event EventHandler Bar;
        public void RaiseEvents()
        {
               if (Foo != null)
                       Foo(this, EventArgs.Empty);
               if (Bar != null)
                       Bar(this, EventArgs.Empty);
        }
}

[TestClass]
public class MoqTest
{
        [TestMethod]
        public void MultipleInterfacesWithEvents()
        {
               var mock = new Mock&lt;FooBar&gt;() { CallBase = true };
               IFoo foo = mock.Object;
               IBar bar = mock.Object;

               bool fooCalled = false;
               bool barCalled = false;
               foo.Foo += (s, e) => fooCalled = true;
               bar.Bar += (s, e) => barCalled = true;

               mock.Object.RaiseEvents();

               Assert.IsTrue(fooCalled);
               Assert.IsTrue(barCalled);
        }
}

**Comment by seanhalliday** [comment]
Last comment left off less-than and greater-than characters:
should read:
var mock = new Mock&lt;Derived&gt;() {CallBase = true};

**Comment by seanhalliday** [comment]
More info, as this was hard for us to repro with the instructions above, but it turns out that it breaks if Base is defined like:
public class Base : INotifyPropertyChanging, INotifyPropertyChanged
but passes if you reverse the order of the interfaces:
public class Base : INotifyPropertyChanged, INotifyPropertyChanging

**Comment by pjquirk** [comment]
[Possibly related question/analysis on SO](http://stackoverflow.com/a/34319714/1698557).

**Comment by kzu** [comment]
IIRC, if you manually inherit a class with just virtual events but no
method to raise the event, it's impossible to raise it "from the outside".
The best you can do is what Moq does, calling the invocation list manually.
There is no magic in Moq, if you can do it with custom code, we should be
able to do it with Moq.

**Comment by seanhalliday** [comment]
If you read the rest of my comments on the issue, you will see that moq
behaves correctly if we simply reorder the interfaces listed in the
inheritance,so it is definitely a bug in moq.

**Comment by kzu** [comment]
Could you update the issue title and provide a better description then?

Thanks
