### ISSUE TITLE
Idea to avoid ref. comparison warning in functional style

### ISSUE THREAD

**Issue by davidshen84** [moq/moq4#233]
When implementing mock in functional style, like this:

```
var someObj = Mock.Of<SomeType>(o => o.Method() == "string literal")
```

There's a compiler warning regarding to "==", because it thinks I am trying to perform a reference comparison with string, which is usually unwanted.

Other than suppress this warning, any better idea to avoid it?

**Comment by stakx** [comment]
This is surprising. I cannot reproduce such a compiler warning. Can you post a complete short program or unit test (including the `SomeType`) that triggers it? Which compiler are you using? Any special, non-default compiler options?

**Comment by davidshen84** [comment]
I realized it is not the compiler, but the ReShaper syntax checking tool.

**Comment by stakx** [comment]
You should only receive this warning if `SomeType.Method`'s return type is not `string` (my guess is that it returns an `object`).

You can fix this in either of two ways:

1. Fix the problem at the source, namely by changing the return type of `SomeType.Method` to `string`.
2. If (1) is not possible for some reason, add an explicit type cast: `Mock.Of<SomeType>(o => (string)o.Method() == "string literal")`

(Note that outside the context of Moq, you would have a third option, namely substituting `.Equals("some string")` for `== "some string"`. At this time, however, `Mock.Of` does not understand `Equals`.)
