### ISSUE TITLE
Allow setting up "overrides" for `object` members when mocking interfaces

### ISSUE THREAD

**Issue by kolomanschaft** [moq/moq4#248]
Consider the following mock of some interface:

    var mock = new Mock<IMyThing>();
    mock.Setup(s => s.Equals(It.IsAny<object>())).Returns<object>(x =>
    {
        if (typeof(IMyThing).IsAssignableFrom(x.GetType()))
        {
            ...
        }
        return false;
    });

    var myThing = mock.Object;

There is no interceptor created for the `Equals()` method. But since I know every object implementing `IMyThing` will also be an `object` wouldn't it be nice if I was able to do this?

**Comment by kzu** [comment]
An unintended side effect of this feature: https://github.com/moq/moq4/issues/273

:(

**Comment by adityap** [comment]
Does this fix also include GetType() method calls?

**Comment by kolomanschaft** [comment]
`GetType` is not virtual. Therefore it is not possible to mock it. But why would you need this anyway? Have you considered checking types in your code via`Type.IsAssignableFrom(Type)`?

**Comment by adityap** [comment]
I am using .NET Core and was not sure if there is a way to call the method mentioned by you without calling GetType. Ref: http://stackoverflow.com/questions/41646964/asp-net-core-equivalent-of-type-isassignablefrom

However, I do get your point about it being not virtual.
Thanks!
