### ISSUE TITLE
Unable to mock protected generic method

### ISSUE THREAD

**Issue by mattzink** [moq/moq4#249]
It is not possible to currently mock a protected method that has generic type parameters.

`protected virtual TEntity GetEntityByName<TEntity>(string name)`

[Related question on StackOverflow](http://stackoverflow.com/questions/9416291/mocking-a-protected-generic-method-with-moq)

**Comment by Prashantpola** [comment]
Is there any way to mock protected generic method of base class from which is calling from child.
I am calling base method from child class as below
this.ExecuteHttpPutCall<ClassT, ServiceResult<IEnumerable<string>>>(url, request,handler)
