### ISSUE TITLE
How to mock controller with no repository member

### ISSUE THREAD

**Issue by andrewdartford** [moq/moq4#254]
http://stackoverflow.com/questions/36293634/moq-and-teststack-fluent-mvc-for-a-controller-without-repository
I have a number of controllers which use a huge base class in my MVC project which in turn uses a large number of Static methods to configure the CRUD operations around a Unity DI container.  I can get the furthest if I mock the controller itself and then the static methods are easily overridden by virtual wrappers, however how do I return a response?  Cant find a single suggestion that might deal with this....

**Comment by stakx** [comment]
Hi @andrewdartford, are you still interested at all in this issue? If not, I'll close it in about 2 weeks or so.

It's not quite clear to me what you're trying to do. You mention several things (a huge controller, many static properties, being able to deal with all of that, trying to produce a response (an `IActionResult`?), etc.). If you still want to solve this, it would be good to focus on that part of the puzzle that you can't solve, then provide a minimal but complete code example for that.
