### ISSUE TITLE
Stop supporting Silverlight in next version?

### ISSUE THREAD

**Issue by jeremymeng** [moq/moq4#257]
Castle.Core already dropped Silverlight support in v4.0.  If we move to depend on Castle.Core v4 for the .NET Core support, we will have to stop supporting Silverlight as well.

**Comment by kzu** [comment]
Let's kill Silverlight support. I'm all for it :+1:

**Comment by jeremymeng** [comment]
Good.  I am working on it.

**Comment by jeremymeng** [comment]
It's done already.
