### ISSUE TITLE
SetupSequence doesn't support ReturnsAsync

### ISSUE THREAD

**Issue by abatishchev** [moq/moq4#259]
Currently [`ReturnsAsync()`](https://github.com/moq/moq4/blob/master/Source/ReturnsExtensions.cs) is an extension method on `IReturns<TMock, Task<TResult>>` and [`SetupSequence()`](https://github.com/moq/moq4/blob/master/Source/SequenceExtensions.cs) is on `Mock<TMock>`.

Is it something you could add, please?

**Comment by abatishchev** [comment]
Bump.

**Comment by kzu** [comment]
PR?

**Comment by abatishchev** [comment]
Sorry, closes in error, maybe pressed wrong button.
If you'll accept a PR, I'll submit one soon.

**Comment by abatishchev** [comment]
I struggle to get it working. Can you please take a look too? The problem is that context is generic on either `TResult` or `Task<TResult>` and I'm unable to kind combine these two.

**Comment by Jacob-McKay** [comment]
This is what I did to get around the issue:
`mock.SetupSequence(m => m.method(
                    It.IsAny<whatever>()
))
                .Returns(Task.FromResult<ISomething>(new Something
                {
                    Successful = false
                }))
                .Returns(Task.FromResult<ISomething>(new Something 
                {
                    Successful = true
                }));`

**Comment by abatishchev** [comment]
Yes, `Returns(Task.FromResult<T>)` is a working workaround but if you have it more than few it become ugly.

**Comment by abatishchev** [comment]
See https://github.com/moq/moq4/pull/261
