### ISSUE TITLE
"Error binding to target method"

### ISSUE THREAD

**Issue by hiredgunhouse** [moq/moq4#26]
See the issue reported here: https://code.google.com/p/moq/issues/detail?id=349
BTW. Why there's no mention on the Google Project site that Moq has new source code repo?

**Comment by tparikka** [comment]
@hiredgunhouse Does this issue still occur in Moq 4.7.9? If so, can you provide steps/code to reproduce? The link http://issues.castleproject.org/issue/DYNPROXY-147 at the Google Code project location is broken so it's not possible to see what it originally referenced.

**Comment by stakx** [comment]
It's not pretty, but I suppose the following document might contain the same information:
https://github.com/castleproject/castle-youtrack-export/blob/master/DYNPROXY/DYNPROXY-147.xml
