### ISSUE TITLE
Small grammar correction in documentation

### ISSUE THREAD

**Issue by jack038** [moq/moq4#260]
I noticed a few sentences like this in the documentation:

> Specifies a setup on the mocked type for a call **to to** a void method.

They are [here](https://github.com/Moq/moq4/blob/master/Source/Mock.Generic.xdoc#L122), [here](https://github.com/Moq/moq4/blob/master/Source/Mock.Generic.xdoc#L139), [here](https://github.com/Moq/moq4/blob/master/Source/Mock.Generic.xdoc#L156), [here](https://github.com/Moq/moq4/blob/master/Source/Mock.Generic.xdoc#L174) and [here](https://github.com/Moq/moq4/blob/master/Source/Mock.Generic.xdoc#L195).

**Comment by abatishchev** [comment]
Submit a PR?

**Comment by kzu** [comment]
I wish that was as simple for wikis as it is for code :(. AFAIK it's not
obvious
