### ISSUE TITLE
Odd behavior in regex matcher with nulls

### ISSUE THREAD

**Issue by sign42** [moq/moq4#266]
Ran into an issue using the regex matcher. The following test passes I was expecting that the matcher would not match the null, but not that an exception would be thrown.

```csharp
[Fact]
public void RegexHandlesNull()
{
    var mock = new Mock<IFoo>();
    mock.Setup(x => x.Execute(It.IsRegex(".*"))).Returns("something");
    Assert.Throws<ArgumentNullException>(() => mock.Object.Execute(null));
}
```

**Comment by stakx** [comment]
`null` will not match `It.IsRegex(…)` at all (regardless of the regex string), so your setup simply doesn't come into effect. If you had an additional setup for `null`:

```csharp
mock.Setup(x => x.Execute(null)).Returns("not matched");
mock.Setup(x => x.Execute(It.IsRegex(".*"))).Returns("matched");
```

Then you'd get what you expected.

Does this answer your question?

**Comment by sign42** [comment]
I knew how to get it to do what I wanted. It's more that it wasn't matching my expectations. If I'm the only one with those expectations don't worry about it.

**Comment by stakx** [comment]
@sign42: I believe I initially misunderstood your report. Sorry for that. An exception being thrown indeed feels somewhat unintuitive. I would also expect `null` to simply not match the `It.IsRegex`, and therefore nothing at all should happen.

**Comment by stakx** [comment]
This is taken care of in Moq 4.7.63.
