### ISSUE TITLE
Gitter badge points to non-existing room

### ISSUE THREAD

**Issue by tiesmaster** [moq/moq4#268]
When I click the gitter badge icon, I get here:

![image](https://cloud.githubusercontent.com/assets/460904/15926275/6dc5970c-2e3b-11e6-9958-cdd6224c637a.png)

Searching in gitter also didn't show anything, do you guys still have a room?

**Comment by kzu** [comment]
I get here:

**Comment by kzu** [comment]
(empty room , but existing)

**Comment by tiesmaster** [comment]
Maybe I'm mistaken, but it says "0 Rooms", and there is nothing to be joined... And when you're not a member, you're also not able to create rooms, so does the gitter badge add any value?

I don't really mind, and this is not intended as rant. I just wanted to ask a question, and when I see a gitter badge, it's usually the easiest way to approach a project (especially if it's something small, and doesn't really deserve an issue). Since, other people might have stumbled upon that as well, and it's also not possible to create a room, maybe, it might be useful to just remove the badge, isn't it?

OT: If you're wondering what my small question was: I was looking for the status on .NET Core support (which is finally there, big kudos for all the hard work!!), and I noticed the "Added support for Roslyn" in the release notes for Moq 4.3. And I was wondering what that exactly meant for Moq. I looked in the issue, and PR list, and didn't find anything related to Roslyn, so I was just curious. If you could elaborate on that, I'd greatly appreciate that ;)

**Comment by kzu** [comment]
That's actually very weird. I'm in that very Room right now :/

**Comment by stakx** [comment]
@tiesmaster, I don't know for certain, but I suspect that the "Added support for Roslyn" note referred to something fairly minor; either to a Roslyn bug regarding XML documentation comments (see b63b6e35368), or to the way how the Roslyn compilers choose method overloads or invoke delegates (there's a note about this in the source code, but I can't find it right now).

FWIW, I'd like to add my vote to abandoning Gitter. There's not much sense in letting people walk into a dead end, if we have that place we should also be present there.

**Comment by tiesmaster** [comment]
Ey, first of all, Happy New Years!

That's a blast from the past 😛  Thanks for digging that commit up, TBH that's not really adding support for Roslyn, but can imagine it's tempting to put something like that in the release notes.

Anyhow, shall I put in a PR to drop the badge?

**Comment by stakx** [comment]
@tiesmaster: Some code archeology every now and then can be fun, right? :)

> shall I put in a PR to drop the badge?

Perhaps it's a little bit too soon. I suggest we wait until Moq 5 is out. If there won't be a Gitter badge on the v5 readme, we can remove it for v4, too (for consistency, if nothing else). However, if there is going to be a Gitter badge with v5 then it would be bad timing to (intermittently) remove it now. In other words, I feel that this is ultimately @kzu's decision to make.
