### ISSUE TITLE
IsAssignableFrom breaks __ComObject support

### ISSUE THREAD

**Issue by bob-fisher** [moq/moq4#269]
trying to setup setter for a property of ISymbol type, which is COM interface:
ISymbol setSymbol = null;
elMock.SetupGet(e => e.Symbol).Returns(setSymbol);
elMock.SetupSet(e => e.Symbol = It.IsAny<ISymbol>()).Callback<ISymbol>(s => setSymbol = s);

set it during a test:
el.Symbol = (ISymbol)Com.CreateInstance<SimpleFillSymbolClass>();

this never works, setSymbol stays null, Symbol property also always returns null

**Comment by stakx** [comment]
Let's start with the getter:

> Symbol property also always returns null

That's because you configured it to return `null`. At the moment when `.Returns(setSymbol)` executes, `setSymbol` is `null`, therefore that call is equivalent to `.Returns(null)`. Did you perhaps mean:

```csharp
elMock.SetupGet(e => e.Symbol).Returns(() => setSymbol);  // deferred evaluation using lambda
```

**Comment by stakx** [comment]
Regarding the setter, there seems to be a problem, indeed. `It.IsAny<T>` won't recognize an instance of `T` is that is a COM object.

You mentioned `IsAssignableFrom` in this issue's title. I'm assuming you're referring to the one inside `It.IsAny<T>()`:

```csharp
public static TValue IsAny<TValue>()
{
    return Match<TValue>.Create(
        value => value == null || typeof(TValue).IsAssignableFrom(value.GetType()),
        () => It.IsAny<TValue>());
}
```

`typeof(TValue).IsAssignableFrom(value.GetType())` might indeed not work for a COM object. I wonder why this isn't simply `value is TValue`...?
