### ISSUE TITLE
ref mock does not work as you described in your document

### ISSUE THREAD

**Issue by HardySoftware** [moq/moq4#270]
[MoqRefTest.zip](https://github.com/moq/moq4/files/332076/MoqRefTest.zip)

Please see the attached file with latest version of Moq, I don't see Moq can mock the ref value at all.

**Comment by stakx** [comment]
The unit test contained in your solution does not have any verification or assertion logic whatsoever, and it passes, so I will close this issue.

If I understand your code correctly, you are creating a mock `ISomething` instance and setting up its `DoSomething` method to return true if it is given the specific `Person` instance from the unit test. Then you are exercising this mock via `Class1`. Class 1, however, passes a null reference to your `ISomething`, not the person object from the unit test. And therefore your setup for `DoSomething` does not come into effect and the method call returns false.
