### ISSUE TITLE
Verify passes on strict mock for parameter without proper setup.

### ISSUE THREAD

**Issue by azaroth001** [moq/moq4#285]
Normally it would fail on MockException, but if that is caught, Verify will pass.
See following code:

``` c#
[TestClass]
public class StrictVerify
{
    [TestMethod]
    public void Test()
    {
        var mock = new Mock<IToMock>(MockBehavior.Strict);
        mock.Setup(m => m.Action("mistake"));
        var sut = new Sut();
        sut.DoSomething(mock.Object, "action"); // won't throw MockException due to catch inside.
        mock.Verify(m => m.Action("action"), Times.Once()); //passes
    }
}

public interface IToMock
{
    void Action(string param);
}

public class Sut
{
    public void DoSomething(IToMock obj, string param)
    {
        try
        {
            obj.Action(param);
        }
        catch(Exception)
        {
            //handle exception without rethrow.
        }
    }
}
```

I would expect Verify to respect MockBehavior.Strict and fail in this case, because even though invocation was performed once, it was prohibited by mock and should not count as correct one.

**Comment by kzu** [comment]
Swallowing all exceptions is hardly a good practice. Your code should only handle what it can recover from. It's unlikely it can recover from anything, like a ThreadAbort, OutOfMemory or the like. Likewise, it shouldn't be able to recover from a MockExcepcion

**Comment by stakx** [comment]
(Closing this issue, since there's really nothing that can nor should be done about this.)
