### ISSUE TITLE
Invalid type for a default value exception (regression)

### ISSUE THREAD

**Issue by shadowfaxer** [moq/moq4#286]
The attached example code gives an exception
`Unhandled Exception: System.FormatException: Encountered an invalid type for a default value.`
when run using version `4.5.21`.  It runs without error using version `4.2.1510.2205`

```
using System;
using Moq;

namespace MoqProblem
{
    public interface ITestMoq
    {
        void WithDefaults(DateTime dateTime = default(DateTime));
    }

    class Program
    {
        static void Main(string[] args)
        {
            var test = new Mock<ITestMoq>();
            var t = test.Object;
        }
    }
}
```

**Comment by stakx** [comment]
Hi, this is no longer reproducible in the latest version of Moq (4.7.25). Please update your package reference.
