### ISSUE TITLE
Moq Docs

### ISSUE THREAD

**Issue by CeeSharper** [moq/moq4#290]
The service that was hosting your API documentation (nudoq.org) failed to renew their domain name. Any chance you've got them in some permanent format?

**Comment by gandarez** [comment]
+1

**Comment by stakx** [comment]
Is this still an issue? http://www.nudoq.org appears to be online and its usual self.

**Comment by stakx** [comment]
While http://www.nudoq.org/#!/Projects/Moq is online now, it doesn't appear to have the latest documentation for Moq. It's stuck at version 4.2.1312.1622, we're at 4.7.x now. It appears as if NuDoq hasn't been updated since approx. Feb 2014.
