### ISSUE TITLE
Missing .ThrowsAsync() extension for Task-returning methods

### ISSUE THREAD

**Issue by gzak** [moq/moq4#294]
Currently, there's only a ThrowsAsync extension for methods which return Task<T>, but there's no equivalent for methods which return the non-generic Task type (a "void" Task, essentially).

The same is true for ReturnsAsync, though it's questionable how useful it would be.

**Comment by neraath** [comment]
+1

**Comment by stakx** [comment]
I've prepared an implementation `ThrowsAsync` for non-generic `Task`s, which I'll be PR-ing in the next few days, but I'm omitting `ReturnsAsync` for now. I can't see any practical use for it.
