### ISSUE TITLE
Nested asynchronous functions are not executed

### ISSUE THREAD

**Issue by tahirahmed76** [moq/moq4#300]
While mocking an object that have a synchronous method which internally executes an asynchronous method is not returning correct results. Eventhough, the setup was configured correctly, it didn't execute the nested asynchronous methods that returns a Task. Following is my object to mock.

```csharp
public class ServiceClient
{
    private readonly Uri baseUri;

    public ServiceClient(string baseUri)
    {
        this.baseUri = new Uri(baseUri);
    }

    public void Process()
    {
        Console.WriteLine("Process has been started");

        DoSomething();

        // this is not working as well..
        // DoSomething().Wait();

        Console.WriteLine("Process has been completed");
    }

    public virtual Task DoSomething()
    {
        Console.WriteLine("DoSomething has been started");
        return DoSomethingMore();
    }

    public virtual Task DoSomethingMore()
    {
        Console.WriteLine("DoSomethingMore has been started");
        return Task.CompletedTask;
    }
}
```

And following is my unit test.

```csharp
public void TestMethod1()
{
    var client = new Mock<MoqTesting.ServiceClient>(@''http://localhost:9000/service'');
    client.Setup(s => s.DoSomethingMore()).Returns(Task.CompletedTask);
    client.Object.Process();
    client.Verify(f => f.DoSomethingMore(), Times.Once);
}
```

This test fails and verify confirms that DoSomethingMore() method was never executed.
Complete source code is also attached to easily reproduce the issue.
[MoqTesting.zip](https://github.com/moq/moq4/files/605781/MoqTesting.zip)

**Comment by stakx** [comment]
The problem here is that Moq also mocks the `DoSomething` method. Because you haven't provided a setup for `DoSomething`, it will just return the default empty value for `Task`, which is a completed task. Your logic in `DoSomething` will never run.

You can get Moq to call your logic in `DoSomething` by setting `client.CallBase` to `true`:

```csharp
var client = new Mock<ServiceClient>(…) { CallBase = true };
//                                      ^^^^^^^^^^^^^^^^^^^
```
