### ISSUE TITLE
Mocking "FindBy" with Generic Repository C# .Net

### ISSUE THREAD

**Issue by marioguadanhim** [moq/moq4#301]
Hi guys,

Recently I started to test my solution with mocks and i got the following issue.
I'm using the "Repository" parttern, but i can not create a mock to it.
Example:

private IRepository<MyClass> myClassRepository;

public void Test()
{
     List<MyClass> arrMyClass = LoadArrayMyClassWithObjects();

     myClass = new Moq <IRepository<MyClass>>();

    myClass.Setup(x => x.findby(myclass => myclass.id ==1 ).ToList() ).Return(arrMyClass); 

}

What is the correct code to write the method above? In my test, it's returning a null error.

Thanks.

**Comment by kzu** [comment]
Delete .ToList()
