### ISSUE TITLE
Nuget Package Moq 4.5.28 could not be installed on MonoAndroid=v7.0

### ISSUE THREAD

**Issue by mcelik84** [moq/moq4#308]
Hi kzu, i'm having problems installing Moq on Xamarin (Mac, v6.1.2 Build 44).
Can yo help me out?

Could not install package 'Moq 4.5.28'. You are trying to install this package into a project that targets 'MonoAndroid,Version=v7.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by stakx** [comment]
The version of Moq you were trying to use only had support for the full .NET Framework, I believe.

Have you tried Moq version 4.7 or later (which also targets .NET Standard)? I can't test this myself at the moment, but I'd expect that Xamarin has .NET Standard support.

Does this resolve your issue?

**Comment by skarllot** [comment]
Confirmed, it works on Android.

**Comment by stakx** [comment]
Glad to hear you got this working. ;)
