### ISSUE TITLE
Error message when attempting to mock an extension method

### ISSUE THREAD

**Issue by gregsdennis** [moq/moq4#317]
I ran into an issue when I was (unwittingly) attempting to mock an extension method.  I've seen #189, and I understand why I can't do that.  Still, I think the error messaging could be better.

I have an interface:

    public interface ILogger
    {
        void Error(string);
    }

and an extension method:

    public void Error(this ILogger logger, Exception e)
    {
        ...
    }

and a test

    [TestMethod]
    public void TestIt()
    {
		var logger = new Mock<ILogger>();
		logger.Verify(l => l.Error(It.IsAny<Exception>()));
    }

As expected, the test fails.  But *why* the test fails is confusing. The following error is returned:

>Invalid verify on a non-virtual (overridable in VB) member: l => l.Error(It.IsAny<Exception>())

The error says nothing about how `Error(Exception)` isn't even a member of `ILogger`.

**Comment by aKabirKhan** [comment]
What did you end up doing to mock extension methods. I need to mock app.UseMvc(); method in Configure method of the start up class but I cannot do so.

**Comment by gregsdennis** [comment]
I verified what the extension method did, which was to call a different method on the logger.

**Comment by stakx** [comment]
This will be fixed in the next release of Moq. The exception message will read:

    Invalid verify on an extension method: l => l.Error(It.IsAny())

**Comment by darraghjones** [comment]
This is likely down to our AWS machines being under resourced. We're upgrading these to m4.large in the next prod release. I've also added max-queue-lenght of 100 to these queues.

There's another issue around how we process parameter updates for bookmakers not in control.

**Comment by stakx** [comment]
@darraghjones: Was that post supposed to go to a different repo/issue?

**Comment by darraghjones** [comment]
Sorry, my bad!
