### ISSUE TITLE
Setup before instantiation of the mock instance

### ISSUE THREAD

**Issue by Kralizek** [moq/moq4#329]
Hi,
Is there a way to setup a mock before instantiating an instance?

The case is the following.

I have [this abstract class](https://github.com/Kralizek/AWSLambdaSharpTemplate/blob/master/src/Kralizek.Lambda.Template/Function.cs) with several virtual methods that are called in the constructor.

I was trying to create a test mock but `new Mock<T>` instantiates the class and therefore the constructor is already invoked.

Ideally, I would like to be able to setup the overrides before creating the instance.

Thanks.

**Comment by kzu** [comment]
There's a reason why that is a code analysis violation: https://msdn.microsoft.com/en-us/library/ms182331.aspx

**Comment by Kralizek** [comment]
I agree with you, but in AWS Lambda the constructor has a specific semantic.

**Comment by stakx** [comment]
> Is there a way to setup a mock before instantiating an instance?

Yes.

> I was trying to create a test mock but `new Mock<T>` instantiates the class and therefore the constructor is already invoked.

That is not correct. Instantiation will only be triggered by the first query of `mock.Object`. If you perform your setups before that, they should take effect even during your type's constructor:

```csharp
public class SomeClass
{
    public SomeClass()
    {
        Console.WriteLine("Constructor called.");
        Console.WriteLine(Foo());
    }

    public abstract int Foo();
}

var mock = new Mock<SomeClass>();
mock.Setup(someClass => someClass.Foo()).Returns(42);
var _ = mock.Object;  // <-- this triggers instantiation
```

I would agree with kzu however that calling virtual methods from the constructor is probably not an ideal design.

**Comment by Kralizek** [comment]
Thanks @stakx, I will double check how I structured my tests :)
