### ISSUE TITLE
Moq functionality broke after update to 4.7.1

### ISSUE THREAD

**Issue by jatouma** [moq/moq4#331]
After updating from 4.2.1402.2112 to 4.7.1, a lot of our unit tests started failing because of the following functionality change. 

```
using System.Diagnostics;
using Moq;

namespace FooApplication
{
    public interface IFoo
    {
        bool fooBool { get; set; }
    }

    public class Foo : IFoo
    {
        public bool fooBool { get; set; }
    }
   class Program
    {
        static void Main(string[] args)
        {
            var mock = new Mock<Foo>();
            IFoo i = mock.Object;
            i.fooBool = true;
            if(!i.fooBool)
                Debug.Assert(false, "Moq changed functionality");
        }
    }
}
```

**Comment by Shazwazza** [comment]
Yup we have the same problem. I know this seems odd but when you have shadowed properties on interfaces like:

```
public interface ITemplate : IFile
 {       
        new string Name { get; set; }
        new string Alias { get; set; }
}
```

it doesn't work, these properties will not be mocked and return null.

**Comment by stakx** [comment]
Related: #162 and #212.

**Comment by stakx** [comment]
Regarding the repro code at the top, there must have been a change between Moq versions 4.2.1402.2112 and 4.2.1408.619 (which is the first version that triggers the assertion error).

**Comment by stakx** [comment]
@Shazwazza, could you please post a short but complete repro code? I'll try to see if your report is related to @jatouma's.

**Comment by Shazwazza** [comment]
Hi sorry for the delay, I assume you no longer need the repro code since it's resolved? I think it's really just a case of the  shadowed properties on interfaces. If you still need repro code I'll go have a look - I'll just need to remember which codebase this was in ;)

**Comment by stakx** [comment]
I am fairly certain that your reported issue would now be fixed, so I'll leave it up to you. ;)
