### ISSUE TITLE
Documentation Correction around using Verify()

### ISSUE THREAD

**Issue by jcockhren** [moq/moq4#332]
Hello, I'm an instructor at the [Nashville Software School](http://nashvillesoftwareschool.com/) and my students and I are using Moq for testing. While working through an in-class example, we noticed what seemed to be a typo in the [documentation describing how to use Verify()](http://www.nudoq.org/#!/Packages/Moq/Moq/Mock/M/Verify). When applying the instructions, intelli-sense complains and compilation fails. Considering the example from the docs:

```c#
var mock = new Mock<IWarehouse>();
this.Setup(x => x.HasInventory(TALISKER, 50)).Verifiable().Returns(true);
```

According to the interface `IVerifies` [and documention](http://www.nudoq.org/#!/Packages/Moq/Moq/IVerifies/M/Verifiable), Verifiable() [return type is `void`](https://github.com/moq/moq4/blob/756bf4e3e7b213c6d819ae7acd5e04280a07a040/Source/Language/IVerifies.cs#L64) and therefore calling `.Returns(true)` on a void causes compilation to fail and Intelli-sense yells: `Operator '.' cannot be applied to operand of type void`.

**Comment by jessicakilby** [comment]
Thanks for showing us! :+1:

**Comment by tkylesh** [comment]
:+1:

**Comment by stakx** [comment]
Thanks! Please note that at the moment, this correction won't be seen [on NuDoq](http://www.nudoq.org/#!/Projects/Moq), since NuDoq doesn't have the documentation for the latest version of Moq. I'll try to follow up on this in #354.
