### ISSUE TITLE
Protected<T>.Setup fails on specific overloads

### ISSUE THREAD

**Issue by 80er** [moq/moq4#341]
Hi,

was it by intention that the  commit c8c5db1 broke identification of some overloads? 

Up to that one it was possible to have overloads with a base and a derived class. Now the IsAssignableFrom leads to InvalidOperationException in SingleOrDefault as now more then one method is found. 

The previous implementation with Type.GetMethod also went  for strict parameter type matching.

**Comment by stakx** [comment]
Closing this issue, since the PR has been merged. The additional overload is available starting with Moq version 4.7.25.
