### ISSUE TITLE
Open Generic Method Callback

### ISSUE THREAD

**Issue by michal-ciechan** [moq/moq4#343]
I can't find any way to mock an open Generic Method without specifying to type beforehand.

I have a couple questions, that someone might be able to help with:

1. Is this already implemented but I'm not finding it?
2. Is this possible (is has someone tried this but come up against a blocker)
3. Is this something that would be merged?
4. Some pointers of what classes I should look init. (To help speed up understanding the code, but will be going through it tomorrow anyhow)

Thinking something like

```csharp
Mock.Setup(x => x.GenericMethod<It.AnyType>())
    .Returns(context => *return type here*)
```

Where `context` will contain:

* Method Generic Type Args
* Passed in Parameters

The reason I would like to do this, is so so I can register hooks for my library 'Moqqer'.

**Comment by kzu** [comment]
> GenericMethod<It.AnyType>

If you find a way to make that compile, I'll merge that ;)

**Comment by michal-ciechan** [comment]
@kzu 
[Pull Request - Issue #343 - Allow Mocking of Open Generic Method](https://github.com/moq/moq4/pull/346) ;-)

**Comment by stakx** [comment]
Closing this dormant issue, but marking it as "unresolved" so it can be easily found again. Please see #642 for details. If you'd like to pick this up and work on it, please post here briefly and we'll see what we can do!

**Comment by stakx** [comment]
Reopening this in the hope that we can include this feature in [version 4.11.0](https://github.com/moq/moq4/milestone/8).

**Comment by oddbear** [comment]
Nice.
This should work in general, but I don't see that it can work in case of ['Constraints on type parameters'](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/generics/constraints-on-type-parameters).
I can think of a couple of workarounds, but those would be more like hacks.

Any ideas?

**Comment by stakx** [comment]
@oddbear - I'm not sure I understand. Could you please elaborate a little? What about generic type parameter constraints? (Yes, an `It.IsAnyType` wouldn't take those into account. What is stopping us from something like `It.IsAnySubtypeOf<T, U, V, ...>`?)

**Comment by oddbear** [comment]
It's kind of an edge case, but I thinking about something like mocking this method:
```csharp
void MockThisMethod<T, U>()
    where T : ITest<U> //This is one of the rules allowed in C#
{
    //
}

public interface ITest<U>
{
    //
}
```

Then IsAnySubtype must be implementing that interface, and since it is not allowed to do:
```csharp
//Can't see that anything like this coult be possible:
Mock.Setup(x => x.MockThisMethod<It.IsAnySubtypeOf<T, ITest<U>>, U>())
    .Returns(context => *return type here*)

//Since, this is not allowed, won't compile
public class IsAnySubtype<T, U> : U //Cannot derive from 'U' because it is a type parameter
{
    //
}
```
Then I can't see any way Moq could provide any type that would compile.

One workaround would be if the user them self make a custom type, and then add some attribute or similar to tell Moq, that this type is a replacement/workaround.

**Comment by stakx** [comment]
Like you said yourself, that may be an edge case. No need to build something complicated if noone's going to need it. I'd say let's start with `It.IsAnyType` (which is going to be an improvement over nothing) and only worry about the super-involved edge cases when someone actually runs into them.

**Comment by oddbear** [comment]
Agreed

**Comment by michal-ciechan** [comment]
I was originally planning also provide an IAnyType interface which would allow you to attach it to any custom type that implements the genetic constraint

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by michal-ciechan** [comment]
@stakx  I will take a look at it today + next week.

**Comment by jchesshir** [comment]
I would love to see this one make it to release!

**Comment by stakx** [comment]
It's been a while, and I might be missing the obvious, but I am no longer sure I understand why we need this feature in the first place. Moq already matches generic type arguments by assignment compatibility (as opposed to precise equality). That is, you can already do this:

```csharp
public class Fruit { }
public class Apple : Fruit { }
public class GreenApple : Apple { }
public class Orange : Fruit { }

public interface IFruitConsumer
{
    void Consume<TFruit>() where TFruit : Fruit;
}

var mock = new Mock<IFruitConsumer>();
mock.Setup(m => m.Consume<Fruit>()).Callback(() => Console.WriteLine("fruit"));
mock.Setup(m => m.Consume<Apple>()).Callback(() => Console.WriteLine("apple"));
mock.Setup(m => m.Consume<Orange>()).Callback(() => Console.WriteLine("orange"));

mock.Object.Consume<Fruit>();         // prints "fruit"
mock.Object.Consume<Apple>();         // prints "apple"
mock.Object.Consume<GreenApple>();    // prints "apple"
mock.Object.Consume<Orange>();        // prints "orange"
```

How is that different than if you had specified `It.IsAnyType` or `It.IsAnySubTypeOf<Fruit>`? (The only difference, as far as I can see, is that the callback won't receive a context object which it can inspect to figure out the generic type arguments. But there are easier ways to allow accessing those than introducing generic type argument matcher infrastructure.)

What precise use case were we trying to solve here?

**Comment by oddbear** [comment]
Could it be scenarios with a return?

With your example then, only one of the Apples prints.
```csharp
void Main()
{

	var mock = new Mock<IFruitConsumer>();
	mock.Setup(m => m.Consume<Fruit>()).Callback(() => Console.WriteLine("fruit"));
	mock.Setup(m => m.Consume<Apple>()).Callback(() => Console.WriteLine("apple"));
	mock.Setup(m => m.Consume<Orange>()).Callback(() => Console.WriteLine("orange"));

	mock.Object.Consume<Fruit>();         // prints "fruit"
	mock.Object.Consume<Apple>();         // prints "apple"
	mock.Object.Consume<GreenApple>();    // prints nothing
	mock.Object.Consume<Orange>();        // prints "orange"
}

public class Fruit { }
public class Apple : Fruit { }
public class GreenApple : Apple { }
public class Orange : Fruit { }

public interface IFruitConsumer
{
	//void Consume<TFruit>() where TFruit : Fruit;
	
	TFruit Consume<TFruit>() where TFruit : Fruit;
}
```

**Comment by stakx** [comment]
@oddbear - That's baffling, thanks for posting this. I'll look into it.

**Comment by michal-ciechan** [comment]
My reasoning was because I wanted to mock the generic variant including generic parameters without knowing the generic types upfront. It is for a helper library ([Moqqer](https://github.com/michal-ciechan/Moqqer)) I created which sets up mock methods recursively with opinionated defaults.

So yes as you mentioned, the point is to inspect what Generic Types/Arguments the method was called with, and return something based on the types passed in.

Something along the lines of:

```

[Fact]
public void SetupReturns_OpenGenericReturnArgument_And_Param()
{
    // Arrange
    var mock = new Mock<IHasOpenGeneric>();

    var callCount = 0;
    ICallContext callContext = null;

    mock.Setup(x => x.Get<It.AnyType, It.AnyType, It.AnyType>(It.IsAny<It.AnyType>()))
        .Returns(context =>
        {
            callContext = context;
            callCount++;
            return "Test";
        });

    Assert.Equal(0, callCount);

    // Act
    var res = mock.Object.Get<int, decimal, string>(2);

    // Assert
    Assert.Equal(1, callCount);

    Assert.Equal(res, "Test");

    Assert.NotNull(callContext);
    Assert.Equal(1, callContext.Arguments.Length);

    Assert.NotNull(callContext.Arguments[0]);
    Assert.Equal(typeof(int), callContext.Arguments[0].GetType());
    Assert.Equal(2, (int) callContext.Arguments[0]);
    Assert.Equal(typeof(string), callContext.Method.ReturnType);
}
```

**Comment by stakx** [comment]
Ah, another test case just came in that would also seem to profit from `It.IsAnyType`: #790.
