### ISSUE TITLE
new Mock<T> can generate not unique names

### ISSUE THREAD

**Issue by 80er** [moq/moq4#348]
When submitting a pull request this test failed in the first try:

https://github.com/moq/moq4/blob/master/UnitTests/MockFixture.cs#L38

After checking the code two times the same name for a mock was generated but that should be unique. Problem is this line:

https://github.com/moq/moq4/blob/master/Source/Mock.Generic.cs#L126

Although it is (more or less) guaranteed that the whole guid is unique this does not hold true for the first 4 characters. This can lead to Heisenbugs while executing tests i think. However. Not sure how much functionality is depending on having unique names for Mocks currently.

**Comment by stakx** [comment]
Done in `develop`. This will be solved with the next merge into `master` / in the next NuGet release.
