### ISSUE TITLE
Set Times expectation on Setup

### ISSUE THREAD

**Issue by skarllot** [moq/moq4#373]
Would be nice if I can set times expectation on Setup instead of separated Verify. e.g.:

```csharp
mockInstance
    .Setup(a => a.Start(It.IsInRange(0, 1000)))
    .Count(Times.AtLeast(5))
    .Returns(Task.FromResult(true));
```

**Comment by tparikka** [comment]
+1

**Comment by stakx** [comment]
Being able to specify `Times` on a setup sounds like a handy feature. Contrary to that, two extant setup methods `.AtMostOnce()` and `.AtMost(n)` that are related in purpose were both deprecated and hidden from IntelliSense years ago. This old [Google Code issue 216](https://code.google.com/archive/p/moq/issues/216) states why:

> These were hidden as we're encouraging people to manage the former occurrence constraints via explicit Verify assertions, which aligns better with AAA style testing.

I'm not against this feature, but I'm digging up this bit of history so we won't end up swinging back and forth between two opposing design decisions.

@kzu: What is your position on the ability to specify `Times` during setup? Do you still consider this a feature that should belong in `Verify` exclusively?

**Comment by IanYates83** [comment]
While I completely agree with the AAA comment, the reason I submitted #401 is to cover scenarios like my `CannotPostVerifyCallsByExpressionForModifiedReferenceTypeArgument` test, where the post-Act `Verify` cannot be used to check the invocation argument values.

I did play around with having a `Verify` directly on `IFluentInterface`, which gives a better AAA approach, but it felt like a larger change and less elegant when you have many setups.

Example:
```
var setup1 = mock.Setup(m => m.Call1(It.Is<MyClass>(c => c.Name == "test"))).Returns("result");

Act();

setup1.Verify(Times.Exactly(2));
```

I realise that this is slightly an edge-case issue.
We currently solve it through argument capture and comparison, which is very inelegant.

**Comment by stakx** [comment]
@IanYates83 - that makes sense, I've come across one other issue where someone had the same problem with reference type state changing and not being verifiable after the fact. I'm generally in favour of your proposed changes. Like I already [commented on your PR](https://github.com/moq/moq4/pull/401#pullrequestreview-47930518)

* Can you perhaps add your thoughts on why you chose to add a `Times` on the `.Verifiable()` method? Did you consider any alternatives (extending the `IOccurrence` interface; extending `.Setup()`; adding a new method such as `.Count()` as proposed by @skarllot; etc.)?

* I would prefer to leave the final decision up to @kzu: Is adding `Times` back to the setup (Arrange) stage OK? We appear to have one use case that the `.Verify` (Assert) stage can't handle easily.

**Comment by IanYates83** [comment]
@stakx Responding to your comments here but will action your request on the other PR.

* When we hit the issue, it was the natural change that came from our internal discussions. I couldn't see the existing functionality (the current `IOccurence` isn't precise enough), so I thought I'd suggest it using the syntax we felt was naturally missing. (You mark the Setup as verifiable, so why can't we control that count assertion at the same time?)
I also liked the fact that it was a very light change that didn't affect existing functionality.
If the old decision is reversed, maybe extending `IOccurence` is the answer, or a new `.ExpectedCalls(Times)` method on `IVerifies` (`Count` is a bit vague, to me).

* Fine by me :)
