### ISSUE TITLE
Upgrade to Castle.Core 4.1.0

### ISSUE THREAD

**Issue by natemcmaster** [moq/moq4#375]
Coming soon: the launch of .NET Core 2.0 adds NuGet improvements which includes warnings about misconfigured packages. Castle.Core 4.0.0 had a such an issue (see https://github.com/castleproject/Core/issues/239) that is resolved in 4.1.0. Until Moq upgrades, .NET Core 2.0 projects will see this warning during restore when the reference Moq 4.7.25.

> warning NU1603: Castle.Core 4.0.0 depends on System.ComponentModel.TypeConverter (>= 4.0.1) but System.ComponentModel.TypeConverter 4.0.1 was not found. An approximate best match of System.ComponentModel.TypeConverter 4.1.0 was resolved.

**Comment by stakx** [comment]
Hi @natemcmaster, the update to Castle Core 4.1.0 has already happened on the `develop` branch (see commit e67faa9fddc85037e91e96c36f96ba7000e77dfd), so it will be in the next NuGet release (version >4.7.25) of Moq.

**Comment by natemcmaster** [comment]
Awesome sauce. 👏
