### ISSUE TITLE
Exception after upgrade of Catle.Core to 4.1.0

### ISSUE THREAD

**Issue by tmm360** [moq/moq4#377]
In my project I use Castle.Core, and after to have updated dependency to 4.1.0, I receive this exception from Moq in my tests (italian message):

	Message: System.TypeInitializationException : L'inizializzatore di tipo di 'Moq.Mock`1' ha generato un'eccezione.
	---- System.TypeInitializationException : L'inizializzatore di tipo di 'Moq.Proxy.CastleProxyFactory' ha generato un'eccezione.
	-------- System.IO.FileLoadException : Non è stato possibile caricare il file o l'assembly 'Castle.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=407dd0808d44fbdc' o una delle relative dipendenze. La definizione di manifesto dell'assembly specificato non corrisponde al riferimento all'assembly. (Eccezione da HRESULT: 0x80131040)

**Comment by stakx** [comment]
The latest published version of Moq is built against Castle.Core 4.0.0. If you replaced that dependency with version 4.1.0, you probably need to set up an assembly binding redirect in Web.config / App.config.

**Comment by stakx** [comment]
Moq 4.7.49 is now available. It targets Castle.Core 4.1.0 as well. This problem should be resolved once you upgrade to Moq 4.7.49.
