### ISSUE TITLE
Moq in UWP needs NeutralResourcesLanguageAttribute 

### ISSUE THREAD

**Issue by benbillbob** [moq/moq4#393]
I receive this build warning when using moq in a uwp unit test app. Any issues with adding the attribute? Or is there another way to deal with this warning?

Moq.dll : warning MSB3817: The assembly "...nuget\packages\Moq\4.7.63\lib\netstandard1.3\Moq.dll" does not have a NeutralResourcesLanguageAttribute on it. To be used in an app package, portable libraries must define a NeutralResourcesLanguageAttribute on their main assembly (ie, the one containing code, not a satellite assembly).

**Comment by stakx** [comment]
I guess adding that attribute to `AssemblyInfo.cs` wouldn't hurt. Would you like to send a PR? (If you do, please direct it at the `develop` branch.)

**Comment by benbillbob** [comment]
Done.
