### ISSUE TITLE
UWP limitations

### ISSUE THREAD

**Issue by XhantiMda** [moq/moq4#398]
Hi guys,

Are there any limitations in using Moq Version: 4.7.63 in a UWP app.

Thanks.

**Comment by stakx** [comment]
Hi @XhantiMda, I am still on a Windows 8 box, so I can only derive an answer from what's currently going on around that topic (https://github.com/moq/moq4/issues?q=uwp). To summarise:

 * There's an open issue regarding Moq's use of embedded resources and `ResourceManager`, which can apparently cause problems on Windows 10 / UWP (which uses another mechanism for localizable resources). See #274.

 * Also related to localizable resources, we have only just added an `[assembly: NeutralResourcesLanguage]` attribute to the Moq assembly, but that's only going to be become effective with the next published release (version >4.7.63) &mdash; or when you compile Moq yourself from the `develop` branch. 4.7.63 doesn't have that attribute, which might cause compilation warnings or errors when building an UWP app package. See #393.

 * Then there's a still pending issue #195 which is sort of dependent on what happens with DynamicProxy.

Perhaps someone who has a Windows 10 box can give some additional feedback. You are also very welcome to report any additional issues that you discover yourself. But remember, Moq doesn't officially support UWP; it currently targets .NET 4.5 and .NET Standard 1.3.

**Comment by stakx** [comment]
@XhantiMda, can we close this?

**Comment by stakx** [comment]
If you have any other specific questions about UWP support, feel free to ask.
