### ISSUE TITLE
www.moqthis.com produces 404

### ISSUE THREAD

**Issue by Ireney** [moq/moq4#41]
This is not so much an issue with the framework itself; more so with "appearances".

Navigating to moqthis.com produces a GitHub-branded 404 error.

It is difficult to sell this project to a team when first impressions suggest that the project is dead/no longer active.  https://code.google.com/p/moq/ is outdated, and certain links are broken (API documentation, for instance: http://clariusconsulting.net/labs/moq/index.html).

**Comment by stakx** [comment]
I am closing this issue as http://moqthis.com no longer produces a HTTP 404, and kzu appears to have fixed at least one broken link as mentioned above.

Regarding the other raised points:

* The Google Code project page clearly points back to this GitHub repository. Copyright headers in source code still mention the Google Code site; this will be tracked in #356.

* Moq's documentation currently lives at http://www.nudoq.org/#!/Projects/Moq, which is not fully up-to-date; this is being tracked in #354.
