### ISSUE TITLE
Upgrade to Castle.Core version 4.2.0

### ISSUE THREAD

**Issue by stakx** [moq/moq4#425]
This is a reminder to upgrade to the next version of Castle.Core once it's published.

One reason for the upgrade is to solve the package versioning issue discussed in #418 and https://github.com/castleproject/Core/issues/288. Therefore, possibly upgrade in conjunction with #424.

/cc @skovsende, @JohanLarsson

**Comment by stakx** [comment]
Castle.Core 4.2.0 has just been published ([here](https://github.com/castleproject/Core/releases/tag/v4.2.0)).

**Comment by skovsende** [comment]
Any timeframe on a release?

**Comment by stakx** [comment]
I originally would've liked to include this in 4.8.0, together with the change suggested in #424, but 4.8.0 is probably still several weeks away. If it's important for people to have a version of Moq dependent on Castle.Core 4.2.0, then I guess we could do another patch release (4.7.x).
