### ISSUE TITLE
Can I Use it with dotnet core 1.1

### ISSUE THREAD

**Issue by wolfgangschneider** [moq/moq4#427]
Hi
I try out to use this package with .Net core 1.1 but without luck.

What i did
Open VS2017.2
Create a asp.net wan API using netcoreApp 1.1
Create a XUnitTest project
Add the Nuget Package moq latest stable 4.7.99 -> moq 4.7.9  aperes in the NuGet folder in Solution Explorer
add using Moq;  -> the type or namespace Moq could not be found
on cmd run dotnet update -> does not help

What i am doing wrong ?

**Comment by stakx** [comment]
This should definitely work via the `netstandard1.3` target. Could you perhaps upload a ZIP of a minimal ASP.NET Core project that you create according to your above instructions?

**Comment by wolfgangschneider** [comment]
Hi

I deleted the bin and obj Folders

wolfgang


Von: stakx<mailto:notifications@github.com>
Gesendet: Montag, 17. Juli 2017 21:54
An: moq/moq4<mailto:moq4@noreply.github.com>
Cc: wolfgangschneider<mailto:wolfgang@easybyte.at>; Author<mailto:author@noreply.github.com>
Betreff: Re: [moq/moq4] Can I Use it with dotnet core 1.1 (#427)


This should definitely work via the netstandard1.3 target. Could you perhaps upload a ZIP of a minimal ASP.NET Core project that you create according to your above instructions?

**Comment by stakx** [comment]
> I deleted the bin and obj Folders

Yes, and...? (Did this resolve your problem?)

**Comment by wolfgangschneider** [comment]
Hi

No it describe the requested zip file attached to the mail. Anyhow, where should I upload the zip file ?


B.R Wolfgang

Von: stakx<mailto:notifications@github.com>
Gesendet: Montag, 17. Juli 2017 23:34
An: moq/moq4<mailto:moq4@noreply.github.com>
Cc: wolfgangschneider<mailto:wolfgang@easybyte.at>; Author<mailto:author@noreply.github.com>
Betreff: Re: [moq/moq4] Can I Use it with dotnet core 1.1 (#427)


I deleted the bin and obj Folders

Yes, and...? (Did this resolve your problem?)

**Comment by stakx** [comment]
> where should I upload the zip file ?

Right here, for example. Drag & drop a ZIP file into the multi-line text box where you write a post. This might not work on GitHub's mobile UI, use the full desktop UI when in doubt.

**Comment by wolfgangschneider** [comment]
Hi

There is a mistake. I already send You the zip file per mail (the mail with the “I delete the pin folder” Anyhow I attach the zip file to this mail again, but change the extension ti ._zip_)

B.R Wolfgang

Von: stakx<mailto:notifications@github.com>
Gesendet: Dienstag, 18. Juli 2017 08:43
An: moq/moq4<mailto:moq4@noreply.github.com>
Cc: wolfgangschneider<mailto:wolfgang@easybyte.at>; Author<mailto:author@noreply.github.com>
Betreff: Re: [moq/moq4] Can I Use it with dotnet core 1.1 (#427)


where should I upload the zip file ?

Right here, for example. Drag & drop a ZIP file into the multi-line text box where you write a post. This might not work on GitHub's mobile UI, use the full desktop UI when in doubt.

**Comment by stakx** [comment]
Wherever you mailed that file, it didn't end up in my mailbox. Please just upload it here. ;-)

**Comment by wolfgangschneider** [comment]
Hi

I Add the File once more to this mail thread. I also add my Company address to Receiver list to see if I get the attachment

BR. Wolfgang

Von: stakx<mailto:notifications@github.com>
Gesendet: Dienstag, 18. Juli 2017 12:40
An: moq/moq4<mailto:moq4@noreply.github.com>
Cc: wolfgangschneider<mailto:wolfgang@easybyte.at>; Author<mailto:author@noreply.github.com>
Betreff: Re: [moq/moq4] Can I Use it with dotnet core 1.1 (#427)


Wherever you mailed that file, it didn't end up in my mailbox. Please just upload it here. ;-)

**Comment by wolfgangschneider** [comment]
[CoreToTest.zip](https://github.com/moq/moq4/files/1157990/CoreToTest.zip)

**Comment by stakx** [comment]
Just for the record, this must have been a Visual Studio IntelliSense or NuGet restore failure. The provided solution compiles just fine.
