### ISSUE TITLE
Moq Unity3D MonoBehaviour

### ISSUE THREAD

**Issue by NoxMortem** [moq/moq4#429]
I know this is more of a stretch, but I am hoping this question already came up (could not find any issues related to it): Is it possible to Mock Unity3d MonoBehaviour? Unity3d MonoBehaviours can not be instantiated with new.

**Comment by stakx** [comment]
Generally speaking, Moq is not a magic wand. It simply automates tasks that you would normally have to do by hand. So if you cannot instantiate those MonoBehaviours manually, it is unlikely that Moq would be able to do it. But have you simply tried it?

**Comment by stakx** [comment]
@NoxMortem, can we close this?
