### ISSUE TITLE
How To Moq Factory StreamReader.Create Method

### ISSUE THREAD

**Issue by green4don** [moq/moq4#440]
Simple problem, should have a simple solution. I have moq'd methods at lower levels with a StreamReader parameter (e.g. the ParseFile(reader) example below), but as I move up the calling chain, requirements become more abstract. 

I'm using SystemWrapper for dependency injection.

This is the original method I want to moq (with comments and try blocks removed).

        internal static PbnGame ParseStream(Stream source)
        {
            using (StreamReader reader = new StreamReader(source))
            {
                    return ParseFile(reader);
            }
        }

After DI I end up with this:
 
        internal static PbnGame ParseStream(IStream source, StreamReaderWrapFactory factory = null)
        {
            using (IStreamReader reader = (factory ?? new StreamReaderWrapFactory()).Create(source))
            {
                return ParseFile(reader);
            }
        }

The factory method maps out as:

        public partial class StreamReaderWrapFactory : IStreamReaderFactory
        {
            public IStreamReader Create(System.IO.Stream stream)
            {
                return new StreamReaderWrap(stream);
            }
        }

So my test case is as follows (some details on mockStreamReader which works fine are not shown):

        [TestMethod()]
        public void PbnFile_ParseStreamTest()
        {
            // arrange  
            var mockStream = new Mock<IStream>();
            var mockStreamReader = new Mock<IStreamReader>();
            var mockStreamReaderWrapFactory = new Mock<StreamReaderWrapFactory>();
            **mockStreamReaderWrapFactory.Setup<IStreamReader>(x => x.Create(It.IsAny<IStream>())).Returns(() => mockStreamReader.Object);**
            // act
            PbnGame game = PbnFile.ParseStream(mockStream.Object, mockStreamReaderWrapFactory.Object);
            Tests.Log(game);
            // assert  
            Assert.AreEqual(2, game.Count);
        }

When I run this case, I get an exception:

Result StackTrace:  
at Moq.Mock.ThrowIfSetupExpressionInvolvesUnsupportedMember(Expression setup, MethodInfo method)
   at Moq.Mock.<>c__DisplayClass61_0`2.<Setup>b__0()
   at Moq.PexProtector.Invoke[T](Func`1 function)
   at Moq.Mock.Setup[T,TResult](Mock`1 mock, Expression`1 expression, Condition condition)
   at Moq.Mock`1.Setup[TResult](Expression`1 expression)
   at Pbn.Tests.PbnFileTests.PbnFile_ParseStreamTest() in PbnFileTests.cs:line 97
Result Message: 
Test method Pbn.Tests.PbnFileTests.PbnFile_ParseStreamTest threw exception: 
System.NotSupportedException: Invalid setup on a non-virtual (overridable in VB) member: x => x.Create(It.IsAny<IStream>())

The example doesn't care about the IStream object, but it needs to be present and not null to compile.

Clearly my setup statement on the Create method is poorly formed. I want to return and use the StreamReader but can't see how to do this.

Thanks.

**Comment by stakx** [comment]
The exception message tells you what the problem is: you are trying to set up a method (`StreamReaderWrapFactory.Create`) that isn't virtual. Because it isn't virtual, Moq cannot override its default implementation, which it would have to do in order to honour your setup (`.Returns(...)`).

Try either of those fixes:

* Declare the method `StreamReaderWrapFactory.Create` as `virtual` so Moq can override it.
* Instead of creating a mock of `StreamReaderWrapFactory`, create a mock of `IStreamReaderFactory` and override its `Create` method.

**Comment by green4don** [comment]
The fix is, of course, that the moq should be on an Interface and not on the class. Correct test code is as follows and this works fine. Thanks.

        [TestMethod()]
        public void PbnFile_ParseStreamTest()
        {
            // arrange  
            var mockStream = new Mock<IStream>();
            var mockStreamReader = new Mock<IStreamReader>();
            var mockStreamReaderFactory = new Mock<IStreamReaderFactory>();
            mockStreamReaderFactory.Setup<IStreamReader>(x => x.Create(It.IsAny<IStream>())).Returns(() => mockStreamReader.Object);
            // act
            PbnGame game = PbnFile.ParseStream(mockStream.Object, mockStreamReaderFactory.Object);
            Tests.Log(game);
            // assert  
            Assert.AreEqual(2, game.Count);
        }
