### ISSUE TITLE
Cannot mock named optional parameter

### ISSUE THREAD

**Issue by alexandru-calinoiu** [moq/moq4#444]
My call is:

```
.GetPagedListAsync(pageSize: 1000, orderBy: source => source.OrderBy(bu => bu.Name))
```

My mock setup is:

```
                .Setup(r => r.GetPagedListAsync<BusinessUnit>(null, null, It.IsAny<Func<IQueryable<BusinessUnit>, IOrderedQueryable<BusinessUnit>>>(), null, 0, 1000, true, It.IsAny<CancellationToken>()))
```

The method signature is:

```
    Task<IPagedList<TResult>> GetPagedListAsync<TResult>(Expression<Func<TEntity, TResult>> selector, Expression<Func<TEntity, bool>> predicate = null, Func<IQueryable<TEntity>, IOrderedQueryable<TEntity>> orderBy = null, Func<IQueryable<TEntity>, IIncludableQueryable<TEntity, object>> include = null, int pageIndex = 0, int pageSize = 20, bool disableTracking = true, CancellationToken cancellationToken = default (CancellationToken)) where TResult : class;
```

The matching will fail and the mocked result will never by returned.

I am able to make it work by doing the call like this:

```
.GetPagedListAsync<BusinessUnit>(null, null, source => source.OrderBy(bu => bu.Name), null, 0, 1000)
```

It's a little tedious to specify all this default values, anything I can do about it?

**Comment by stakx** [comment]
@alexandru-calinoiu, could you please provide minimally complete repro code? That would be a lot easier than having to put together the various pieces you've provided. (Btw. the method signature you're providing is syntactically incorrect: you cannot intersperse optional and non-optional parameters.) Thanks!
