### ISSUE TITLE
SetupSequence is missing for void methods

### ISSUE THREAD

**Issue by alexbestul** [moq/moq4#451]
SetupSequence is cool, but only works for methods that produce a return value. Is there a reason that it's not supported for `void` methods? I'd like to have that support in order to test some exception-handling retry logic.

I've got a branch ready with `Pass` and `Throws` implemented. Those are the only useful methods I could think of.

Please let me know if you're interested, and I'll open a PR.

**Comment by alexbestul** [comment]
Opened PR #454

**Comment by stakx** [comment]
Hi @alexbestul, thank you for your PR, and sorry for the delay. Currently trying to get some bug fixes through, but I will review your PR soon. It sounds like a sensible and useful extension to Moq's API.

**Comment by stakx** [comment]
Merged. Thank you for this new feature! 👍

**Comment by Adrian10988** [comment]
As of version 4.7.145 `SetupSequence` still complains about not providing a `TResult`

**Comment by stakx** [comment]
@Adrian10988: Not sure what you mean by that, is this related to this issue? If so, the answer is simply that the new feature hasn't been merged into `master` yet / is scheduled for version 4.8.0. If it's unrelated, please open a new issue.

**Comment by Adrian10988** [comment]
Yea I was noting that it still seemed to not be fixed. I thought I had seen it pushed to the current version. My mistake, and thank you for the reply.

**Comment by stakx** [comment]
You can always check the changelog for these kinds of questions. :wink:
