### ISSUE TITLE
Setup does not throw NotSupportedException when setting up sealed method seen through an interface

### ISSUE THREAD

**Issue by stakx** [moq/moq4#453]
This is a continuation of #452 (reported by @toha73).

```csharp
public interface IInterface
{
    string Answer { get; }
}

public class Implementation : IInterface
{
    public string Answer => "answer from implementation";  // note: non-overridable!
}

[Fact]
void Setup_throws_NotSupportedException_when_given_sealed_method()
{
    // Arrange:
    Implementation mockedImplementation = Mock.Of<Implementation>();
    Mock<IInterface> mock = Mock.Get<IInterface>(mockedImplementation);

    // Act:
    var error = Record.Exception(() =>
    {
        mock.Setup(_ => _.Answer).Returns("mocked answer");
    });

    // Assert:
    Assert.NotNull(error);
    Assert.IsType<NotSupportedException>(error);
}
```

This test creates a mock `Implementation`, then tries to set up `Answer` by looking at the mock through the `IInterface` interface. This setup should fail because `Implementation.Answer` is sealed, i.e. non-overridable, and therefore non-interceptable.

However, the test currently fails, i.e. the setup (incorrectly) runs to completion without any error. This would probably suggest to most people that the setup will take effect, yet that is not the case: `proxy.Answer` will (correctly) still return `"answer from implementation"` and not `"mocked answer"`.

In more straightforward usages, such as `new Mock<Implementation>().Setup(_ => _.Answer)`, Moq correctly recognizes that `Implementation.Answer` is non-overridable and throws.

The problem here is that Moq only sees `IInterface.Answer` and doesn't verify what target method (`Implementation.Answer`) this interface method might map to for the given mock, and whether that target method might be sealed.

This problem can only surface when mocking classes. It can't happen when mocking an interface directly.

The problem also isn't unique to just `Setup`. For example, `SetupGet` is likewise affected.

**Comment by HossienMehdikhah** [comment]
Hi i same exception when setup generic interface. its ok with non generic interface but generic Throw Exception
