### ISSUE TITLE
4.7.137 regression

### ISSUE THREAD

**Issue by cbruun** [moq/moq4#469]
After upgrading to Moq 4.7.137 the following scenario breaks:

```c#
public void Main()
{
	new Mock<IBreak>().Object;
}

public interface IBreak
{
	void DoStuff<T>(Implementation1<T> a);
	void DoStuff<T>(Implementation2<T> a);
}

public abstract class BaseType<T>
{
}

public class Implementation1<T> : BaseType<T>
{
}

public class Implementation2<T> : BaseType<T>
{
}
```

**Comment by stakx** [comment]
Thanks for reporting. This looks like a valid usage scenario, I can't see a reason why this *shouldn't* work.

It appears to be caused by some change inside Castle Core 4.2.0. I'll do some investigation and see what I can find.

**Comment by stakx** [comment]
@cbruun, most of the work to get this fixed will have to happen over at [castleproject/Core](https://github.com/castleproject/Core) now.

In the meantime, if you could spare some time & would like to contribute to Moq, please feel free to submit a PR (against the `develop` branch) that adds your above repro code as a skipped unit test [there, in `UnitTests/Regressions/IssueReportsFixture.cs`](https://github.com/moq/moq4/blob/48c6aa654f94907d4b19c8b2275c9e8d824f88e5/UnitTests/Regressions/IssueReportsFixture.cs#L1601). For example:

```csharp
#region 469

public class Issue469
{
    [Fact(Skip = "Temporarily disabled due to a regression in Castle Core, see https://github.com/castleproject/Core/issues/309.")]
    …
}

#endregion
```

**Comment by ADThomsen** [comment]
@stakx, @cbruun and I worked on the issue together when he reported the regression, so I have taken the liberty to write the test and make the pull request.

I just now saw that you mention `BaseType<T>` isn't actually needed. Feel free to remove it from the PR.

**Comment by stakx** [comment]
@ADThomsen, thanks for letting me know. Will merge your PR in a short while.

**Comment by ivancitin** [comment]
This version along with Castle.Core 4.2.0 definitely breaks us. Will be stock with the previous version, i'll give it a try on the next release.

I was not able to pinpoint the issue, other than noticing test get hanged indefinitely.

**Comment by stakx** [comment]
@ivancitin: Can you please post repro code of such a test that hangs as a separate issue? Could be a different problem than the one reported here.

**Comment by stakx** [comment]
I'm preparing a "hotfix" version of Moq (4.7.x) which should be available in the next 24 hours or so.

**Comment by stakx** [comment]
@cbruun and @ADThomsen: Moq 4.7.142 is now available. Once you update (which should automatically update its dependency Castle Core to 4.2.1, which is the important bit), you should be good.

**Comment by ADThomsen** [comment]
@stakx Thanks for the update. We have upgraded Moq and can confirm that our tests again work as expected.
