### ISSUE TITLE
.Setup() on EF DbContext mock impossible after upgrading Moq

### ISSUE THREAD

**Issue by MatejQ** [moq/moq4#475]
Hello,
today I tried upgrading old version of Moq to latest (4.2.1402.2112 to 4.7.137). The old version works just fine but the new version fails on a call to `.Setup()` on a mock of EF `DbContext`:

```csharp
mockContext.Setup(m => m.Set<ApplicationUser>().Create())
    .Returns(() =>
    {
        Mock<ApplicationUser> mock = new Mock<ApplicationUser>();                   
        return mock.Object; 
    });
```

where `mockContext` is `Mock<SystemDatabase>` and `SystemDatabase` inherits `DbContext`.

The exception is:

```
Cannot set up IInternalQueryAdapter.get_InternalQuery because it is not accessible to the proxy generator used by Moq:
Can not create proxy for method System.Data.Entity.Internal.Linq.IInternalQuery get_InternalQuery() because it or its declaring type is not accessible. Make it public, or internal and mark your assembly with [assembly: InternalsVisibleTo("DynamicProxyGenAssembly2, PublicKey=0024000004800000940000000602000000240000525341310004000001000100c547cac37abd99c8db225ef2f6c8a3602f3b3606cc9891605d02baa56104f4cfc0734aa39b93bf7852f7d9266654753cc297e7d2edfe0bac1cdcf9f717241550e0a7b191195b7667bb4f64bcb8e2121380fd1d9d46ad2d92d2d15605093924cceaf74c4861eff62abf69b9291ed0a340e113be11e6a7d3113e92484cf7045cc7")] attribute, because assembly EntityFramework is strong-named.
```

I guess it has some problems with EF but I don't know what to do to fix this. Also by googling I found out I am the only one in the world having this issue.
EF is the latest version, 6.1.3. Can you please suggest what to do with this?

**Comment by stakx** [comment]
@MatejQ, could you please post short repro code that reproduces the error you've reported? It's pretty much impossible to help otherwise.

**Comment by stakx** [comment]
You are using a recursive setup expression, `m.Set<ApplicationUser>().Create()`. In such cases you're forcing Moq to setup all properties it encounters along the way, and it seems one of them has a type that is internal to EF. The exception is triggered by Moq to warn you that something can't actually be mocked. I agree that this probably shouldn't happen, but then you can easily work around it by splitting the recursive setup expression and do this instead:

```csharp
var mockSet = new Mock<DbSet<ApplicationUser>>();
mockSet.Setup(s => s.Create())
    .Returns(() =>
    {
        Mock<ApplicationUser> mock = new Mock<ApplicationUser>();
        return mock.Object;
    });

mockContext.Setup(m => m.Set<ApplicationUser>())
    .Returns(() => mockSet.Object);
```

I've seen quite a few people having problems with mocking Entity Framework `DbContext`s and most of them appear to create separate mocks for their `DbContext` and `DbSet` instances.

Good luck!

P.S.: If you want to test your Entity Framework-based database code, and switching to EF Core is an option at all, take a look at [Testing with InMemory](https://docs.microsoft.com/en-us/ef/core/miscellaneous/testing/in-memory).

**Comment by MatejQ** [comment]
I amended the code according to what you suggested. It helped, thank you!
