### ISSUE TITLE
VerifyAll() does not appear to work correctly if the target moq is in a try catch block.

### ISSUE THREAD

**Issue by stevewi1950** [moq/moq4#477]
I am fairly new to Moq but have previously used NMock2 and Rhino.Mocks so have experience in what to expect when using such tools.

I have come across an instance where I would expect a moq exception to be raised when VerifyAll() is called but my tests are passing correctly.

This is the interface I am mocking (a very simple example) :- 

namespace ClassToTest
{
    public interface ITestGraph
    {
        void CreateMethod();
        bool SubmitChanges();
    }
}

This is the class that I am testing :- 

namespace ClassToTest
{
    public class Controller
    {
        ITestGraph _graph = null;

        public Controller(ITestGraph graph)
        {
            _graph = graph;
        }

        public void DoStuff()
        {
            try
            {
                _graph.SubmitChanges();
            }
            catch (Exception ex)
            {
                Console.WriteLine("In ex handler." + ex.Message);
            }
        }
    }
}

This is my test that is passing and should be failing .

namespace ClassToTest.UnitTests
{
    [TestFixture]
    public class ControllerTests
    {
        private MockRepository _mocks = null;

        [SetUp]
        public void Setup()
        {
            _mocks = new MockRepository(MockBehavior.Strict);
        }

        [TearDown]
        public void Teardown()
        {
            _mocks.VerifyAll();
            _mocks = null;
        }

        [Test]
        public void TestSubmitt()
        {
            Mock<ITestGraph> _mockGraph = _mocks.Create<ITestGraph>();
       //     _mockGraph.Setup(x => x.SubmitChanges())
       //         .Returns(true);
          
            Controller inst = new Controller(_mockGraph.Object);
            Assert.IsNotNull(inst);

            inst.DoStuff();
        }
    }
}

Now I would expect the mockGraph verification to fail as I have not setup the SubmitChanges() call but because the _graph.SubmitChanges() call in the ClassToTest is in a try catch block it is fine as the Moq exception is caught in that code.   If I comment out the try catch block in ClassToTest.DoStuff and just leave the _graph.SubmitChanges()  call the verification fails as expected.

Is this how Moq should work or is this a bug ?
I think this is an issue as the mock framework should not dictate how the code under test should be written eg. with or without a try catch block.

I apologise in advance if there is already an issue but I have had a look through the open ones an cannot see one so have raised this one.

Many thanks in advance.

**Comment by stakx** [comment]
Your system under test (SUT) is not the `SubmitChanges` method, like your test's name would suggest; you are testing `Controller.DoStuff`, which is in effect an exception-swallowing black hole.

Further, you are passing your `Controller` a mock that is set up to throw as soon as it is invoked. Given that `Controller.DoStuff` swallows any and all exceptions, that's a pretty useless mock to use in your test. All your test really asserts is that `Controller.DoStuff` either doesn't invoke the mock, or that it swallows `MockException`s.

What needs to change is your test, not Moq's behaviour. I can't really say more because it's impossible to say what your test was supposed to do.

**Comment by stevewi1950** [comment]
Thanks for the quick reply and sorry for the really basic example.  This is not how the code that is being tested is implemented but just the smallest footprint to highlight my question.  I think you have answered my question with the info in the last bit of your reply. . My understanding of how verifyAll works is wrong as I would have expected the call to submitChanges to fail the verification as it hasn't been setup....  Sorry to have wasted your time and thank you for your reply....

**Comment by stakx** [comment]
You know, you could do something like this:

```csharp
bool wasInvoked = false;
mock.Setup(m => m.SubmitChanges())
    .Callback(() => wasInvoked = true);
inst.DoStuff();
Assert.False(wasInvoked);
```

**Comment by stevewi1950** [comment]
Thanks, I have used callbacks in a few other places like this so this is an option.
