### ISSUE TITLE
Assigning out/ref parameters in Moq

### ISSUE THREAD

**Issue by kiran94** [moq/moq4#490]
Currently there does not seem to be a way to assign 'out' and 'ref' parameters for Setup in Mocked objects. 

The following shows a potential solution to assigning 'out' variables but it would be interesting to get other peoples opinions on this and if we can also apply this to 'ref' variables.

https://stackoverflow.com/questions/1068095/assigning-out-ref-parameters-in-moq

**Comment by stakx** [comment]
This feature is scheduled for the [v4.8.0 milestone](https://github.com/moq/moq4/milestone/4) and has already been implemented on the `develop` branch; see #105.
