### ISSUE TITLE
cannot save It.Is<Type> in local variable for verify

### ISSUE THREAD

**Issue by drewsk01** [moq/moq4#492]
I'm seeing an issue where I try:

```csharp
var itIs = It.Is<Type>(obj => obj.foo == bar);
mock.Verify(x => x.Action(itIs), Times.Once());
```

And that fails, but then I try:

```csharp
mock.Verify(x => x.Action(It.Is<Type>(obj => obj.foo == bar)), Times.Once());
```

and that succeeds.  Is this something odd with Moq or C# in general?  Relatively new to both, so appreciate the help.  Thanks!

**Comment by stakx** [comment]
This is to be expected. There's nothing wrong with Moq, nor with C# here.

> ```csharp
> var itIs = It.Is<Type>(obj => obj.foo == bar);
> ```

You are actually executing the method `It.Is<T>` here, `itIs` will end up having the value `default(Type)`. Therefore, your verification is equivalent to this:

```csharp
mock.Verify(x => x.Action(default(Type)), Times.Once());
                          ^^^^^^^^^^^^^
```

and you probably didn't call `x.Action` with that particular argument.

If, however, you do this:

> ```csharp
> mock.Verify(x => x.Action(It.Is<Type>(obj => obj.foo == bar)), Times.Once());
> ```

then `It.Is<T>` does not get executed, but transformed into an [`Expression` (expression sub-tree)](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/expression-trees/index "See 'Expression Trees (C#)' at docs.microsoft.com") that describes the original C# expression, which Moq can then analyze.

If you're new to C#, I suggest you read the article I just linked to, then play around a bit with e.g. `Func<bool> func = () => true` vs. `Expression<Func<bool>> funcExpr = () => true` to see how this bit of compiler magic works. Then note that `Mock.Verify`'s first parameter is declared as an `Expression<Action<TMock>>`, not as an `Action<TMock>`. :wink:
