### ISSUE TITLE
Swapped method arguments will overwrite previous method setup

### ISSUE THREAD

**Issue by payn-git** [moq/moq4#50]
What steps will reproduce the problem?
When method with two arguments of same type is setup another setup call with swapped arguments will lead to situation where previous setup is removed.

What is the expected output? What do you see instead?
In case when arguments are swapped Mock should still hold reference to two different versions of method invocation setup. First which will get instance A as first argument and B as second argument. Second which have B as first argument and A as second argument.

Please reffer to attached simple code example which will simulate issue very easily.

What version of the product are you using? On what operating system?
v4.0.20926

Please provide any additional information below.
Please see attached code example which will lead to incorrect behaviour.
![moqincorrectbehaviourexample](https://f.cloud.github.com/assets/4748314/680924/dd2d56a8-d9a1-11e2-8285-b1baa1956a5e.png)

**Comment by LeonidLevin** [comment]
This is now solved, see issue #252 and pull request #262.
The issue can be closed.

**Comment by kzu** [comment]
Indeed. Thanks @LeonidLevin!
