### ISSUE TITLE
Bring back .NET 4.0 support

### ISSUE THREAD

**Issue by PawelTroka** [moq/moq4#518]
Since new csproj format allows easy multitargetting it should be fairly easy unless moq needs some packages that do not support .NET 4.0.

**Comment by PawelTroka** [comment]
I agree with you that .NET 4.0 is comparatively ancient. However assuming that it's only about `ValueTask<T>` then it's easily possible to just `PackageReference` with condition `Condition="'$(TargetFramework)' == 'net40'"` one of backport packages like:

- https://www.nuget.org/packages/Theraot.Core/
- https://www.nuget.org/packages/dylan.NET.Tasks/

Assuming it's only about referencing packages with backported functionality with maybe few conditions here and there I think that moq should have it's try at supporting old .NET versions like 4.0.

**Comment by kzu** [comment]
It is no longer just "comparatively ancient". It's effectively [no longer a Microsoft-supported platform](https://blogs.msdn.microsoft.com/dotnet/2015/12/09/support-ending-for-the-net-framework-4-4-5-and-4-5-1/).

If .NET 4.0 is really important to you, we'd be glad to [review a PR that provides that support](https://medium.com/@mikeal/stop-supporting-old-releases-70cfa0e04b0c) (and test). 

Thanks!

**Comment by stakx** [comment]
As above. If such a PR *does* come in (and until that happens, I'm closing this issue), I'll do my part and review it fairly. But bear in mind that the world has moved on from .NET 4.0, and Moq shouldn't be held back by something that is officially outdated, so securing long-term support for it simply won't be a priority.

**Comment by joehoeller** [comment]
Plz dont bring back .net 4 support
