### ISSUE TITLE
It.Is Overload taking a T not a Func

### ISSUE THREAD

**Issue by BlythMeister** [moq/moq4#532]
Rather than having to keep writing a Func to check equality
Using similar logic to the It.IsIn but with just 1 value

Suggest using the same logic as It.Is but as well as a Func, allow just an object and perform a comparison.

**Comment by stakx** [comment]
I'm afraid I don't quite understand. Could you explain this in a different way, or make a concrete example?

**Comment by BlythMeister** [comment]
oh...you can do that....can you mix concrete value and "It" functions?
I would like to do
```
mock.Verify(m => m.Foo(10, It.Is<string>(i => i.StartsWith("hello"))));
```

**Comment by stakx** [comment]
Of course. Don't forget to take a look at the quickstart over in the wiki, it demonstrates how to use the most commonly used features. ;-)

**Comment by BlythMeister** [comment]
@stakx sorry :(
i couldn't see any example of mixing concreate and not concreate values.
Previous frameworks i used was either all concreate or all function type.

Thanks for your quick response!

**Comment by stakx** [comment]
No worries! :)
