### ISSUE TITLE
`Mock.Of<T>()` is much slower than `new Mock<T>` (up to several orders of magnitude)

### ISSUE THREAD

**Issue by stakx** [moq/moq4#547]

**Comment by informatorius** [comment]
I added a lambda compile cache to Moq and Mock.Of<T>() performance improves.
https://github.com/moq/moq4/issues/188

**Comment by informatorius** [comment]
Is my understanding right that Mock.Of<Interface>() equals
```
var mock  = new Mock<Interface>();
mock.SetupAllProperties();
return mock.Object; 
```
If true can we just replace the

**Comment by stakx** [comment]
@informatorius - I'd have to check whether the current implementation is equivalent to what you've shown above. If so, that's a possibility. But we cannot do the same for the parameterised `Mock.Of` overload.

I'll get back to you about that.

**Comment by informatorius** [comment]
Is `Mock.Of<T>(predicate)` the same as 
```
var mock = new Mock<IFoo>();
mock.SetupAllProperties();
mock.Setup(predicate);
return mock.Object;
```

**Comment by stakx** [comment]
Closing this issue as the performance of `Mock.Of<T>()` has now been taken care of. Thank you, @informatorius.

There's still the other method overload, `Mock.Of<T>(Func<T, bool>)` to deal with. Improving its performance would likely require some heavy refactoring regarding how Moq processes setups and LINQ setup expressions. This will probably deserve its own issue.
