### ISSUE TITLE
Can't install Moq NuGet on UWP

### ISSUE THREAD

**Issue by kzu** [moq/moq4#559]
> NOTE: moved from https://github.com/moq/moq/issues/8 by @DerGary

Hello, 

I'm currently having the problem that I can't install Moq in a UWP UnitTestApp project. It is the only project type that can be used to unit test an uwp app.

Moq says on NuGet that it is compatible with .NetStandard 1.3 which should be compatible with UWP when looking at this table: https://docs.microsoft.com/en-us/dotnet/standard/net-standard

I'm getting the following error while Installing the Package:
```
Restoring packages for UnitTestProject1\project.json...
System.Reflection.Emit.ILGeneration 4.3.0 provides a compile-time reference assembly for System.Reflection.Emit.ILGeneration on UAP,Version=v10.0.10586, but there is no run-time assembly compatible with win10-arm-aot.
System.Reflection.Emit.ILGeneration 4.3.0 provides a compile-time reference assembly for System.Reflection.Emit.ILGeneration on UAP,Version=v10.0.10586, but there is no run-time assembly compatible with win10-x64-aot.
System.Reflection.Emit.ILGeneration 4.3.0 provides a compile-time reference assembly for System.Reflection.Emit.ILGeneration on UAP,Version=v10.0.10586, but there is no run-time assembly compatible with win10-x86-aot.
Package restore failed. Rolling back package changes for 'UnitTestProject1'.
Time Elapsed: 00:00:01.3615812
========== Finished ==========
```

When I try to install the package System.Reflection.Emit.ILGeneration on its own I get the same error.

Greetings 
Gary

**Comment by stakx** [comment]
@DerGary -

> ```
> System.Reflection.Emit.ILGeneration 4.3.0 provides a compile-time reference assembly for System.Reflection.Emit.ILGeneration on UAP,Version=v10.0.10586, but there is no run-time assembly compatible with win10-arm-aot.
> System.Reflection.Emit.ILGeneration 4.3.0 provides a compile-time reference assembly for System.Reflection.Emit.ILGeneration on UAP,Version=v10.0.10586, but there is no run-time assembly compatible with win10-x64-aot.
> System.Reflection.Emit.ILGeneration 4.3.0 provides a compile-time reference assembly for System.Reflection.Emit.ILGeneration on UAP,Version=v10.0.10586, but there is no run-time assembly compatible with win10-x86-aot.
> ...
> ```
> When I try to install the package System.Reflection.Emit.ILGeneration on its own I get the same error.

My understanding is that Windows Universal Platform *claims* to support .NET Standard 1.3, but it actually have full support. In particular, it doesn't have runtime code generation, which is very much required for Moq 4 to work.

I think we ran into this issue before; see #195.

Frankly, as long as Moq is based on run-time dynamic proxy generation (which is true for version 4), I don't think we can do anything about this. AFAIK, Moq 5 will be a rather different beast and likely won't be affected by this problem.

If I'm wrong, please correct me!
