### ISSUE TITLE
Raise(..) does not return event return values

### ISSUE THREAD

**Issue by kzu** [moq/moq4#561]
Hi

I have the following code, it doesnt work.
Please fix :)

```
public delegate object TestDelegate();

public class TestClassWithEvent
{
    public virtual event TestDelegate TestEvent;
}

[Test]
public void UnitTest()
{
    var mock = new Mock<TestClassWithEvent>();
    mock.Object.TestEvent += () => "test";

    object[] returnValue = mock.Raise(_ => _.TestEvent += null);
    Assert.AreEqual(returnValue.Single(), "test");
}
```

> Moved from https://github.com/moq/moq/issues/10 by @NoReturnValueFromRaise (?!)

**Comment by kzu** [comment]
@NoReturnValueFromRaise it's very much a common practice in .NET to never return anything from events, since any number of event handlers can handle the event and there is no way to tell who (if any) returned anything. A common way this is handled is by keeping the state in the event args instead, which is passed to all event handlers. Keep in mind that even in that case, there is no way to know in which order they will be called either.

**Comment by stakx** [comment]
@NoReturnValueFromRaise - I very much agree with the above post: Gathering return values from event handlers is a very unusual practice in .NET, and one that I think should not be encouraged. IMHO Moq would be better off without this capability.

**Comment by nietras** [comment]
I am hitting this issue on event that have Task as return value e.g. async events. Is this still not supported?
