### ISSUE TITLE
Setup cannot invoke callback with different number of parameters in Moq 4.8.1

### ISSUE THREAD

**Issue by Caraul** [moq/moq4#572]
Hi,

looks like adding ValidateReturnDelegate makes extension methods unusable in zero argument methods such as property getters. Here is small repro that fails at Setup phase with ArgumentException:

```
using Moq;

namespace TestMoq
{
	internal class Program
	{
		internal static void Main()
		{
			var a = new A();
			var mock = new Mock<A>();
			mock.SetupGet(aa => aa.P).Returns(a.Pext);
		}
	}

	public class A
	{
		public virtual string P { get; set; }
	}

	internal static class Aext
	{
		public static string Pext(this A a)
		{
			return "42";
		}
	}
}
```
Not sure if this is expected effect - please could anyone tell is such behavior correct?

**Comment by stakx** [comment]
@Caraul, thanks for reporting. Without looking into this in detail, this looks like a regression introduced in 4.8.0. This used to work in Moq 4.7.145, but I'm not sure whether that was by design or incidental. Will try to look into this in the next few days.

**Comment by stakx** [comment]
It's indeed a regression caused by 104c6464eccf9f2b643bf077adcf6da8d612e7d3 (which aimed to make delegate validation more strict, as you've already found out). We didn't have a test for the extension method case you've provided. I'll fix this over the next few days... or would you like to provide a PR yourself?

**Comment by Caraul** [comment]
Well, fix won't take weeks but one week maybe cause I need to go deeper inside Moq - if next week ASAP is acceptable then I'm in with PR.

**Comment by stakx** [comment]
@Caraul, that is fine. :+1:

I expect that a local fix in just that validation method should be possible; check whether the callback is an extension method (`IsStatic` & `IsDefined(typeof(ExtensionAttribute))`), and if so, subtract 1 from the parameter count when matching. Something like that.

Please don't forget to also add one or more unit tests to the test suite. :)

Thank you!

**Comment by Caraul** [comment]
Thanks for moving Moq forward - [Good job!](https://youtu.be/S0UvJZmGTsk) 👍

**Comment by stakx** [comment]
Moq 4.8.2 (which includes your patch, see [changelog](https://github.com/moq/moq4/blob/master/CHANGELOG.md#482-2018-02-23)) has just been published [on NuGet](https://www.nuget.org/packages/Moq/4.8.2).

**Comment by Caraul** [comment]
Great news, thank you very much!
