### ISSUE TITLE
Conventions for "extension" packages

### ISSUE THREAD

**Issue by Tragedian** [moq/moq4#574]
I'm interested in publishing some extensions to Moq, things which take dependencies on other libraries and probably don't belong in the core library. 

The obvious format for this would be a NuGet package. Given the recently-added verification of names to the NuGet repo, I thought it would be good to ask: are there any conventions for the naming of these kinds of packages so they're easy for others to find?

Besides naming, are there any other practices I should look to follow?

**Comment by stakx** [comment]
I am not aware of any such conventions specific to Moq, at least none that is already in use, given that the main Moq package is the only official one tied to this project.

Perhaps @kzu can shed some more light on this...?

**Comment by Tragedian** [comment]
The SpecFlow team has reserved `SpecFlow.*` on NuGet, with a `SpecFlow.Contrib.*` allowed for extensions. http://specflow.org/2017/nuget-packages-reserved-id-naming-conventions/

Are there any similar reservations for `Moq`?

**Comment by kzu** [comment]
Very good point. I'll follow the lead of SpecFlow on this. I had already requested the reservation, but had not made a request to allow Moq.Contrib.* for extension.

Thanks for bringing this up!

**Comment by Tragedian** [comment]
Worth mentioning the existing (but largely defunct?) [`Mock.Contrib`](https://www.nuget.org/packages/Moq.Contrib/) project?

**Comment by kzu** [comment]
An update: I heard back from nuget.org with:

> Moq and Moq.* are now reserved exclusively for kzu. Moq.Contrib.* is reserved for kzu, but is also listed as public.

Thanks
