### ISSUE TITLE
ValueTuple Package not necessary for .Net 4.7

### ISSUE THREAD

**Issue by bdarby22** [moq/moq4#578]
As of .Net 4.7, the ValueTuple is provided in the framework and the separate package reference is not necessary.  Its inclusion conflicts with the system library.

e.g. mock.Setup(e => e.DoStuff(It.IsAny<(int MyInt, DateTime MyDateTime) >())).Verifiable();

This would not compile until I forcibly removed the ValueTuple package  reference from my project.

**Comment by stakx** [comment]
Hi @bdarby22. Thanks for reporting this. If that is correct, we'd have to add a separate framework target for `net47` (or perhaps just `netstandard20`).

**Comment by stakx** [comment]
> Wouldn't it make even more sense for the .NET team to change the System.ValueTuple NuGet package so it is basically empty for `net47`?

According to https://github.com/dotnet/corefx/issues/23085, this has already happened. But after the ordeal of #566 and #567, I am *very* reluctant to potentially repeat the same mistake by upgrading `System.ValueTuple` from 4.3.0 to 4.4.0. Adding an additional `net47` framework target seems a safer choice at this point.

**Comment by kherr9** [comment]
Can use moq 4.8.0, which doesn't have System.ValueTuple dep.
Currently moq 4.8.1 is latest.

**Comment by steelerc** [comment]
I'm still seeing a dep on System.ValueTuple 4.3.0 when installing Moq 4.8.1

**Comment by stakx** [comment]
@steelerc - that's because no work has happened yet to change this.

**Comment by kherr9** [comment]
@steelerc Use 4.8.0

**Comment by stakx** [comment]
@steelerc:

> I'm still seeing a dep on System.ValueTuple 4.3.0 when installing Moq 4.8.1

Once released, a particular version never get changed. 4.8.1 will always have that particular issue.

Expect a fix for 4.8.2 in about 3 or 4 weeks' time. Until then use 4.8.0 like suggested above. ;-)

**Comment by huysentruitw** [comment]
Eagerly waiting for 4.8.2 because of this :)

**Comment by stakx** [comment]
I'll try to resolve this during the weekend ahead.

**Comment by stakx** [comment]
Moq 4.8.2 (see [changelog](https://github.com/moq/moq4/blob/master/CHANGELOG.md#482-2018-02-23)) has just been published [on NuGet](https://www.nuget.org/packages/Moq/4.8.2).

Please report if there's any more trouble with `ValueTuple` and .NET 4.7+.

**Comment by stakx** [comment]
@bdarby22 - Moq 4.10.1 has just become available on Moq. That version no longer has a dependency on System.ValueTuple.
