### ISSUE TITLE
Need a way to setup a property / method by name

### ISSUE THREAD

**Issue by BradleyUffner** [moq/moq4#580]
I'm building a unit test framework to assist with testing code that relies on Entity Framework, and I need a way to setup a callback on a method by name.

The primary function of my project is to dynamically create a mock object that behaves like user's subclass of DbContext.  I have a ContextMockBuilder<T> class, where T is the interface representing the DbContext under test.  I create a Mock of T, then loop through all the properties on T, using reflection, to find all the properties of type DbSet<TEntity> , and populate them with a customized subclass TestDbSet<TEntity>.  This works great, but I need to be able to call custom code for the SaveChanges method.  Unfortunately, DbContext doesn't implement an interface with the SaveChanges method on it, which means I can't constraint T.  That leads to not being able to use Moq's normal methods to setup the callback, since "mock.Setup(foo => ...)" foo will only contains members of System.Object.

I either need some method to setup a method by name, or some other way to do it that doesn't involve a strongly typed Expression.  I thought I would be able to "abuse" Protected, since it allows member access by name, but apparently it throws an error if the member is public (otherwise, I believe it would work).

**Comment by stakx** [comment]
Moq already allows you to do what you want: Most `Setup` and `Verify` methods take an `Expression<>` as their first parameter. You can build such LINQ expression trees at runtime using the static factory methods of the `System.Linq.Expressions.Expression` class (e. g. `Expression.MakeMemberAccess`). Since you're already doing reflection, this should be a fairly small step.

**Comment by BradleyUffner** [comment]
Interesting, I'll see if I can get that working.  Thank you for taking the time help.

**Comment by stakx** [comment]
Good luck. Report back if you get stuck, and I'll try to demo with a brief example.

**Comment by BradleyUffner** [comment]
Success (at least it *seems* to be working)!

            var mock = new Mock<TDbContextInterface>();
            var param = Expression.Parameter(typeof(TDbContextInterface), "i");
            var method = typeof(TDbContextInterface).GetMethod("SaveChanges");
            var exp = Expression.Call(param, method);
            mock.Setup(Expression.Lambda<Action<TDbContextInterface>>(exp,param))
                .Callback(() =>
                {
                    Console.WriteLine("saving changes");
                });

**Comment by stakx** [comment]
@BradleyUffner: That's looking good! (Note that in normal Moq usage, building an `Expression` is usually done at compile-time by the compiler for you, but that is how `Setup` always gets called behind the scenes! Building an expression manually is no magic!)

**Comment by BradleyUffner** [comment]
Just in case anyone else needs this functionality, I made an extension method that seems to handle all the cases I threw at it.

    public static class MockExtensions
    {
        public static ISetup<T> SetupByName<T>(this Mock<T> mock, string methodName, params Expression<Func<object>>[] args) where T : class
        {
            object[] argTypes = args.Select(a => a.Body.NodeType == ExpressionType.Convert ? (object)((UnaryExpression)a.Body).Operand.Type : (object)a.Body.Type).ToArray();
            var param = Expression.Parameter(typeof(T), "i");
            var method = typeof(T).GetMethod(methodName, argTypes.Cast<Type>().ToArray());
            if (method == null) { throw new ArgumentException($"{typeof(T).Name} does not contain a method \"{methodName}({string.Join(",", (object[])argTypes)})\".", nameof(methodName)); }
            var callArgs = args.Select(a => a.Body.NodeType == ExpressionType.Convert ? ((UnaryExpression)a.Body).Operand : a.Body);
            var call = Expression.Call(param, method, callArgs);
            var exp = Expression.Lambda<Action<T>>(call, param);
            return mock.Setup(exp);
        }
    }

It can be used like this (Equivalent of `mock.Setup(i => i.ATestMethod(5, "Test"))`) :

    mock.SetupByName("ATestMethod", () => 5, () => "Test")
        .Callback(() =>
        {
            Debug.WriteLine("ATestMethod was called");
        });

or this (Equivalent of `mock.Setup(i => i.ATestMethod(It.IsAny<int>, It.IsAny<string>))`)
    mock.SetupByName("ATestMethod", () => It.IsAny<int>(), () => It.IsAny<string>())
        .Callback(() =>
        {
            Debug.WriteLine("ATestMethod was called");
        });

I know the format is a little ugly, but it's the best way I could figure out how to make it support both the constant form, and the "It.IsAny" form.

**Comment by stakx** [comment]
@BradleyUffner: First of all, thanks for sharing your work! :+1:

> I know the format is a little ugly, but it's the best way I could figure out how to make it support both the constant form, and the "It.IsAny" form.

Let me point you at Moq's in-built `.Protected()` functionality, which faces the same problem. There, it got solved via `ItExpr.IsAny<T>()`. Basically, the `Setup` method accepts an `object[]` array for arguments. Every value in that array is "lifted" to a `ConstantExpression` except those that are `MethodCallExpression`s referring to the `It.IsAny<T>` static method; those are used verbatim. `ItExpr.IsAny<T>()` is a static factory method producing such an expression.
