### ISSUE TITLE
Not able to moq setup 2 different methods with same input parameters 

### ISSUE THREAD

**Issue by ShashiG88** [moq/moq4#587]
One of my method has 2 DB methods -

 Method1(string a,int? b) and 

Method2(string a, int? b)

I mocked and set up these methods -
            objectMock.Setup(b => b.Method1(It.IsAny<string>(), It.IsAny<int())).Returns(true);
            objectMock.Setup(a => a.Method2(It.IsAny<string>(), It.IsAny<int>())).Returns(true);

and during the test always only one method is getting invoked by mock object and the 2nd method always hits DB.
And when I performed mockObject.verify(..) receiving the exception 
Moq.MockException: '
Expected invocation on the mock at least once, but was never performed: a => a.Method2(It.IsAny<String>(), It.IsAny<Int32>())

**Comment by stakx** [comment]
@ShashiG88, impossivle to say what's going wrong without seeing the actual test code. Could you please post a minimal & complete code example that shows how exactly you're invoking these two methods?

**Comment by ShashiG88** [comment]
I was able to resolve this .. the method which I was mocking had input parameter nullable int, but during mocking I was passing it as int. 
After I change the moccking parameter to same as the method it worked fine...
