### ISSUE TITLE
Intellisense puts red squiggly under wrong method

### ISSUE THREAD

**Issue by Mardoxx** [moq/moq4#604]
### Steps to Reproduce

```cs
    public interface IInterface
    {
        Task<int> GetAsync();
    }

    public class Program
    {
        public void Method()
        {
            var mock = new Mock<IInterface>();
            mock.Setup(x => x.GetAsync())
                .ReturnsAsync("wrongtype");
        }
    }
```

### Expected Behavior
Red squiggly and contextual help under `.ReturnsAsync("wrongtype")`

### Actual Behavior
Red squiggly and contextual help under `mock.Setup(x => x.GetAsync())`

**Comment by Mardoxx** [comment]
Possibly an issue with roslyn, never seen this elsewhere before though.

**Comment by stakx** [comment]
Since this is a problem in Visual Studio, and not with Moq per se, I think it makes more sense to report this either as a Visual Studio bug (or over at the Roslyn repo). I don't think anything can be done at Moq's end to resolve this issue.
