### ISSUE TITLE
"Any" matching for out parameters with .Protected() setups

### ISSUE THREAD

**Issue by iitaiy** [moq/moq4#606]
I tried to setup the following protected virtual method:
```
protected virtual bool DoSomething(out string str)
{
   str = "boo";
   return true;
}
```
I didn't found a way to do it with moq. But when I try to setup with` ItExpr.Ref<string>.IsAny` it worked. Is it the purpose of `ItExpr.Ref` to match also out parameters? Or there is another way to do this?

Full code example:

    [TestClass]
    public class OutProtectedMockFixture
    {
        delegate void DoSomethingCallback(out string str);

        [TestMethod]
        public void test()
        {
            // Arrange
            string str;
            var classUnderTest = new Mock<SomeClass>();
            classUnderTest.Protected().Setup<bool>("DoSomething", ItExpr.Ref<string>.IsAny)
                .Callback(new DoSomethingCallback((out string stri) =>
                    {
                        stri = "test";
                    }));

            // Act
            classUnderTest.Object.foo(out str);

            // Assert
            Assert.AreEqual("test", str);
        }
    }

    public class SomeClass
    {
        public void foo(out string str)
        {
            DoSomething(out str);
        }

        protected virtual bool DoSomething(out string str)
        {
            str = "boo";
            return true;
        }
    }

Thank you for the help.

**Comment by stakx** [comment]
Yes, you can use `ItExpr.Ref<T>.IsAny` with `out` parameters. And no, there is no alternative.

The way how Moq handles `out` parameters might be somewhat counterintuitive. C# does not allow a method to read their `out` parameters' values before they have been assigned&mdash;that is, `out` parameters don't provide an input value. Therefore they don't need to be matched at all. However, Moq *will* read any `out` parameter's value at the time when a method call is set up, and it will set up an expectation for the method call that the method should assign those values to the parameters.

What `ItExpr.Ref<T>.IsAny` essentially does with `out` parameters is to tell the setup, "Don't set up an expectation for this `out` parameter's post-call value. I don't care what value the method will assign to it."

**Comment by stakx** [comment]
P.S.: In restrospect, I am not sure why I wrote some of the things I wrote above. Yes, Moq *does* read the value of `out` parameters when a method is setup. But as far as I am aware today, it doesn't set up an *expectation*&mdash;it simply sets up the method to return that same value via the `out` parameter for future calls.
