### ISSUE TITLE
WindsorContainer UsingFactoryMethod broken on upgrade to 4.8.0+

### ISSUE THREAD

**Issue by Jevonius** [moq/moq4#608]
Hi,

I'm in the process of updating Nuget packages in our solution and have come across a problem updating to newer versions of Moq (4.8.0+). For background, we were running on 4.7.99 and jumped to 4.8.2, but I've narrowed the issue down to the move from 4.7.145 -> 4.8.0.

Code such as the following:
``` C#
using Castle.Core.Logging;
using Castle.MicroKernel.Registration;
using Castle.Windsor;
using Moq;
...
	var container = new WindsorContainer();
	container.Register(Component.For<ILogger>().UsingFactoryMethod(() => new Mock<ILogger>().Object));
	var logger = container.Resolve<ILogger>();
```
Generates the exception:
```
System.NotSupportedException: Can not apply commission concerns to component Late bound Castle.Core.Logging.ILogger because it appears to be a target-less proxy. Currently those are not supported.
```

I've dug into the Castle and Moq source as much as I can, but it's a bit beyond me without spending significantly more time on it. The exception is being thrown in `Castle.MicroKernel.ComponentActivator.AbstractComponentActivator.ApplyCommissionConcerns`.

There are a couple of ways I can work around the issue - change the registration to `.Instance(new Mock<ILogger>().Object)` for example, or use the `UsingFactoryMethod` overload and setting `managedExternally` to true, but the first potentially causes slightly different behaviour to our 'real' code, and I don't fully understand the impact of the second - plus it means finding and remembering to do this everywhere we want to use a Mock object in this way.

I'm not entirely sure which change caused this behaviour - I thought at first it was related to #476 but the issue doesn't exist in v4.8.0-rc1, so #550 seems like a more likely candidate.

**Comment by stakx** [comment]
Oh btw. I think you can emulate what previous versions of Moq did by changing your code to this:

```csharp
UsingFactoryMethod(() => new Mock<object>().As<ILogger>().Object));
```

In theory this should make your code work with Moq 4.8.x, if it worked with Moq 4.7.x.

**Comment by Jevonius** [comment]
I suspect you're probably right about the issue being related to #551 - the exception being thrown does sound closely tied to `CreateInterfaceProxyWithoutTarget`. I took it as a Moq issue as it broke while with the same version of Castle components, but I agree it is more of an issue with Castle - odd/frustrating that they allow you to create an object in DynamicProxy that you can't then use properly in Windsor!

I'll discuss with my team whether we settle on one of the workarounds (your suggestion works, thank you), stick with 4.7.145, or give 5 a test - will keep an eye out for that either way.

Thanks!
