### ISSUE TITLE
Return default value for not implemented methods for As<> method

### ISSUE THREAD

**Issue by pluginbb** [moq/moq4#609]
Hello!

I'm trying to create mock for `IServiceInterface` with implementations for several methods. 
Hovewer my `DefaultImplementationClass` not implemented all methods from `IServiceInterface`, so when I call methods that don't exists in `DefaultImplementationClass` program throws exception like:

**_System.NotImplementedException: This is a DynamicProxy2 error: The interceptor attempted to 'Proceed' for method 'MethodThatNotExistsInDefaultImplementationClass(Int64)' which has no target. When calling method without target there is no implementation to 'proceed' to and it is the responsibility of the interceptor to mimic the implementation (set return value, out arguments etc)_**

Example of my code:

```csharp
var mock = new Mock<DefaultImplementationClass>().As<IServiceInterface>();
mock.Callbase = true;

mock.Object.MethodThatExistsInDefaultImplementationClass(); // all good, calling real implementation
mock.Object.MethodThatNotExistsInDefaultImplementationClass(); // throws exception
```

So the question, can I somehow make it so that it simply returns the default value, 
not to throw exception in this case?
thanks in advance

**Comment by stakx** [comment]
Hi @pluginbb, could you please post minimal & self-contained reproduction code so we can take a closer look at this?

**Comment by pluginbb** [comment]
@stakx 
sorry, when I tried to reproduce this error, I created a new project with latest version of Moq, and everything worked out! I though that I have updated Moq to latest version in my real project, my mistake =( 
Now everything is works, thank you very much!
