### ISSUE TITLE
Moq 4.2 documentation

### ISSUE THREAD

**Issue by IvanRibakov** [moq/moq4#612]
Nuget.org is hosting [4.2 version of Moq](https://www.nuget.org/packages/Moq/4.2.1510.2205) which I'm forced to use due to my project's code base being targeted for .Net 3.5. 

Unfortunately, current documentation found on https://github.com/Moq/moq4/wiki doesn't seem to apply to Moq v4.2 as I'm unable to find `Setup()` method on Mock object. Any ideas where could I find relevant documentation?

**Comment by IvanRibakov** [comment]
I'm able to find documentation in general. I'm just not sure it's the right one. As I mentioned originally, Mock object doesn't have `Setup()` method available in my case so I'm guessing Moq v4.2 is using some other API (which?).

![image](https://user-images.githubusercontent.com/3639958/38460524-da14fd88-3abb-11e8-8676-68aed460a335.png)

**Comment by stakx** [comment]
> [...] as I'm unable to find `Setup()` method on Mock object.

> Mock object doesn't have `Setup()` method available

If you are really using Moq 4.2.1510.2205 as you claimed above, then there should definitely be a `Setup` method group on `Mock<T>` (I just verified it, `Setup` is definitely there):

https://github.com/moq/moq4/blob/v4.2.1510.2205/Source/Mock.Generic.cs#L253-L314

Perhaps your editor's code completion is malfunctioning.
