### ISSUE TITLE
Write exact values into exception messages

### ISSUE THREAD

**Issue by pinki** [moq/moq4#636]
I had this exception:

> Moq.MockException: 
Expected invocation on the mock exactly 22 times, but was 21 times: p => p.Report(It.IsInRange<Double>(0, 1, Range.Inclusive))
\
Configured setups: 
p => p.Report(It.IsInRange<Double>(0, 1, Range.Inclusive))
\
Performed invocations: 
IProgress\`1.Report(0)
IProgress\`1.Report(0,05)
IProgress\`1.Report(0,1)
IProgress\`1.Report(0,15)
IProgress\`1.Report(0,2)
IProgress\`1.Report(0,25)
IProgress\`1.Report(0,3)
IProgress\`1.Report(0,35)
IProgress\`1.Report(0,4)
IProgress\`1.Report(0,45)
IProgress\`1.Report(0,5)
IProgress\`1.Report(0,55)
IProgress\`1.Report(0,6)
IProgress\`1.Report(0,65)
IProgress\`1.Report(0,7)
IProgress\`1.Report(0,75)
IProgress\`1.Report(0,8)
IProgress\`1.Report(0,85)
IProgress\`1.Report(0,9)
IProgress\`1.Report(0,95)
IProgress\`1.Report(1)
IProgress\`1.Report(1)

I was wondering why the validation didn't pass.
It turned out, that the first `1` was `1.000[...]2`.

It took me a long time to find that out.
If the exact value was inside the exception message, it would have saved me much time.

**Comment by stakx** [comment]
AFAIK Moq doesn't have any special logic for rounding floating point numbers, it just performs a regular `.ToString()` on the arguments. Not sure what can be done about this. Suggestions?

**Comment by stakx** [comment]
This will be "fixed" in the next release of Moq (version > 4.8.3).

The "fix" consists of using round-tripping when formatting floating point values for inclusion in diagnostic messages. The Visual Studio IDE does the same for floats in e.g. the Watch window, so it seemed like a reasonable change to do the same in Moq.
