### ISSUE TITLE
Allow setting up async methods easily

### ISSUE THREAD

**Issue by jdom** [moq/moq4#64]
It would be nice to have better usability for methods that return Task.

For example, an option for doing something like:

myMock.Setup(x => x.ReadAsync()).ThrowsAsync(new Exception());

which should return a faulted task with that exception.

Also, for methods that return Task that are not explicitly set up, it would be good that instead of defaulting to return a null Task, that they return a completed Task (or completed Task<T>) instead.

Didn't consider the best way to address this yet, but currently it can be a little cumbersome especially when mocking code where >70% of its methods are async.

**Comment by stakx** [comment]
Closing this issue since all that it asked for has been implemented since.
