### ISSUE TITLE
License update to project

### ISSUE THREAD

**Issue by retslig** [moq/moq4#669]
I was hoping the project owner would consider updating the project license to use spdx identifier for the "BSD license" license. Your license in the github api only shows as "Other".
See https://api.github.com/repos/moq/moq4/license for your current license.
Also note your current license committed in the repo is already "[This is the BSD license, see
 http://opensource.org/licenses/BSD-3-Clause]" https://raw.githubusercontent.com/moq/moq4/master/License.txt
This is no change to the license at all, but then allows anyone using the github license API to get an exact match of the licensed used and not have to use any string magic to come up with your license.

If your unfamiliar with SPDX see spdx.org.

Pretty sure this can be done in your settings somewhere. Here is an example of your API json and your
spdx_id is null.
{
"name": "License.txt",
"path": "License.txt",
"sha": "c284be82c2f6c82cce6a1b182311b3b7be308dd7",
"size": 1735,
"url": "https://api.github.com/repos/moq/moq4/contents/License.txt?ref=master",
"html_url": "https://github.com/moq/moq4/blob/master/License.txt",
"git_url": "https://api.github.com/repos/moq/moq4/git/blobs/c284be82c2f6c82cce6a1b182311b3b7be308dd7",
"download_url": "https://raw.githubusercontent.com/moq/moq4/master/License.txt",
"type": "file",
"content": "Q29weXJpZ2h0IChjKSAyMDA3LiBDbGFyaXVzIENvbnN1bHRpbmcsIE1hbmFz\nIFRlY2hub2xvZ3kgU29sdXRpb25zLCBJblNURURECmh0dHA6Ly93d3cubW9x\ndGhpcy5jb20vCkFsbCByaWdodHMgcmVzZXJ2ZWQuCgpSZWRpc3RyaWJ1dGlv\nbiBhbmQgdXNlIGluIHNvdXJjZSBhbmQgYmluYXJ5IGZvcm1zLCAKd2l0aCBv\nciB3aXRob3V0IG1vZGlmaWNhdGlvbiwgYXJlIHBlcm1pdHRlZCBwcm92aWRl\nZCAKdGhhdCB0aGUgZm9sbG93aW5nIGNvbmRpdGlvbnMgYXJlIG1ldDoKCiAg\nICAqIFJlZGlzdHJpYnV0aW9ucyBvZiBzb3VyY2UgY29kZSBtdXN0IHJldGFp\nbiB0aGUgCiAgICBhYm92ZSBjb3B5cmlnaHQgbm90aWNlLCB0aGlzIGxpc3Qg\nb2YgY29uZGl0aW9ucyBhbmQgCiAgICB0aGUgZm9sbG93aW5nIGRpc2NsYWlt\nZXIuCiAgICAKICAgICogUmVkaXN0cmlidXRpb25zIGluIGJpbmFyeSBmb3Jt\nIG11c3QgcmVwcm9kdWNlIAogICAgdGhlIGFib3ZlIGNvcHlyaWdodCBub3Rp\nY2UsIHRoaXMgbGlzdCBvZiBjb25kaXRpb25zIAogICAgYW5kIHRoZSBmb2xs\nb3dpbmcgZGlzY2xhaW1lciBpbiB0aGUgZG9jdW1lbnRhdGlvbiAKICAgIGFu\nZC9vciBvdGhlciBtYXRlcmlhbHMgcHJvdmlkZWQgd2l0aCB0aGUgZGlzdHJp\nYnV0aW9uLgogICAgCiAgICAqIE5laXRoZXIgdGhlIG5hbWUgb2YgQ2xhcml1\ncyBDb25zdWx0aW5nLCBNYW5hcyBUZWNobm9sb2d5IFNvbHV0aW9ucyBvciBJ\nblNURUREIG5vciB0aGUgCiAgICBuYW1lcyBvZiBpdHMgY29udHJpYnV0b3Jz\nIG1heSBiZSB1c2VkIHRvIGVuZG9yc2UgCiAgICBvciBwcm9tb3RlIHByb2R1\nY3RzIGRlcml2ZWQgZnJvbSB0aGlzIHNvZnR3YXJlIAogICAgd2l0aG91dCBz\ncGVjaWZpYyBwcmlvciB3cml0dGVuIHBlcm1pc3Npb24uCgpUSElTIFNPRlRX\nQVJFIElTIFBST1ZJREVEIEJZIFRIRSBDT1BZUklHSFQgSE9MREVSUyBBTkQg\nCkNPTlRSSUJVVE9SUyAiQVMgSVMiIEFORCBBTlkgRVhQUkVTUyBPUiBJTVBM\nSUVEIFdBUlJBTlRJRVMsIApJTkNMVURJTkcsIEJVVCBOT1QgTElNSVRFRCBU\nTywgVEhFIElNUExJRUQgV0FSUkFOVElFUyBPRiAKTUVSQ0hBTlRBQklMSVRZ\nIEFORCBGSVRORVNTIEZPUiBBIFBBUlRJQ1VMQVIgUFVSUE9TRSBBUkUgCkRJ\nU0NMQUlNRUQuIElOIE5PIEVWRU5UIFNIQUxMIFRIRSBDT1BZUklHSFQgT1dO\nRVIgT1IgCkNPTlRSSUJVVE9SUyBCRSBMSUFCTEUgRk9SIEFOWSBESVJFQ1Qs\nIElORElSRUNULCBJTkNJREVOVEFMLCAKU1BFQ0lBTCwgRVhFTVBMQVJZLCBP\nUiBDT05TRVFVRU5USUFMIERBTUFHRVMgKElOQ0xVRElORywgCkJVVCBOT1Qg\nTElNSVRFRCBUTywgUFJPQ1VSRU1FTlQgT0YgU1VCU1RJVFVURSBHT09EUyBP\nUiAKU0VSVklDRVM7IExPU1MgT0YgVVNFLCBEQVRBLCBPUiBQUk9GSVRTOyBP\nUiBCVVNJTkVTUyAKSU5URVJSVVBUSU9OKSBIT1dFVkVSIENBVVNFRCBBTkQg\nT04gQU5ZIFRIRU9SWSBPRiBMSUFCSUxJVFksIApXSEVUSEVSIElOIENPTlRS\nQUNULCBTVFJJQ1QgTElBQklMSVRZLCBPUiBUT1JUIChJTkNMVURJTkcgCk5F\nR0xJR0VOQ0UgT1IgT1RIRVJXSVNFKSBBUklTSU5HIElOIEFOWSBXQVkgT1VU\nIE9GIFRIRSBVU0UgCk9GIFRISVMgU09GVFdBUkUsIEVWRU4gSUYgQURWSVNF\nRCBPRiBUSEUgUE9TU0lCSUxJVFkgT0YgClNVQ0ggREFNQUdFLgoKW1RoaXMg\naXMgdGhlIEJTRCBsaWNlbnNlLCBzZWUKIGh0dHA6Ly9vcGVuc291cmNlLm9y\nZy9saWNlbnNlcy9CU0QtMy1DbGF1c2VdCg==\n",
"encoding": "base64",
"_links": {
"self": "https://api.github.com/repos/moq/moq4/contents/License.txt?ref=master",
"git": "https://api.github.com/repos/moq/moq4/git/blobs/c284be82c2f6c82cce6a1b182311b3b7be308dd7",
"html": "https://github.com/moq/moq4/blob/master/License.txt"
},
"license": {
"key": "other",
"name": "Other",
"spdx_id": null,
"url": null,
"node_id": "MDc6TGljZW5zZTA="
}
}

**Comment by retslig** [comment]
This is done by updating you License.txt file to match Githubs known list licenses.
See here for exact details of how the license API works.  https://developer.github.com/v3/licenses/
Brief snippet: 

> The Licenses API uses the open source Ruby Gem Licensee to attempt to identify the project's license. Licensee matches the contents of a project's LICENSE file (if it exists) against a short list of known licenses. As a result, the API does not take into account the licenses of project dependencies or other means of documenting a project's license such as references to the license name in the documentation.
If a license is matched, the license key and name returned conforms to the SPDX specification.

Another article that explains this well. https://blog.github.com/2016-09-21-license-now-displayed-on-repository-overview/

I tested this on one of my own repos and this did indeed work.
Only concern I have is that your license is in the known list.

**Comment by stakx** [comment]
What actual change to the license file do you suggest?

**Comment by retslig** [comment]
I think if you added the spdx identifier for BSD 3 ("BSD-3-Clause") or even some text at the end with name ("BSD 3-Clause \"New\" or \"Revised\" License") to your license file this would then fix the API. 

If that doesnt work then here is the instructions given by api giuthub...   
https://api.github.com/licenses/bsd-3-clause

> Create a text file (typically named LICENSE or LICENSE.txt) in the root of your source code and copy the text of the license into the file. Replace [year] with the current year and [fullname] with the name (or names) of the copyright holders. Replace [project] with the project organization, if any, that sponsors this work.
