### ISSUE TITLE
Cannot set callback on function call that uses default parameter

### ISSUE THREAD

**Issue by Custodia** [moq/moq4#689]
If you setup a callback on a function with a default parameter and then call the function without overriding the default parameter the callback function supplied to Moqs .Callback will never be called.

**Comment by stakx** [comment]
```csharp
public interface IFoo
{
    void Do(int arg = 42);
}

void Callback_invoked_if_mocked_method_called_without_explicit_value_for_default_parameter()
{
    var mock = new Mock<IFoo>();
    bool callbackInvoked = false;
    mock.Setup(m => m.Do(It.IsAny<int>())).Callback(() => callbackInvoked = true);

    mock.Object.Do();

    Assert.True(callbackInvoked);
}
```

This test appears to do what you've described, yet it passes just fine.

Can you post a brief failing test that demonstrates the issue you're describing?

**Comment by Custodia** [comment]
I'll look at this again on Monday.

**Comment by Custodia** [comment]
The issue was fixed by replacing a call to a factory method from `.Returns(publisherMock.Object)` to `.Returns(() => publisherMock.Object)` so this is unrelated to what I originally thought it was.

That being said I think it's confusing behaviour that the property isn't actually a property but actually generates a new instance of the mock object. I think it would make way more intuitive sense if this was a function like `publisherMock.GetObject()`
