### ISSUE TITLE
Mocking indexer captures It.IsAny() as the value, even if given in the indexer argument

### ISSUE THREAD

**Issue by idigra** [moq/moq4#696]
Following code mocks the indexer and followed by two calls to the indexer. I would expect Moq to capture the first call (mock.Object[10] = 8) but the second is captured (mock.Object[0] = 17;):

			int x = default(int);
			int result = default(int);

			var mock = new Mock<IFoo>();
			mock.SetupSet(f => f[It.IsAny<int>()] = 8)
				.Callback(new Action<int, int>((x_, result_) =>
				{
					x = x_;
					result = result_;
				}));

			mock.Object[10] = 8;
			mock.Object[0] = 17;
			Assert.Equal(10, x);
			Assert.Equal(8, result);

It's caused because the limitation of the non-deprecated overload of SetupSet which accepts an Action instead of Expression, thus cannot really know when It.IsAny really called. Following code in src\Moq\Mock.cs assumes always that it was the value (rather than the index):

					// If the value matcher is not equal to the property 
					// type (i.e. prop is int?, but you use It.IsAny<int>())
					// add a cast.
					if (last.Match.RenderExpression.Type != propertyType)
					{
						values[valueIndex] = Expression.Convert(last.Match.RenderExpression, propertyType);
					}
					else
					{
						values[valueIndex] = last.Match.RenderExpression;
					}

					matchers[valueIndex] = new MatchExpression(last.Match);

					if (arguments.Length == 2)
					{
						// TODO: what about multi-index setters?
						// Add the index value for the property indexer
						values[0] = GetValueExpression(arguments[0], parameters[0].ParameterType);
						// TODO: No matcher supported now for the index
						matchers[0] = values[0];
					}

					var lambda = Expression.Lambda(
						typeof(Action<>).MakeGenericType(x.Type),
						Expression.Call(x, last.Invocation.Method, values),
						x);

					return callFactory(last.Mock, lambda, last.Invocation.Method, matchers);

Suggestions for solution:
- de-deprecate the SetupSet overload which accepts two arguments to allow mocking indexer with Expressions.
- Inject in It.IsAny() some magic number and later check where those numbers were injected (that's a real challenge to do this because It.IsAny is generic, thus not always have ints in it. I would suggest using some Interops or unsafe code to get garbage injected in it). Also, to double check that the user didn't use exactly same value as constant, run the given delegate twice with different magic number injected in It.IsAny. Also check that other value remains deterministic and that the count of It.IsAny calls matches the resulting any arguments.

**Comment by stakx** [comment]
As you correctly noted in the PR, this is duplicate. Thank you nevertheless for posting some suggestions on how to possibly resolve it. I'm a little pressed for time at the moment, some quick thoughts:

> de-deprecate the SetupSet overload

This would be the easiest solution, but it might be confusing for users to deprecate a method, then bring it back, then see it gone again in Moq v5. Because Moq v5 does proxy generation at design/compile time, it won't suffer from the issue present in Moq v4 so it can deprecate the old `SetupSet` without any negative effects. For this reason it would be more strategic to *not* bring back the deprecated method at this time.

> Inject in It.IsAny() some magic number [...]

That's a good thought worth following up. Apart from the limitations you already mentioned, I suspect it won't be able to solve the main problem (which is that if there are less matchers than places where they could appear, you don't know in which places they were originally). Noting down some random or sequential number in `Matcher.Create` is likely only going to help you determine the relative ordering of matcher invocations, not the exact place in an expression where they were used.

**Comment by MaMazav** [comment]
> you don't know in which places they were originally

I think that my solution does solves this problem. If you approve that its an acceptible solution (no other problems in it), I will publish another iteration in the referenced PR so you can decide if Im correct.

**Comment by idigra** [comment]
> you don't know in which places they were originally
I think that my solution does solve that problem. If you approve that this solution has no other problems than that, I'll publish another iteration in the referenced PR along with unit tests so you can investigate the solution.

**Comment by stakx** [comment]
> Inject in It.IsAny() some magic number and later check where those numbers were injected (that's a real challenge to do this because It.IsAny is generic [...]

As a small improvement to the current workings of `SetupSetImpl`, we could do something like this:

* If only one matcher was used, assign it to the last (`value`) parameter. This is to stay compatible with how Moq has worked up until now.

* If more than one matcher was used, assign the last one to the `value` parameter (as above) and assign the others starting with the left-most parameter. Only assign matchers to places where the argument has a `default(TArg)` value. (This last bit means we don't have to generate random values for arbitrary types, at the cost of possible mixups of matchers with types' default values. We could optionally make this less likely for for the most commonly used types by letting matchers return a randomly chosen "magic" value like you suggested, and only compare against `default(TArg)` for those types where we cannot produce a random value.)

**Comment by idigra** [comment]
Seen your comments, I don't care to break the PR into `NullReferenceException` fix, `SetupSet` improvements and testing.

> If only one matcher was used, assign it to the last (value) parameter. This is to stay compatible with how Moq has worked up until now.

This is one of the few examples that I would say that backward compatibility is not desired. That's too clear bug, that even if someone has written `obj[It.IsAny()] = 5;` he won't want it to continue passing. Even more, I think that if anyone has written such statement he already saw that undesired effects happen and already changed his test (after searching and finding this documented issue). What do you think?

> We could optionally make this less likely for for the most commonly used types

I thought about that and agree that we should avoid arbitrary types solution like I suggested above (even if I'll succeed injecting random values, it might have instability effects e.g. when GC tries to collect this random value which he considers to be a valid reference). We can think about an API which allows injecting random values (e.g. `Moq.RandomGenerator<MyType>.Generator = new Func<MyType>(() => new MyType(myRandom.Next()));`). However, if we do that, we can also just provide an API to set an It.IsAny placeholder... (e.g. `Moq.IsAnyPlaceholder<MyType>.Placeholder = new MyType(0);`).
I suggest to do the random generator I suggested below as internal design only (so we can set ints, longs, and interfaces we dynamically build class for), and the placeholder as external API. Then the full logic will be:

- For any argument: If has random generator and no placeholder set, set It.IsAny to return random value.
- Execute delegate.
- If some random generator was missing on first stage above: If single It.IsAny called - do old logic and exit. If It.IsAny calls count equals to argument count + 1, then set IsAny matchers for all arguments and set value and exit. Otherwise - throw unsupported exception with instruction to set RandomGenerator.
- Use placeholders to discover It.IsAnyMatchers.
- If random generator used on the first stage above (rather than only placeholders): Set It.IsAny to return another random value, execute delegate again, and compare two executions to resolve It.IsAny arguments.
- Now we know all It.IsAny calls, finalize mocking and exit.

**Comment by stakx** [comment]
@idigra, apologies for not yet having replied to your above post. It's not forgotten.

In fact, I've been spending some time on refactoring `FluentMockContext` (see #722) so it would allow us to get at all matchers used with a mock invocation (which would be the prerequisite for the above scheme).

I'll try to reply to the actual points you made above as soon as possible. Thanks for being patient!

**Comment by stakx** [comment]
@idigra - I've been busy for the past 10 days or so rewriting portions of Moq that deal with `SetupSet`, `VerifySet`, and argument matchers. So this issue is finally fixed in the upcoming version 4.11.0.

>> If only one matcher was used, assign it to the last (value) parameter. This is to stay compatible with how Moq has worked up until now.
>
> This is one of the few examples that I would say that backward compatibility is not desired. 

I've come to agree with you. The single/last matcher and last parameter don't have any special meaning now, matchers are simply distributed over null/zero "holes" from left to right.
