### ISSUE TITLE
NuDoq API documentation is down

### ISSUE THREAD

**Issue by jonschoning** [moq/moq4#701]
NOTICE: NuDoq domain name expired on 9/25/2018 and is pending renewal or deletion.

**Comment by stakx** [comment]
NuDoq has seen very little love for the past two years or so. I'm pretty sure the project was abandoned long ago. See also #354 and moq/moq#1, seems @kzu has been thinking about a new documentation website.

**Comment by stakx** [comment]
@jonschoning: I won't be around for the next few days, but if you have some spare time and if you are willing to contribute, I think it would be great to remove references to NuDoq from this repository. (No point in linking to a resource that's long gone stale, and is now even gone.) Likely places for such references are the Wiki start page, and probably the README, too.

Please, feel free to edit the Wiki page or send PRs to that effect.

**Comment by kzu** [comment]
Domain renewed. Would love to revamp it on top of docfx or something like that

**Comment by stakx** [comment]
Good to hear. In that case let's keep the links to NuDoq a little longer. :)
