### ISSUE TITLE
`CallBase` should not be allowed for delegate mocks

### ISSUE THREAD

**Issue by stakx** [moq/moq4#706]
### Reproduction code:

```csharp
var mock = new Mock<Action>();
mock.Setup(m => m()).CallBase();
mock.Object.Invoke();
```

### Actual behavior:

`mock.Object.Invoke()` throws a `NotImplementedException` with message:

```
This is a DynamicProxy2 error: The interceptor attempted to 'Proceed' for method 'Void Invoke()' which has no target. When calling method without target there is no implementation to 'proceed' to and it is the responsibility of the interceptor to mimic the implementation (set return value, out arguments etc)
```

### Expected behavior:

The call to `.CallBase()` should throw a `NotSupportedException` with a message explaining that `CallBase` cannot be used with delegate mocks.

The same should happen when setting a delegate mock's `CallBase` property to `true`.

**Comment by tehmantra** [comment]
Hey, created PR #708

**Comment by stakx** [comment]
@tehmantra, thank you for picking this one up! :+1: I've posted a review on your PR.

**Comment by Veikedo** [comment]
It looks like something is wrong with this issue.

I have this code

    [Theory]
    [AutoMoqData]
    internal async Task GetAutomationStatistics_should_return_correct_statistics(
      [Frozen] Mock<GetAutomationsLogTotalCount> getAutomationsLogTotalCount,
      [Frozen] GetCurrentlyRunningSchedulesResult getCurrentlyRunningSchedulesResult,
      [Frozen] GetAutomationsTotalCountResult getAutomationsTotalCountResult,
      GetAutomationStatisticsQuery query,
      GetAutomationStatisticsHandler sut,
      CancellationToken ct
    )
    {
      getAutomationsLogTotalCount
        .Setup(_ => _(It.IsAny<GetAutomationsLogTotalCountQuery>(), ct))
        .ReturnsAsync((GetAutomationsLogTotalCountQuery x, CancellationToken _) =>
          new GetAutomationsLogTotalCountResult
          {
            TotalCount = (long) x.LogLevel.GetValueOrDefault()
          }
        );

      var expectedResult = new GetAutomationStatisticsResult
      {
        AutomationsRunningNow = await getCurrentlyRunningSchedulesResult.Items.LongCount(ct),
        TotalAutomations = getAutomationsTotalCountResult.TotalCount,
        ErrorsReported = (long) EapLogLevel.Error,
        WarningsReported = (long) EapLogLevel.Warn,
      };

      var result = await sut.Handle(query, ct);

      result.Should().BeEquivalentTo(expectedResult);
    }

Where `GetAutomationsLogTotalCount` is a delegate. And I got the exception

```
AutoFixture.ObjectCreationExceptionWithPath : AutoFixture was unable to create an instance from Moq.Mock`1[AutomationsWeb.Features.Statistics.GetAutomationsLogTotalCount] because creation unexpectedly failed with exception. Please refer to the inner exception to investigate the root cause of the failure.

Request path:
	Moq.Mock`1[AutomationsWeb.Features.Statistics.GetAutomationsLogTotalCount] getAutomationsLogTotalCount
	  Moq.Mock`1[AutomationsWeb.Features.Statistics.GetAutomationsLogTotalCount]

Inner exception messages:
	System.NotSupportedException: CallBase cannot be used with Delegate mocks.
```

But I do not call `CallBase` method.

**Comment by zvirja** [comment]
@Veikedo Notice, it has been fixed in AutoFixture. Please update to a new version (it will be published soon) to get a fix 😉
