### ISSUE TITLE
ArgumentOutOfRangeException when setup expression contains indexer access

### ISSUE THREAD

**Issue by mosentok** [moq/moq4#714]
I'm getting an ArgumentOutOfRangeException when my Setup expression contains accessing an object in an array at an index.

```
_Helper.Setup(s => s.Parse(containers[i]));
```

This can be remedied by first accessing the object at the index.

```
var currentContainer = containers[i];
_Helper.Setup(s => s.Parse(currentContainer));
```

If this is intended behavior, could Moq be enhanced to detect this type of expression and throw an exception with a helpful message? This would add value in troubleshooting these expressions.

Below is some code to reproduce the exception and the result stack trace.

```
public class Container
{
    public int MyProperty { get; set; }
}
public interface IHelper
{
    void Parse(Container container);
}
public class Parser
{
    IHelper _Helper;
    public Parser(IHelper helper)
    {
        _Helper = helper;
    }
    public void Parse(List<Container> containers)
    {
        foreach (var container in containers)
            _Helper.Parse(container);
    }
}
[TestFixture]
public class HelperTests
{
    Mock<IHelper> _Helper;
    Parser _Parser;
    [SetUp]
    public void SetUp()
    {
        _Helper = new Mock<IHelper>();
        _Parser = new Parser(_Helper.Object);
    }
    [Test]
    public void Parse()
    {
        var containers = new List<Container> { new Container() };
        for (var i = 0; i < containers.Count; i++)
            _Helper.Setup(s => s.Parse(containers[i]));
        _Parser.Parse(containers);
    }
}
```

```
Result StackTrace:	
at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at Moq.Evaluator.SubtreeEvaluator.Evaluate(Expression e) in C:\projects\moq4\src\Moq\Evaluator.cs:line 73
   at Moq.Matchers.LazyEvalMatcher.Matches(Object value) in C:\projects\moq4\src\Moq\Matchers\LazyEvalMatcher.cs:line 20
   at Moq.InvocationShape.IsMatch(Invocation invocation) in C:\projects\moq4\src\Moq\InvocationShape.cs:line 52
   at Moq.SetupCollection.FindMatchFor(Invocation invocation) in C:\projects\moq4\src\Moq\SetupCollection.cs:line 63
   at Moq.FindAndExecuteMatchingSetup.Handle(Invocation invocation, Mock mock) in C:\projects\moq4\src\Moq\Interception\InterceptionAspects.cs:line 117
   at Moq.Mock.Moq.IInterceptor.Intercept(Invocation invocation) in C:\projects\moq4\src\Moq\Interception\Mock.cs:line 21
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at UnitTests.Parser.Parse(List`1 containers) in REDACTED
   at UnitTests.HelperTests.Parse() in REDACTED
--ArgumentOutOfRangeException
   at lambda_method(Closure )
Result Message:	
System.Reflection.TargetInvocationException : Exception has been thrown by the target of an invocation.
  ----> System.ArgumentOutOfRangeException : Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
```

**Comment by stakx** [comment]
```
var containers = new List<Container> { new Container() };
        for (var i = 0; i < containers.Count; i++)
        {
            _Helper.Setup(s => s.Parse(containers[i]));
        _Parser.Parse(containers);
```

**Comment by stakx** [comment]
Interestingly, this is the second issue we've recently got that is related to how Moq evaluates parameters in a setup expression (see https://github.com/moq/moq4/issues/711#issuecomment-433616626 for that other one).

What's apparently happening in your case is that the `containers[i]` part of your setup expression is not evaluated eagerly, but lazily. That is, it only gets evaluated when you invoke the setup&mdash;and by that time, we're beyond the `for` loop so `i == containers.Count`, and thus the `IndexOutOfRangeException`.

Try applying the following change and see the exception go away:

```diff
     [Test]
     public void Parse()
     {
         var containers = new List<Container> { new Container() };
         for (var i = 0; i < containers.Count; i++)
+        {
+            var j = i;
-            _Helper.Setup(s => s.Parse(containers[i]));
+            _Helper.Setup(s => s.Parse(containers[j]));
+        }
         _Parser.Parse(containers);
     }
```

I vaguely remember the VB.NET compiler warning about closing over the iteration variable of a `for` loop. Such a warning here would've come in handy here.

Right now, I am not sure whether this should count as a bug, or whether it's simply a user mistake. Will need to take a closer look.

**Comment by stakx** [comment]
> I will need to take a closer look and see whether switching over to eager evaluation would be a breaking change for other scenarios.

I think we might be able to solve this issue without too much of a breaking change by changing which expressions `MatcherFactory` evaluates eagerly, and for which ones it creates a `LazyEvalMatcher`.

Currently, Moq evaluates `MemberExpression`s (i.e. property accesses) eagerly. It evaluates `MethodCallExpression`s lazily (except for argument matchers like `It.IsAny`). What it doesn't consider at all is `IndexExpression`s (which conceptually tend towards the `MemberExpression` side). What it currently also doesn't deal with is accessor method (regardless of whether they belong to a property or to an indexer) encoded directly as `MethodCallExpression`s... those should be treated like `MemberExpression` / `IndexExpression`.

I'll look at submitting a PR to make the current logic of `MatcherFactory` a little more consistent. The rule of thumb for users will then be:

* Property and indexer accesses are evaluated greedily.
* Everything else is evaluated lazily.
