### ISSUE TITLE
CallBase cannot be used with Delegate mocks

### ISSUE THREAD

**Issue by Veikedo** [moq/moq4#731]
First of all, I don't call `CallBase` method explicitly. 

I have this code

    [Theory]
    [AutoMoqData]
    internal async Task GetAutomationStatistics_should_return_correct_statistics(
      [Frozen] Mock<GetAutomationsLogTotalCount> getAutomationsLogTotalCount,
      [Frozen] GetCurrentlyRunningSchedulesResult getCurrentlyRunningSchedulesResult,
      [Frozen] GetAutomationsTotalCountResult getAutomationsTotalCountResult,
      GetAutomationStatisticsQuery query,
      GetAutomationStatisticsHandler sut,
      CancellationToken ct
    )
    {
      getAutomationsLogTotalCount
        .Setup(_ => _(It.IsAny<GetAutomationsLogTotalCountQuery>(), ct))
        .ReturnsAsync((GetAutomationsLogTotalCountQuery x, CancellationToken _) =>
          new GetAutomationsLogTotalCountResult
          {
            TotalCount = (long) x.LogLevel.GetValueOrDefault()
          }
        );

      var expectedResult = new GetAutomationStatisticsResult
      {
        AutomationsRunningNow = await getCurrentlyRunningSchedulesResult.Items.LongCount(ct),
        TotalAutomations = getAutomationsTotalCountResult.TotalCount,
        ErrorsReported = (long) EapLogLevel.Error,
        WarningsReported = (long) EapLogLevel.Warn,
      };

      var result = await sut.Handle(query, ct);

      result.Should().BeEquivalentTo(expectedResult);
    }

Where `GetAutomationsLogTotalCount` is a delegate. And I got the exception

```
AutoFixture.ObjectCreationExceptionWithPath : AutoFixture was unable to create an instance from Moq.Mock`1[AutomationsWeb.Features.Statistics.GetAutomationsLogTotalCount] because creation unexpectedly failed with exception. Please refer to the inner exception to investigate the root cause of the failure.

Request path:
	Moq.Mock`1[AutomationsWeb.Features.Statistics.GetAutomationsLogTotalCount] getAutomationsLogTotalCount
	  Moq.Mock`1[AutomationsWeb.Features.Statistics.GetAutomationsLogTotalCount]

Inner exception messages:
	System.NotSupportedException: CallBase cannot be used with Delegate mocks.
```

_Originally posted by @Veikedo in https://github.com/moq/moq4/issues/706#issuecomment-444523679_

**Comment by stakx** [comment]
@Veikedo - This looks like an AutoFixture problem to me. You might not be calling `.CallBase()` on the mock, but apparently AutoFixture does. Which is an error, since for delegate mocks, there is no base implementation to call.

Moq used to stay quiet about it, but it's now explicitly calling this out as a bad call.

Please report the problem to the AutoFixture project (or more precisely, whoever provides the AutoFixture-Moq integration). Until that issue gets fixed there, you can downgrade Moq to a previous version that silently ignores this error.

**Comment by Veikedo** [comment]
@stakx sorry, I was quite sure I am on AutoFixture's project :)
Thanks for the reply!
