### ISSUE TITLE
Unable to resolve IFluentInterface

### ISSUE THREAD

**Issue by NoxMortem** [moq/moq4#734]
Trying to build moq4, I am unable to resolve IFluentInterface. Any ideas?

I've already updated Visual Studio 2017, used `git reset --hard`, `git pull` to get the latest stage, restored the nuget packages but still I am unable to build it.

**Comment by stakx** [comment]
Hmm. Usually, any initial problems with building disappear once you've performed a package restore and re-opened the solution. Can you try the following?

* Close Visual Studio and delete at least the `src/Moq/bin/` and `src/Moq/obj/` folders.
* Open a Visual Studio developer prompt and run `msbuild /r` from inside the Moq solution directory.

**Comment by NoxMortem** [comment]
Works in Visual Studio and is a Jetbrains Rider Bug not executing a target which generated the IFluentInterface.g.cs
