### ISSUE TITLE
Example for how to return a class that also needs mocking.

### ISSUE THREAD

**Issue by Bungalow12** [moq/moq4#736]
Let's say I have a class `Map` that I mock. This map class has a `map.Player` that should return a `Player` class that also needs to be mocked such that I can call `player.Name` and have that return `"MockedName"`. 
The situation being I am building a class that needs to get the name by calling `map.Player.Name`. I want to unit test my property for my `Controller` class' `controller.PlayerName`. How can I unit test this scenario? I can't return a new Mock<Player> because the expected return is player. I'm sure there is a way to do this but I can't see it.

Can someone add an example of mocking a returned object that also needs mocking?

**Comment by stakx** [comment]
```csharp
var map = Mock.Of<Map>(m => m.Player.Name == "MockedName");
```

**Comment by Bungalow12** [comment]
That is perfect! Thank you. It makes so much sense now :)
