### ISSUE TITLE
Raise event when stubbed property is changed

### ISSUE THREAD

**Issue by yordans** [moq/moq4#745]
How to raise event when stubbed property (automatically tracking its value) is changed (setter called)?

e.g. 
mock.SetupProperty(m => m.Foo).Raises(m => m.FooChanged += null);
mock.Object.Foo = 5; // raises the FooChanged event on ISomething

**Comment by yordans** [comment]
I want the event to be fired automatically when a stubbed property is changed but it seems that this functionality is missing.

**Comment by stakx** [comment]
@yordans - It appears that you've already answered your own question for the most part:

```csharp
public interface IFoo
{
    int Foo { get; set; }
    event EventHandler FooChanged;
}

var mock = new Mock<IFoo>();
mock.Object.FooChanged += (s, e) => Console.WriteLine("Foo property changed.");
mock.SetupSet(m => m.Foo = It.IsAny<int>()).Raises(m => m.FooChanged += null, EventArgs.Empty);
mock.Object.Foo = 5;
```

(If you want an API that creates such a setup for any pair of a property `P` and an event `PChanged`, it should be easy to create it as an extension method. Because neither the member names nor the property type will be known in advance, you'll have to build the setup expressions yourself (using the static `Expression` factory methods) instead of letting the compiler do it for you.)

Can we close this, or did I misunderstand something?

**Comment by yordans** [comment]
It is fine the event to be fired when the property is set, but the real problem is that I want the mock to "track" sets/gets to this property (i.e. Stub) + firing event.

`mock.SetupSet(m => m.Foo = It.IsAny<int>())` 

won't track the property Foo.

**Comment by stakx** [comment]
What exactly do you mean by "tracking a property"?

**Comment by yordans** [comment]
When setup property in this way:
`mock.SetupProperty(m => m.Foo);`
it is a Stub and it tracks its changes, so if latter call mock.Object.Foo = 5 and then get the value, it will be 5.

And the question is could this kind of stubbed property be setup to raise an event when changed?

**Comment by stakx** [comment]
> And the question is could this kind of stubbed property be setup to raise an event when changed?

I'll once again refer you to [my first post above](https://github.com/moq/moq4/issues/745#issuecomment-460630808) which shows you just how to do that.

**Comment by yordans** [comment]
Thank you for your responses. I think the issue can be closed.

Is it planned `SetupProperty` to offer a way for raising events out of the box?

**Comment by stakx** [comment]
> Is it planned `SetupProperty` to offer a way for raising events out of the box?

No, such an extension isn't planned at the moment.

**Comment by jhv2017kam** [comment]
@stakx When implementing what you describe here I ran in to the problem that `property.ToPropertyInfo();` used in the newest version of SetupProperty is placed in an internal extensions class would it be possible to have ToProperty be part of the public API?

**Comment by stakx** [comment]
@jhv2017kam, no, that helper method definitely does not belong in Moq's public API... it's strictly an implementation detail. But it should be easy enough to replicate in your own code.
