### ISSUE TITLE
`mock.Protected().Verify` method group has no overloads with `bool exactParameterMatch`

### ISSUE THREAD

**Issue by stakx** [moq/moq4#752]
This is a continuation of https://github.com/moq/moq4/issues/735#issuecomment-465678796. In #751 we added a missing method overload to the `mock.Protected().Setup` method group that gives users the option to specify `bool exactParameterMatch` for non-void methods.

What is likely needed to solve the problem reported in https://github.com/moq/moq4/issues/735#issuecomment-465576779 is similar additional overloads for the `mock.Protected().Verify` method group.

/cc @Shereef

**Comment by Shereef** [comment]
Thanks for your feedback it all makes sense.

P.S. the virtual part I had in my original project I just forgot it while making the test here, I have updated it and created a PR with the fix, if you have feedback please don't hesitate.
