### ISSUE TITLE
Modifying list in between mocked calls causes verifying to fail.

### ISSUE THREAD

**Issue by johnthcall** [moq/moq4#757]
I noticed that when calling a mocked function that only a referenced to the variables at invocation time are cached. For a majority of objects it is clear that a deep copy cannot be made, however for lists and arrays I expected a copy to be made.

Here is a sample piece of code to demonstrate the issue.
```
var aggregatedList = new List<string>();
var items = new List<string>() { "a", "b", "c" };
foreach (var item in items)
{
  aggregatedList.Add(item);
  if (aggregatedList.Count > 2)
  {
    myClass.myMethod(aggregatedList);
    aggregatedList.Clear();
  }
}
```

My verifies for this might be.
```
mockMyClass.Verify(myClass => myClass.myMethod(It.IsAny<List<String>>(list => list.Count == 2)), Times.Once);
mockMyClass.Verify(myClass => myClass.myMethod(It.IsAny<List<String>>(list => list.Count == 1)), Times.Once);
```
However because the same reference is used for both myMethod calls the invocations list shows 2 calls of myMethod both with a list of 1 items containing "c".

When invocations are created can collection objects be shallow copied to make this experience a little bit better?

**Comment by lepijohnny** [comment]
Actually, it seems this one is exactly the same as #756

**Comment by stakx** [comment]
First off, assuming that I am reading your code correctly, either your code or your verifications are incorrect: This code will call `myClass.myMethod` once with a list containing all three elements `"a"`, `"b"`, and `"c"`. Both of your verification steps would fail even if the requested change were implemented. So this is a rather bad example to base a change request on.

Second, why should collections get any different treatment than other reference types? Your eyample doesn't demonstrate that at all.

Third, *any* kind of work that happens during a proxied invocation is going to slow down Moq runtime performance. Having to check *each* invocarion argument's type, then optionally performing a shallow clone, will negatively affect *all* usage scenarios, not just yours, which is likely a somewhat rare use case. Even without benchmarking I am confident that penalizing all users for such little gain this would be a bad tradeoff to make.

If you need to capture argument state at the time when an invocarion occurs, use capturing matchers (e.g. `Capture.In`). That way you can target only those method setups that need this.
