### ISSUE TITLE
unable to mock in unittesting on windows app?

### ISSUE THREAD

**Issue by Charlemagne65** [moq/moq4#79]
Install-Package : Could not install package 'Moq 4.2.1312.1622'. You are trying to install this package into a project that targets '.NETCore,Version=v4.5.1', but the package does not contain any assembly references or content file
s that are compatible with that framework. For more information, contact the package author.
At line:1 char:1
- Install-Package Moq
- ~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : NotSpecified: (:) [Install-Package], InvalidOperationException
  - FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PowerShell.Commands.InstallPackageCommand

I would like using moq in a Windows Store App. But this is the message I get from the NUGet PM. 

What is going wrong?

**Comment by stakx** [comment]
@Chakotay - this issue is super old, but just for the record, Moq 5 will likely support this scenario.
