### ISSUE TITLE
Setup sequence doesn't support ReturnsAsync with Func<>

### ISSUE THREAD

**Issue by kswider** [moq/moq4#795]
In SetupSequence there is an overload for Returns can that take Func<> as an argument, but there isn't such overload for ReturnsAsync. 

I think that adding this overload to ReturnsAsync would be a nice enhancement.

**Comment by stakx** [comment]
Would you like to provide the implementation for it?

**Comment by kswider** [comment]
Yea, I think I can make it :)

**Comment by VladFasie** [comment]
could you please detail the requirements ?

**Comment by stakx** [comment]
@VladFasie: The existing non-async method `ReturnsAsync(Func<T> valueFactory)` returns a value of type `T` that is equal to whatever `valueFactory()` returns. I'd assume the `.ReturnsAsync(Func<T> valueFactory)` to do the same, i.e. it should return a completed `[Value]Task<T>` whose `.Result` property equals the value produced by `valueFactory()`. Neither the result of that call nor the returned task should be cached, i.e. every invocation of the sequence setup produces a new task.

**Comment by VladFasie** [comment]
I can't make my branch public.

git push --set-upstream origin "#795"
remote: Permission to moq/moq4.git denied to VladFasie.
fatal: unable to access 'https://github.com/moq/moq4.git/': The requested URL returned error: 403

**Comment by stakx** [comment]
@VladFasie - First, please coordinate your efforts with @kswider, as he stated above that he might be working on this as well. It would be a shame if both of you work on this separately, as I will only be able to merge the changes from one of you.

If @kswider is fine with *you* going ahead here, then please send a pull request (PR) via GitHub. That is:

1. Fork this repository to your own GitHub account.
2. Clone your own fork repository.
3. Create a topic branch off `master`.
4. Add commits to that topic branch.
5. Submit a PR from this branch in your repository to `master` in this repository.

Please make sure that you've read our [contributing guide](https://github.com/moq/moq4/blob/master/CONTRIBUTING.md). Thanks!

**Comment by kswider** [comment]
If @VladFasie has already finished fixing that issue I'm ok with that. I planned to do it today :)

**Comment by mattdeckard** [comment]
I ran into this just yesterday and would love to see it added. In addition, there doesn't seem to be any way of accessing the arguments within the version of `Returns()` that takes a `Func<>`. Was that intentional or another oversight that could potentially be added along with this?

**Comment by stakx** [comment]
> Was that intentional or another oversight that could potentially be added along with this?

Moq's API today is mostly driven by the community's needs, so it is not so much an oversight, but more that noone asked for nor implemented this.

Making these additions would certainly be possible.

(I personally think the whole `SetupSequence` API shouldn't expanded much further, initially it was probably meant as a simple helper that spared you the work of setting up a callback with a state machine inside (though that remains of course possible for more complicated scenarios), it's something of a burden keeping it in synch with the main `Setup` API.)

**Comment by VladFasie** [comment]
I hope I will manage to come with a push in weekend

**Comment by stakx** [comment]
@kswider: @VladFasie closed his PR a moment ago. If you'd still like to proceed with this issue and submit your own, please feel free to go ahead.

**Comment by BenCoden** [comment]
Is there a workaround? 
And @kswider are you making a PR?
