### ISSUE TITLE
Requesting permission to publish as Moq.HttpClient

### ISSUE THREAD

**Issue by maxkagamine** [moq/moq4#807]
I created a library a while back that adds extension methods to assist in mocking HttpClient: https://github.com/maxkagamine/Moq.HttpClient

I'd like to publish this as Moq.HttpClient so my name isn't plastered on the namespace anymore (unlisting the one I published), but it looks like NuGet now has the "Moq" prefix reserved for one of your accounts. If I try to upload, I get:

> This package ID has been reserved. Please request access to upload to this reserved namespace from the owner of the reserved prefix, or re-upload the package with a different ID.

Would you be willing to give me access to publish this package under your prefix?

**Comment by stakx** [comment]
@kzu, can you answer this one?

@maxkagamine, @kzu (the owner of this project) is managing the NuGet account. Not sure, but he might have registered a contrib package namespace?

**Comment by kzu** [comment]
Indeed, community packages should be named Moq.Contrib.*

**Comment by maxkagamine** [comment]
Wasn't aware of that, apologies. I renamed everything and [was able to upload successfully](https://www.nuget.org/packages/Moq.Contrib.HttpClient/). Will go ahead and close this. Thanks guys!
