### ISSUE TITLE
`in` string parameter verifying doesn't work in some cases

### ISSUE THREAD

**Issue by wholegroup** [moq/moq4#808]
moq 4.10.1

```java
        public interface ISome
        {
            string bad(in string text);
        }

        [Test]
        public void testMoq()
        {
            var m = new Mock<ISome>();
            m.Setup(foo => foo.bad("test")).Verifiable();
            m.Object.bad("test.".TrimEnd('.')); // it doesn't work
//            m.Object.bad("test"); // it works well
            m.Verify();
        }
```

**Comment by stakx** [comment]
Why are you passing `string` using `in`? `System.String` is already a reference type, and as such will be passed by-reference anyway.

**Comment by wholegroup** [comment]
@stakx 
I use `in` modifier to mark variables as immutable. It's kind of `final` in Java. Microsoft calls this 'readonly references'.

**Comment by stakx** [comment]
`in` was introduced to be used mostly in conjunction with *value types*. 
Of course it's your decision to use it however you want. Just be aware that Moq has certain rules when it comes to matching by-ref arguments (which align more with how by-ref parameters are *typically* employed), which you'll need to follow if you want to continue using `in` your way.

**Comment by wholegroup** [comment]
@stakx 

Thank you for your help and fast response! I definitely used `in` in the wrong way.

> When using the string constant `"test"`, both the setup and the invocation refer to the exact same string instance in both cases due to interning. When you use a string expression `"test.".TrimEnd('.')`, a new, distinct string object will get computed that does not reference-equal the `"test"` string instance. To test that theory, try calling your method with an argument `string.Intern("test.".Trim('.'))` and see what happens.

**Comment by stakx** [comment]
Glad I could help. 😃
