### ISSUE TITLE
ToString() on SetupPhrase does not return expression

### ISSUE THREAD

**Issue by jacob-ewald** [moq/moq4#810]
We have a unit test that verifies the message we receive when a sequenced setup is not run, but with version 4.10+ the message is no longer displaying the expression. Instead, it displays the full name of the type and method, which is the default `ToString()` output. I originally thought this may be an issue with Moq.Sequences, however it seems to be originating inside Moq.

To reproduce the issue here is a simple unit test:
```C#
[Fact]
public void SetupPhraseConvertsExpressionToDescriptiveString()
{
	var setupPhrase = new Mock<IFoo>().Setup(x => x.DoThings(null));

	Assert.Equal("x => x.DoThings(null)", setupPhrase.ToString());
}
```

Expected:
```C#
x => x.DoThings(null)
```
Actual:
```C#
Moq.Language.Flow.VoidSetupPhrase`1[Moq.Tests.Regressions.IssueReportsFixture+IFoo]
```

I can submit a PR to fix this (simply overridding the `ToString()` on `SetupPhrase`), but wanted to see if that would be welcome first. Thanks!

**Comment by stakx** [comment]
@jacob-ewald: Sounds like a reasonable enhancement! I suppose it would make sense for all fluent API types' `ToString` methods to simply delegate to the `ToString` method of the setup that they're wrapping. Your PR would be welcome. It'd be great if you could make the change for all `...Phrase` classes.

**Comment by jacob-ewald** [comment]
Thanks @stakx. I created PR #812. I did _not_ add handling for `WhenPhrase` because that works on `Func<bool>`, which doesn't play nicely with the `ExpressionStringBuilder`.
