### ISSUE TITLE
Moq pre-release version 4.11.0-rc1

### ISSUE THREAD

**Issue by stakx** [moq/moq4#815]
Moq pre-release version 4.11.0-rc1 is now available on NuGet. I am pinging everyone who has contributed to this version, in case you want to run some tests and verify that everything is working as expected.  

If no regressions get reported, I will publish 4.11.0 proper in a few weeks' time.

/cc @jacob-ewald, @mosentok, @aeslinger0, @MichaelSagalovich, @icenine457, @jamesfoster, @idigra, @MutatedTomato, @Shereef, @sdepouw, @lepijohnny, @dav1dev, @hallipr, @TimothyHayes, @thalesmello

**Comment by Shereef** [comment]
Thanks for the ping!

**Comment by lepijohnny** [comment]
I have verified the changes I introduced, everything as expected. :clap: to @stakx and all other contributors.

**Comment by stakx** [comment]
Moq 4.11.0 proper is now available on NuGet.
