### ISSUE TITLE
System.InvalidCastException when invoking method that starts with "add"

### ISSUE THREAD

**Issue by F0b0s** [moq/moq4#82]
Hello, I faced with the problem when i used Moq.
I wrote the simple test

```
public interface ILogger
{
    void add_info(string info);
    void Add_info(string info);
}

[TestFixture]
public class Class1
{
    [Test]
    public void Test_add_info()
    {
        var mock = new Mock<ILogger>();
        mock.Setup(x => x.add_info(It.IsAny<string>()));
        mock.Setup(x => x.Add_info(It.IsAny<string>()));

        mock.Object.add_info("asd");
        //mock.Object.Add_info("asd");
    }
}
```

When i call

mock.Object.add_info("asd"); 

it throws 
System.InvalidCastException : Не удалось привести тип объекта "System.String" к типу "System.Delegate".
   в Moq.AddActualInvocation.HandleIntercept(ICallContext invocation, InterceptStrategyContext ctx)
   в Moq.Interceptor.Intercept(ICallContext invocation)
   в Castle.DynamicProxy.AbstractInvocation.Proceed()
   в Test.Class1.Test_add_info() в Class1.cs: line 22

Sorry, i have Russian VS, it says: "Can't cast System.String to System.Delegate". But, when i call 

mock.Object.Object.Add_info("asd"); 

string, it works.
I use VS 2012, .NET4.5. Nuget packages - NUnit, Moq(v.4.2.1312.1622). The Code was runned from Resharper test runner.

**Comment by stakx** [comment]
Regular methods with `add_` or `remove_` name prefixes are now supported in Moq 4.8.0.
