### ISSUE TITLE
Provide fluent interface

### ISSUE THREAD

**Issue by mu88** [moq/moq4#833]
It would be great if we could write something like the following:
```
IMyType myMock = new Mock<IMyType>().Setup(...).Returns(...)
                                    .Setup(...).Returns(...)
                                    .Object;
```

**Comment by stakx** [comment]
I somewhat agree, but on the downside this would require that we pollute the whole fluent API with `.Setup()` verbs at every step along the way. Not sure *that*'s such a good idea. Also, it'll make it less clear when the fluent API is configuring a setup, and when it's configuring the mock. Mainly for that last reason, I think it's better to keep the fluent API simple & focused on configuring a single setup.

**Comment by stakx** [comment]
Hi @mu88, thanks for your suggestion. As this would be a fairly fundamental change to Moq's fluent API, we'll have to check with @kzu whether this would also stand a chance of being included in the upcoming Moq v5. (It would be a pity to do all the work to add it in v4 only to once again have it lacking in v5.)

My initial reaction here is somewhat ambivalent:

* From a user perspective, this would be a nice shortcut in a few use cases.

* Often however, you can already use `Mock.Of<T>` to achieve much the same thing in an even terser fashion.

* This would blur the line of when the fluent API is configuring a setup, and when it's configuring the mock. For better ease of understanding the API, it might be better not to mix up these two concerns.

* This will require adding `.Setup*` verbs at every step of the fluent API, which means quite a bit of code duplication and added maintenance effort. (It's simple code, but repetitive and quantitatively quite a lot of it.). I secretely hope we can avoid that.

Any thoughts or opinions?

**Comment by kzu** [comment]
If all you're doing are Setup...Returns, you could just use Linq to Mocks instead: 

```
IMyType my = Mock.Of<MyType>(x => x.Foo == ... && x.Bar == ...);
```

**Comment by mu88** [comment]
Thanks to the two of you for sharing your ideas :) I absolutely understand your concerns.

I didn't know about `Mock.Of<>()` and will take a closer look on it! Just two thoughts/observations about this:

- I tried to use it for an async method in the way of `Mock.Of<IMyType>(async x => await x.DoSomethingAsync() == new CustomResult())`, which cannot be compiled.
- At a first look, the usage of equality operator `==` instead of assignment operator `=` within the lambda is a bit counterintuitive. I will see whether it confuses my colleagues ;)

**Comment by stakx** [comment]
> I tried to use it for an async method in the way of `Mock.Of<IMyType>(async x => await x.DoSomethingAsync() == new CustomResult())`, which cannot be compiled.

The C# compiler has some unfortunate limitations of what it can convert to LINQ expression trees. (See https://github.com/dotnet/csharplang/issues/158.)

You could work around it as follows:

```csharp
Mock.Of<IMyType>(x => x.DoSomethingAsync() == Task.FromResult(new CustomResult()))
```

> At a first look, the usage of equality operator `==` instead of assignment operator `=` within the lambda is a bit counterintuitive. I will see whether it confuses my colleagues ;)

It can be helpful to think about `Mock.Of<T>(expr)` in a declarative (rather than imperative) way: "Give me a mock that meets these conditions: \<expr\>."

**Comment by kirinboy** [comment]
Could `Mock.Of<T>` have a fluent API? If I want to mock multiple properties or methods, it is not very clear to read and write.

**Comment by stakx** [comment]
@kirinboy, a fluent API wouldn't work with `Mock.Of<T>` since it returns the mock object instance directly, which can have any type. Just use `&&` (as shown in an above post) to set up several members.

**Comment by stakx** [comment]
I'm closing this issue, seeing that there is an existing & mostly viable alternative (`Mock.Of<T>(predicate)`) to what was requested here. If such a fundamental change should be made to the setup API, I'd prefer to let Moq v5 take the lead here.

That being said, I'll think about some easy and inconspicuous extension points in the fluent API that would allow client code to add their own extension methods to make this work. (More specifically, if the interfaces making up the fluent setup API each made their current "context" accessible, e.g. via some `Mock` and `Setup` properties, it should become possivle for client code to build new fluent APIs on top of that.)
