### ISSUE TITLE
SetupAllProperties does not setup write-only properties

### ISSUE THREAD

**Issue by vanashimko** [moq/moq4#835]
Opening a new issue as per https://github.com/moq/moq4/pull/826#discussion_r288929791.

**Steps to reproduce**
```csharp
public abstract class WriteOnlyProperty
{
   public abstract string Test { set; }
}

[Fact]
public void Write_only_property_should_be_ignored_by_SetupAllProperties()
{
   var mock = new Mock<WriteOnlyProperty>(MockBehavior.Strict);
   mock.SetupAllProperties();
	
   mock.Object.Test = "test";
}
```

**Expected behavior** 
Test is passed, writing to Test property is ignored.

**Actual behavior** 
Exception is thrown: 
```
Moq.MockException : WriteOnlyProperty.Test = "test" invocation failed with mock behavior Strict.
All invocations on the mock must have a corresponding setup.
```

**Comment by stakx** [comment]
Assuming that changing the current behavior won't break any existing tests, I'm all for fixing this. Please feel free to submit a PR.
