### ISSUE TITLE
Verify NullReferenceException if method is called with null parameter

### ISSUE THREAD

**Issue by ShaunMitchem** [moq/moq4#859]
Hi there - in the attached example, the test Method2_ShouldCall_Load_On_Class1() throws a NullReferenceException because Method2() calls _class1.Load(null);

Should Verify not check that a match isn't null before it tests the property?

Thanks

Shaun

//======================================

using Moq;
using Xunit;

namespace MockIssue
{
    public interface IClass1
    {
        void Load(Class2 class2);
    }

    public class Class1 : IClass1
    {
        public void Load(Class2 class2){}
    }

    public class Class2
    {
        public int Property1 { get; set; }
    }

    public class Class3
    {
        private readonly IClass1 _class1;

        public Class3(IClass1 class1)
        {
            _class1 = class1;
        }

        public void Method1()
        {
            var class2 = new Class2();
            class2.Property1 = 12;

            _class1.Load(class2);
        }
        
        public void Method2()
        {
            _class1.Load(null);

            var class2 = new Class2();
            class2.Property1 = 12;

            _class1.Load(class2);
        }
    }

    public class Class3Tests
    {
        [Fact]
        public void Method1_ShouldCall_Load_On_Class1()
        {
            var class1Mock = new Mock<IClass1>();

            var class3 = new Class3(class1Mock.Object);

            class3.Method1();

            class1Mock.Verify(m => m.Load(It.Is<Class2>(arg => arg.Property1 == 12)));
        }

        [Fact]
        public void Method2_ShouldCall_Load_On_Class1()
        {
            var class1Mock = new Mock<IClass1>();

            var class3 = new Class3(class1Mock.Object);

            class3.Method2();

            class1Mock.Verify(m => m.Load(It.Is<Class2>(arg => arg.Property1 == 12)));
        }
    }
}

//======================================

**Comment by stakx** [comment]
> Should Verify not check that a match isn't null before it tests the property?

Maybe, maybe not. Either way, it is probably much too late to change the behavior of the `It.Is<T>(predicate)` matcher; that would probably break tons of existing user code out there.

So I suggest that you change 
`It.Is<Class2>(arg => arg.Property1 == 12)` to `...arg?.Property1...`.

**Comment by ShaunMitchem** [comment]
Ok - thanks

On 9 Jul 2019, at 14:59, stakx <notifications@github.com<mailto:notifications@github.com>> wrote:


Should Verify not check that a match isn't null before it tests the property?

Maybe, maybe not. Either way, it is probably much too late to change the behavior of the It.Is<T>(predicate) matcher; that would probably break tons of existing user code out there.

So I suggest that you change
It.Is<Class2>(arg => arg.Property1 == 12) to ...arg?.Property1....

**Comment by ShaunMitchem** [comment]
Just FYI, your suggestion doesn’t compile – “An expression tree lamda may not contain a null propagating operator”

Obviously It.Is<Class2>(arg => arg != null && arg.Property1 == 12) works fine, you just lose some of the sense of what it was you were trying to verify in the test

To be honest, I think the better solution is probably “don’t go passing nulls around”!

**Comment by stakx** [comment]
> Just FYI, your suggestion doesn’t compile – “An expression tree lamda may not contain a null propagating operator” Obviously It.Is<Class2>(arg => arg != null && arg.Property1 == 12) works fine, you just lose some of the sense of what it was you were trying to verify in the test To be honest, I think the better solution is probably “don’t go passing nulls around”! 

Arrgh, apologies, you're absolutely right, of course. The limitations of LINQ expression trees these days are just ridiculous!

You could define a custom matcher (using `Match.Create`) that would do what you want, but it's perhaps just as easy to be a little more verbose.
