### ISSUE TITLE
Null reference exception for EventHandler property with name starting with "Item"

### ISSUE THREAD

**Issue by kaan-kaya** [moq/moq4#869]
I have experienced an issue when trying to mock an interface with a EventHandler property whose name starts with "Item".

Sample interface:

```
public interface IEventGenerator
{
    EventHandler<BaseCustomEventArgs> ItemAdded { get; set; }
}
``

**Comment by stakx** [comment]
@kaan-kaya, could you please provide a minimal but complete code example that we can run to reproduce that exception? Otherwise I'll close this issue in a few days'time.

**Comment by stakx** [comment]
This is very likely a duplicate of #870, so I am also closing this. If you think that was in error, please let me know and we'll reopen.
