### ISSUE TITLE
MockDefaultValueProvider does not support Task<T> results

### ISSUE THREAD

**Issue by rickykaare** [moq/moq4#87]
When using the MockDefaultValueProvider, methods with a return type of Task<T> will get an empty Task (provided by the EmptyDefaultValueProvider) as the default value. 

Expected behavior is to return a mock wrapped in a completed Task.

Related to #73

**Comment by stakx** [comment]
Thank you for reporting this! Issue #171 covers the same ground but has a slightly wider scope, so I'll close this issue in favor of #171.
