### ISSUE TITLE
MockDefaultValueProvider will try to set 'Callbase' on auto-generated mocks for delegates.

### ISSUE THREAD

**Issue by dammejed** [moq/moq4#874]
Recently, it's become a blocking error to set `CallBase` to true on Mocks of delegates.
This causes a regression is existing code that had set `CallBase` to true, and the `MockDefaultValueProvider` was being used to provide values for items that weren't setup.

Here's an illustration of the issue:
```csharp
[Fact]
public void MockDefaultValueProvide_will_not_propagate_Callback_to_delegates()
{
	var mock = new Mock<IDictionary<string, Func<string>>>()
	{
		CallBase = true,
		DefaultValue = DefaultValue.Mock
	};
	var mockedIndexResult = mock.Object["foo"]; // This line throws because it attempts to set `CallBase` to true on the auto-generated mock for the delegate.
	Assert.Null(mockedIndexResult());
}
```

I can submit a PR to fix the bug-- it seems fairly straightforward.

**Comment by stakx** [comment]
Hi @dammejed, thanks for reporting this problem, and for your PR. Yes, this looks like something that should be fixed!

**Comment by dammejed** [comment]
Cheers, thanks for your reactivity! 👍
