### ISSUE TITLE
Behavioural change between 4.11 -> 4.12 with CallBase=True and params args

### ISSUE THREAD

**Issue by chrisaut** [moq/moq4#877]
Consider the following code:
```C#
    public class C1
    {
        public virtual string M(string s, params object[] args) => "fromBase";
    }
    public class Tests
    { 
        [Fact]
        public void Test1()
        {
            var c = new Mock<C1>();
            c.CallBase = true;
            c.Setup(x => x.M(It.IsAny<string>(), It.IsAny<object[]>()))
                //.Returns(default(string))
                .Verifiable();

            var result = c.Object.M("foo", 1, 2);
            Assert.Null(result);
        }
     }
```
In 4.11.0 this test passes, that is it does NOT call into C1's implementation of "M"

However in 4.12.0 this test fails, result = "fromBase", it is as if the setup doesn't match. Uncommenting the .Returns line fixes it in 4.12.0. I think it has to do with the params object array

This took me a while to figure out, and I'm not entirely sure what the expected behavior should be, but I think this is a bug?

**Comment by stakx** [comment]
This is noted in the changelog for 4.12:

> Setups with no `.Returns(…)` nor `.CallBase()` no longer return `default(T)` for loose mocks, but a value that is consistent with the mock's `CallBase` and `DefaultValue[Provider]` settings. (@stakx, #849)

The change was made for improved consistency, and it's in line with a hint dropped by @kzu (can't find the reference right now) that setups on non-void methods without any `Returns`, `Throws` or `CallBase` are basically a user mistake and will be called out as such in Moq v5.

**Comment by chrisaut** [comment]
Oh I see, sorry I didn't see a changelog under releases, but see it is a .md file.

**Comment by stakx** [comment]
Yes, perhaps I should start annotating releases with the relevant changelog entries. Thanks for the hint!
