### ISSUE TITLE
Setup method DateTimeOffset vs DateTime

### ISSUE THREAD

**Issue by michelcedric** [moq/moq4#898]
During a setup if a method take a parameter of type DateTimeOffset but defined
It.IsAny<DateTime>() and not It.IsAny<DateTimeOffset>()
After that the mtehod return null.
I can understand it's not the strict same type. But it compile and there no exception with a correct message but just return null.
Could you block the compilation or raise a good exception with a specific message. 

https://github.com/moq/moq4/issues/897

Best regards

Cédric Michel

**Comment by stakx** [comment]
Please don't post duplicate issues.

**Comment by stakx** [comment]
P.S.:

> Could you block the compilation or raise a good exception with a specific message.

No. `DateTimeOffset` declares an implicit conversion operator to `DateTime`. Know your APIs. There's nothing we can do about that on Moq's side.

**Comment by michelcedric** [comment]
`var serviceMock = new Mock<IMeteringDataServiceAgent>();
            serviceMock.Setup(s => s.GetDataList(It.IsAny<DateTime>())).Returns(_data);
            var result3 = serviceMock.Object.GetDataList(new DateTime(2019,1,1));

            //Expected the list but received null
            //Because during the setup I put It.IsAny<DateTime>() and not It.IsAny<DateTimeOffset>()
            Assert.AreEqual(_data, result3);`

**Comment by michelcedric** [comment]
It's not a duplicate in my repository I have 2 test case with 2 different issue
1 about return null for IEnumerable but not for a List and I think it's a strange behavior
2 Setup and invocation with sub type DateTime or in the Mocked interface is DateTimeOffset and he return null.

**Comment by stakx** [comment]
See your other issue, to which you linked from this one, for an answer regarding all of these tests.
