### ISSUE TITLE
Permission to wrap & distribute as a COM library under GPLv3?

### ISSUE THREAD

**Issue by retailcoder** [moq/moq4#910]
Hi,

First of all, huge props to all Moq contributors - this package has changed my life!

I manage an OSS project licensed under GPLv3; [Rubberduck](http://rubberduckvba.com) is a COM add-in for the VBIDE (VB6/VBA6/VBA7 x86/x64) that aims to bring the legacy editor into this century with features that every modern IDE has - including navigational enhancements, static code analysis, refactorings... and a unit testing framework, to name a few.

There's a pull request that's been WIP for a while, that's solved all the hard parts and is now nearing completion; [this pull request](https://github.com/rubberduck-vba/Rubberduck/pull/4681) would give Rubberduck a full-blown mocking framework, by wrapping Moq into a COM-visible API that VBA/VB6 code can consume. This is a complete revolution in the VBA landscape, and I'd really want Moq to get all the praise it deserves from users of this future Rubberduck feature: there's no way that PR could have existed without Moq.

Now, I should probably have done this a couple of months ago, but I would like to ask for your permission to distribute this wrapper API (with proper attribution) as a Rubberduck feature, branded as a "Moq wrapper" - similar to how we ported the original Smart Indenter code (which was kindly offered to the Rubberduck project... under GPLv3) and now publicly brand it as a "Smart Indenter port".

Can we use the name "Moq" in "Moq wrapper API", or we should just call it some "Mocking API" that users would only know it's Moq under the hood if they looked at the project's attributions? Is the GPLv3 license a problem? If so, how can we make it work?

Thank you for your time!
Mathieu

**Comment by retailcoder** [comment]
Linking #887

**Comment by kzu** [comment]
I don't have a problem at all. The conditions sound fair (attribution). 

Thanks for asking and good luck with that cool new feature!
