### ISSUE TITLE
4.13 callback with returns and out parameter ~ bug?

### ISSUE THREAD

**Issue by Rubenisme** [moq/moq4#917]
The following worked in 4.12:

```
using Moq;
using NUnit.Framework;

namespace Tests
{
    public interface ITest
    {
        int JustAMethod(string name, out string outParam);
    }

    public class Tests
    {
        private readonly Mock<ITest> _myMock = new Mock<ITest>();

        [Test]
        public void Test1()
        {
            string saveParamName;
            string outParam;
            _myMock.Setup(
                    tcm => tcm.JustAMethod(It.IsAny<string>(), out outParam))
                .Callback((string name, string unused) => saveParamName = name)
                .Returns(30);
        }
    }
}
```

But fails on 4.13 with this exception:

>    Test1 Failed: System.ArgumentException : Invalid callback. Setup on method with parameters (string, out string) cannot invoke callback with parameters (string, string).
> System.ArgumentException : Invalid callback. Setup on method with parameters (string, out string) cannot invoke callback with parameters (string, string).
>    at Moq.MethodCall.SetCallbackResponse(Delegate callback)
>    at Moq.Language.Flow.SetupPhrase.Callback[T1,T2](Action`2 callback)
>    at Tests.Tests.Test1() in C:\Users\ID045675\source\repos\Test\NUnitTest\UnitTest1.cs:line 32

Looks like it has to do with [this change](https://github.com/moq/moq4/issues/872).
Is this not a bug/breaking change?

Update: this also fails if you call 'Returns' first before 'Callback'.

**Comment by stakx** [comment]
> Looks like it has to do with this change.

Correct. See this entry in the [changelog](https://github.com/moq/moq4/blob/v4.13.0/CHANGELOG.md#changed):

> Consistent Callback delegate validation regardless of whether or not Callback is preceded by a Returns: Validation for post-Returns callback delegates used to be very relaxed, but is now equally strict as in the pre-Returns case.) (@stakx, #876)

**Comment by stakx** [comment]
> Update: this also fails if you call 'Returns' first before 'Callback'.

Reopening. If that's correct, I'd like to take a closer look.

**Comment by stakx** [comment]
The code posted above fails in Moq 4.12.0. It succeeds only when `Callback` is called after `Returns`.

The code posted above fails in Moq 4.13.0, regardless of whether `Callback` appears before or after `Returns`. So this is indeed what the changelog entry describes, i.e. this is not a bug, but an intended change.

**Comment by Rubenisme** [comment]
Thanks for the clarification and the prompt reply. Can you tell me how to save my variables now? I can't use the out keyword on the callback to have my callback's parameter types to match those on the method, can I?

**Comment by stakx** [comment]
```csharp
delegate void JustAMethodCallback(string name, out string outParam);
...

_myMock.Setup(...).Callback(new JustAMethodCallback((string name, out string outParam) => ...);
```

The custom delegate type is necessry because Moq only provides overloads for `Action` and `Func`, all of which don't have any by-ref parameters. So you need to call the overload that accepts any `Delegate`.
