### ISSUE TITLE
Can't setup protected methods with nullable parameters

### ISSUE THREAD

**Issue by RobSiklos** [moq/moq4#92]
It seems that it's not possible to set up a protected method if it has nullable parameters.

Example:

``` csharp
public abstract class MyService
{
    protected abstract void MyMethod(int? val);
}

class Program
{
    static void Main(string[] args)
    {
        var mock = new Mock<MyService>();

        mock.Protected().Setup("MyMethod", (int?)1);
    }
}
```

The output of running this program is an `ArgumentException` with the following message:

Expression of type 'System.Int32' cannot be used for parameter of type 'System.Nullable`1[System.Int32]' of method 'Void MyMethod(System.Nullable`1[System.Int32])'

**Comment by RobSiklos** [comment]
@kzu Ok - I finally got around to doing this :) Pull request #199.

**Comment by RobSiklos** [comment]
Pull request #200 (single commit).

**Comment by RobSiklos** [comment]
@kzu Any reason why the pull request hasn't been merged yet?

**Comment by stakx** [comment]
I guess we can close this issue, now that #200 has been merged.
