### ISSUE TITLE
Feature request: Promote Invocation.ReturnValue to IInvocation

### ISSUE THREAD

**Issue by MaStr11** [moq/moq4#920]
The `Invocation` class has a property `ReturnValue`:
https://github.com/moq/moq4/blob/a12fe5b1fc2eb7857799d5a7bb5cc9e18f61aace/src/Moq/Invocation.cs#L69

The `IIvocation` interface does not include this property:
```CS
namespace Moq
{
	public interface IInvocation
	{
		MethodInfo Method { get; }
		IReadOnlyList<object> Arguments { get; }
	}
}
```

While the argument values of the invocation are accessible, the return value is not. Is it possible to make the return value part of the interface?

```CS
namespace Moq
{
	public interface IInvocation
	{
		MethodInfo Method { get; }
		IReadOnlyList<object> Arguments { get; }
		/// <summary>
		/// Gets the return value of the invocation.
		/// </summary>                
                object ReturnValue { get; }
	}
}
```

A related discussion of why the return value wasn't included in the first place can be found here:
https://github.com/moq/moq4/issues/560#issuecomment-355815230

I currently use reflection to access the Invocation.ReturnValue and the value is set to the correct value.

**Comment by stakx** [comment]
Yes, Moq does record the return value these days. See my comment in your PR for the reason why I haven't yet added `ReturnValue` to the public API despite that fact.
