### ISSUE TITLE
Getting value of property through read-only interface returns default

### ISSUE THREAD

**Issue by Faibbus** [moq/moq4#923]
I have an interface A with a read-only property P, and a derived interface B
that shadows P as read/write. When I mock using interface B to write P,
and pass that mocked object to a service expecting interface A, P “becomes” null.

I observed this behaviour on both v4.8.2 and v4.13.0.

```csharp
using Moq;
using NUnit.Framework;
public interface IReadOnly
{
	int Value { get; }
}
public interface IReadWrite : IReadOnly
{
	new int Value { get; set; }
}

public class Tester
{
	[Test]
	public void TestMock()
	{
		var readWrite = new Mock<IReadWrite>();
		readWrite.SetupAllProperties();
		readWrite.Object.Value = 42;
		IReadOnly readOnly = readWrite.Object;
		Assert.AreEqual(readWrite.Object.Value, readOnly.Value);
	}
}
```

**Comment by stakx** [comment]
Simple answer, `IReadOnly.Value` and `IReadWrite.Value` are two distinct properties. You're telling the compiler via the `new` keyword. So obviously setting one property won't affect the other one.
