### ISSUE TITLE
Can not instantiate proxy of class

### ISSUE THREAD

**Issue by robertok77** [moq/moq4#924]
Hi,
I 've created object of a class with parameterless constructor.
On the other hand when I tried to mock this class, I got exception 'Can not instantiate proxy of class. Could not find a parameterless constructor'. 
See attached file.

![MockParameterlessConstructor](https://user-images.githubusercontent.com/14275269/64459033-39660e80-d0f7-11e9-8ca9-89bbe4e08800.png)

regards
Robert

**Comment by stakx** [comment]
Not much that can be gleaned from one screenshot. Please post some short, minimal, executable code.

**Comment by robertok77** [comment]
I edited my code after I reminded about DynamicProxy is underneath and no more posts are necessary
