### ISSUE TITLE
Quickstart guide add callback which sets mock setup property

### ISSUE THREAD

**Issue by informatorius** [moq/moq4#926]
Should we add this example to Quickstart guide?

```
// access invocation arguments and set to mock setup property
mock.SetupProperty(foo=>foo.Bar);
mock.Setup(foo => foo.DoSomething(It.IsAny<string>()))
    .Callback((string s) => mock.Object.Bar=s)
    .Returns(true);
```

**Comment by stakx** [comment]
Hi @informatorius, everyone can edit the Wiki, so if you feel this addition is sufficiently frequent and general in nature to be of use to others, and a good fit with the current form & structure of the Quickstart page, then go ahead... no need to ask for permission. :wink:
