### ISSUE TITLE
regression when updating from 4.12 to 4.13

### ISSUE THREAD

**Issue by patriziobruno** [moq/moq4#928]
My tests started failing after updating from 4.12 to 4.13:

System.ArgumentException : Matcher 'It.IsAny<byte[]>()' is unmatchable: An implicit conversion operator will convert arguments of type 'byte[]' to the parameter's type 'RedisValue', which is assignment-incompatible.

RedisValue has an implicit conversion to byte[] and viceversa.

`public static implicit operator RedisValue(byte[] value)`

`public unsafe static implicit operator byte[](RedisValue value)`

this is my code mocking `StackExchange.Redis`' `IDatabaseAsync` iface:
```cs
Setup(_ => _.SortedSetAddAsync(It.IsAny<string>(),
                It.IsAny<byte[]>(),
                It.IsAny<double>(),
                It.IsAny<When>(),
                It.IsAny<CommandFlags>()))
                .Returns<RedisKey, RedisValue, double, When, CommandFlags>((k, hk, i, w, f) => run(runImmediately, () => redis.Object.SortedSetAdd(k, hk, i, w, f)));
```

**Comment by stakx** [comment]
This was a planned change and is [mentioned in the changelog](https://github.com/moq/moq4/blob/v4.13.0/CHANGELOG.md#changed):

> Moq will throw when it detects that an argument matcher will never match anything due to the presence of an implicit conversion operator. (@michelcedric, #897, #898)

Have you verified whether your setup (the one that now causes the exception) was ever actually matched? If so, then we might indeed have a regression; please post a MCVE (minimally complete & verifiable code example). If not, then the error is telling you about a mistake in your mock's setup.

**Comment by patriziobruno** [comment]
Hi @stakx

Thanks for getting back on this so quick.

My setup is always matched and working with 4.12.0.

I'll post a MCVE as soon as I'm back to my workstation tomorrow. Do you need a full project or a simple xunit test method is enough?

**Comment by stakx** [comment]
> Do you need a full project or a simple xunit test method is enough?

A single xUnit test should be enough, provided that referenced types are either included, or it's clear in what NuGet package & namespace they're defined.

Cheers!

**Comment by patriziobruno** [comment]
Sorry for the long wait, here's the xUnit I promised. It requires [StackExchange.Redis](https://www.nuget.org/packages/StackExchange.Redis/2.0.601), [xunit ](https://www.nuget.org/packages/xunit/2.4.1)and [xunit.assert](https://www.nuget.org/packages/xunit.assert/2.4.1) 2.4.1 to run. I'm also using [xunit.runner.visualstudio](https://www.nuget.org/packages/xunit.runner.visualstudio/2.4.1), but it shouldn't be needed.

```cs

        [Fact]
        public async Task JustTest()
        {
            var mock = new Mock<IDatabase>();
            var hit = false;
            mock.Setup(_ => _.HashSet(It.IsAny<string>(),
                    It.IsAny<string>(),
                    It.IsAny<byte[]>(),
                    It.IsAny<When>(),
                    It.IsAny<CommandFlags>()))
                    .Returns<RedisKey, RedisValue, RedisValue, StackExchange.Redis.When, CommandFlags>((k, hk, hv, w, f) => hit = true);
            mock.Object.HashSet("key", "hash", new byte[] { 0x00 });
            Assert.True(hit);
        }

```

**Comment by stakx** [comment]
Thanks for the test.

* When I execute it against Moq 4.13.0, it produces the error message you've described above.

* When I execute it against Moq 4.12.0 or 4.11.0, the test fails because `hit` is `false`.

Which confirms that your setup doesn't actually get hit, and Moq is correct in pointing this out by producing the error message.

**Comment by patriziobruno** [comment]
I tried to run this same test myself and I confirm your findings, I had a bug in my tests and the update exposed it. Thanks
