### ISSUE TITLE
VerifyAll() setup for mock that no method was called

### ISSUE THREAD

**Issue by informatorius** [moq/moq4#929]
Do we have an option to VerifyAll() a Mock to check that no method was called? Or that no method was called without a setup? 

Because I may mock a big interface and only setup one method. Then I want to verify that no other method was called.

**Comment by stakx** [comment]
That's what strict mocks are for. Specify `MockBehavior.Strict` when you create the mock. That'll make the mock throw for all calls that weren't set up.

Alternatively, verify expected calls then finish with `mock.VerifyNoOtherCalls()`.
