### ISSUE TITLE
Mocks.Of in the quickstart

### ISSUE THREAD

**Issue by AlexKeySmith** [moq/moq4#93]
I didn't realise Mocks.Of existed until digging around the internet / the api.

It would be great to feature it in the QuickStart.

**Comment by LeonidLevin** [comment]
`Mock.Of` is now described in QuickStart.

This issues can be closed!

**Comment by kzu** [comment]
Yay! :)

**Comment by AlexKeySmith** [comment]
Yay!

**Comment by stakx** [comment]
Yay! :)
