### ISSUE TITLE
Controller Mock return null for ActionResult other return types like int working fine

### ISSUE THREAD

**Issue by RajaduraiAz** [moq/moq4#936]
I have similar work case for [this stackoverflow question](https://stackoverflow.com/questions/41824352) mocking method inside controller

[TestMethod]
public void Index()
{
    // Arrange
    var controller = Mock.Of<HomeController>(m => m.GetCheckStatus() == "Hi from Moq");
    
    // Act
    var result = controller.Index();

    // Assert
    Assert.IsNotNull(result);
}

public ActionResult Index()
        {
            return View();
        }
It's return null value. But if we change Index return type int it's working fine

**Comment by stakx** [comment]
Hi @RajaduraiAz, please note that this issue tracker focuses on Moq development, i.e. on feature requests and bug report. Please don't post pure usage questions here, as we don't have the capacity ro answer them all.

**Comment by RajaduraiAz** [comment]
@stakx  I think this is not usage related question. Moq return null value for Custom type but it's working defined data types like int. So only this posted here
