### ISSUE TITLE
Original mocked type not included after downcasting and Get 

### ISSUE THREAD

**Issue by pjquirk** [moq/moq4#943]
Consider this code:

```cs
using Moq;

public class Program
{
    public interface B { }
    public interface A : B { } 
    	
    public static void Main() 
    {
        Mock<A> a = new Mock<A>();
	// a.As<A>();  // workaround
        B b = a.Object;
        Mock<B> mockb = Mock.Get(b);
        Mock<A> c = mockb.As<A>();  // throws
    }
}
```
The line to assign `c` fails with an `InvalidOperationException` because it doesn't think the mock that wraps `B` implements `A`.  Note that uncommenting the 'workaround' line fixes the problem.

The workaround makes me think this is a bug rather than intended behavior.

**Comment by stakx** [comment]
Hi @pjquirk, and thanks for reporting this.

To be honest, I'm not sure whether to classify this as a "bug", or as an "enhancement". But I'm happy to go along with your suggestion that this is a bug.
