### ISSUE TITLE
IDE0008 Use explicit type instead of 'var'

### ISSUE THREAD

**Issue by connywesth** [moq/moq4#971]
![image](https://user-images.githubusercontent.com/3123534/74102092-a5362280-4b40-11ea-87d3-3eead0638246.png)

Should it be better to always use specific typing and avoid the var-type at all. That is what is recomended by Microsoft itself.

I only found this issue 23 times in one file of the entire Mock-library, and that is only in the file MatchExpressionFixture.cs in the Mock.Tests(netcoreapp2.2). 

This is found in Moq4 version 4.13.1.

**Comment by stakx** [comment]
> [...] always use specific typing and avoid the var-type at all. That is what is recomended by Microsoft itself.

That's a rather questionable recommendation, IMHO. `var` definitely has its uses, e.g. to avoid repetition (`T x = new T(...)`), especially when that `T` is a `TypeWithAnImpracticallyLongName`, or in situations where the type simply isn't important for understanding.

I think it's fine to decide between `var` and explicitly named types on a case by case basis.

**Comment by connywesth** [comment]
The var-declaration only occurs in one place only in the entire Mock-project.

**Comment by stakx** [comment]
I remain unconvinced that Microsoft's recommendation is sound in each and every circumstance. Simple appeal to authority isn't a sufficient argument, and if they really wanted to categorically avoid `var`, perhaps they shouldn't have added that keyword to the language in the first place, right? :wink: By that, I mean to say that this recommendation obviously doesn't have the character of an eternal truth; it is simply someone's preference.

If Microsoft's goal were to nudge us into explicitly specifying types, we'd also have to do that in many different places, e.g. for lambda parameter lists: `x => x + 1` would have to become `(int x) => x + 1`.

In all honesty, I don't see a problem here. Let's leave `var` usage as is, those 23 uses are not worth spending much time on discussing, reviewing PRs, etc.
Further than that, I bet that there are a lot of other places where the Moq source code doesn't mention types explicitly; e.g. with lambda parameters.

**Comment by stakx** [comment]
(Btw. `var` is used elsewhere, too, not just in `MatchExpressionFixture`. Makes me wonder whether your code analysis settings are correct; and if so, why it only complains about that one file.)

**Comment by connywesth** [comment]
Well, this is not my decisiton, I just reported something that anoys me in code. I follow the VisualStudio recommendations as far it's possible in my code. My life gets somewhat easier then.
