### ISSUE TITLE
Interface Default methods are ignored

### ISSUE THREAD

**Issue by hahn-kev** [moq/moq4#972]
I'm not sure if this would be considered a bug, but I'd think it would work the same as mocking an abstract class.

Example
```C#
interface ITest
{
    string CallMe();

    string CallMeDefault()
    {
        return CallMe();
    }
}

[Fact]
public void DefaultFails()
{
    var mock = new Mock<ITest>(MockBehavior.Loose);
    mock.Setup(t => t.CallMe()).Returns("hello");
    Assert.NotNull(mock.Object.CallMeDefault());
}
```

My interface has the method `CallMeDefault` which has an implementation, however when I mock that interface it gets overridden and calling that method returns null instead of what `CallMe` returns as I'd expect. I think ideally this would follow the CallBase setting, however it doesn't seem like it does.

**Comment by stakx** [comment]
Before Moq can support default interface methods, DynamicProxy must add support for them; see https://github.com/castleproject/Core/issues/447.

**Comment by stakx** [comment]
@hahn-kev: OK, I think this can be made to work. You'll have to configure `CallBase` behavior for your `CallMeDefault` interface method, either at the setup level:

```diff
 var mock = new Mock<ITest>(MockBehavior.Loose);
 mock.Setup(t => t.CallMe()).Returns("hello");
+mock.Setup(t => t.CallMeDefault()).CallBase();
 Assert.NotNull(mock.Object.CallMeDefault());
```

or at the mock level (whatever is a better fit for your tests):

```diff
-var mock = new Mock<ITest>(MockBehavior.Loose);
+var mock = new Mock<ITest>(MockBehavior.Loose) { CallBase = true };
 mock.Setup(t => t.CallMe()).Returns("hello");
 Assert.NotNull(mock.Object.CallMeDefault());
```

In terms of default interface implementations, `.CallBase()` shall call [the most specific override](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-8.0/default-interface-methods#the-most-specific-override-rule).
