### ISSUE TITLE
Mocked method call with multiple specific parameter call returns null

### ISSUE THREAD

**Issue by SayusiAndo** [moq/moq4#973]
Hi Folks,

Could you take a look at [this](https://stackoverflow.com/questions/60441646/how-to-setup-moq-for-the-same-method-where-return-value-depends-on-input) issue? I can't decide whether I'm doing something wrong - documentation doesn't specify a special case like this - or I found a defect.

**Comment by stakx** [comment]
No runnable repro &rArr; closing this issue for now.
