### ISSUE TITLE
Mocking Fluent API

### ISSUE THREAD

**Issue by BlythMeister** [moq/moq4#981]
In order to mock a fluent builder api, i created the extension class

```
    public static class MockExtensions
    {
        public static IReturnsResult<T> SetupFluent<T>(this Mock<T> mock, Func<T, T> setupAction) where T : class
        {
            return mock.Setup(x=> setupAction(x)).Returns(mock.Object);
        }
    }
```

This feels like something that would be pretty handy to have natively.

Is there a way to do this natively already?

**Comment by stakx** [comment]
Can you perhaps explain a little how you'd typically use this method? As far as I can tell, this would be used to set up methods to "loopback" to the instance:

```csharp
public partial interface IX
{
    IX GetThis();
}

var mock = new Mock<IX>();
mock.SetupFluent(x => x.GetThis());

Assert.Same(mock.Object, mock.Object.GetThis());
```

Perhaps I'm missing something here? If not, it looks like a rather narrow special case, so it's perhaps better to define this outside the library.

**Comment by BlythMeister** [comment]
```
public interface IX
{
    IX Setup1(string input);
    IX Setup2(string input);
}
```

To use this in real terms

```
public void Do()
{
   var thing = new IXClass().Setup1("a").Setup2("b");
}
```

and mock usecase

```
var mock = new Mock<IX>();
mock.SetupFluent(x => x.Setup1("a"));
mock.SetupFluent(x => x.Setup2("b"));
```

**Comment by BlythMeister** [comment]
also, realised my extension was wrong, should be

```
public static class MockExtensions
    {
        public static IReturnsResult<T> SetupFluent<T>(this Mock<T> mock, Expression<Func<T, T>> setupAction) where T : class
        {
            return mock.Setup(setupAction).Returns(mock.Object);
        }
    }
```

**Comment by stakx** [comment]
Ah, you want to do method chaining on the same mock. That should be easy to do using **`SetReturnsDefault`**:

```csharp
var mock = new Mock<IBuilder>();
mock.SetReturnsDefault<IBuilder>(mock.Object);
```

Any method having a return type of `IBuilder` will then return `mock.Object`, unless you override that default using a setup.

It shouldn't be necessary to add a fairly specific helper method to the library if the same thing can be already be achieved using an existing, but more general mechanism.

**Comment by BlythMeister** [comment]
ahhh that's exactly what i want!

_changes all use of my extension method to SetReturnsDefault_
