### ISSUE TITLE
MissingMethodException on virtual method with in parameter

### ISSUE THREAD

**Issue by grokys** [moq/moq4#988]
Repro (moq 4.13.1):

```csharp
    public class Foo
    {
        public void Run()
        {
            Virtual(new Bar<int>());
        }

        public virtual void Virtual<T>(in Bar<T> bar)
        {
        }
    }

    public readonly struct Bar<T>
    {
        T Value { get; }
    }
```

```csharp
var mock = new Mock<Foo>();
mock.Object.Run();
```

Throws exception:

```
System.MissingMethodException
  HResult=0x80131513
  Message=Method not found: 'Void ConsoleApp1.Foo.Virtual(ConsoleApp1.Bar`1<Int32> ByRef)'.
  Source=DynamicProxyGenAssembly2
  StackTrace:
   at Castle.Proxies.FooProxy.Virtual[T](Bar`1& bar)
   at ConsoleApp1.Foo.Run() in D:\temp\ConsoleApp1\ConsoleApp1\Program.cs:line 21
   at ConsoleApp1.Program.Main(String[] args) in D:\temp\ConsoleApp1\ConsoleApp1\Program.cs:line 13
```

Seems that the combination of a generic struct and an `in` parameter confuses moq somewhere.

**Comment by stakx** [comment]
I'm almost certain that this not caused by Moq, but by a long-standing bug in the runtime; see https://github.com/dotnet/runtime/issues/25958.

**Comment by stakx** [comment]
Small update: It appears that updating to .NET 6 (once released) will take care of this problem. The issue described above is no longer reproducible on [.NET 6 Preview](https://dotnet.microsoft.com/download/dotnet/6.0).

**Comment by stakx** [comment]
If there's any further news on this, I'll post them in #1148.
