### ISSUE TITLE
ISetupSequentialResult doesn't support Pass for async void methods.

### ISSUE THREAD

**Issue by fuzzybair** [moq/moq4#993]
`ISetupSequentialAction` provides `Pass()` and `Throws<TException>()` for synchronous method calls with void return types. But because async void methods return a Task `SetupSequence()` uses `ISetupSequentialResult<Task>`. Pull Request #261 added support for ReturnsAsync and ThrowsAsync if there is a return type `async Task<TResult> DoAsync()` but it does not support Pass and ThowsAsync for void returns like `async Task DoAsync()`.

If you are interested I could set up a pull request to add 
`public static ISetupSequentialResult<Task> PassAsync(this ISetupSequentialResult<Task> setup)`
and 
`public static ISetupSequentialResult<Task> ThrowsAsync(this ISetupSequentialResult<Task> setup, Exception exception)`

**Comment by stakx** [comment]
Hi @fuzzybair, sorry for the delayed response. Sounds like a reasonable enhancement, feel free to submit a PR, if you'd like. Note that there should probably also be two additional overloads covering `ValueTask`.

**Comment by fuzzybair** [comment]
No problem for the delay we all have busy lives 😃 I have added the pull request https://github.com/moq/moq4/pull/1006

**Comment by stakx** [comment]
Closed by #1006.
